### ISSUE TITLE
✨ [Feature request]: Validation: Restrict creating play with existing name

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#1010]
### Is your feature request related to a problem? Please describe.

Add validation to restrict creating play with existing name

### Describe the solution you'd like.

Add validation to restrict creating play with existing name

### Describe alternatives you've considered.

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@koustov so if you create a play, say "Test", won't I be able to create a play called "Test"? Is that right?
