### ISSUE TITLE
🐛 [Bug report]: #2PlaysAMonth tag not working to Filter Plays

### ISSUE THREAD

**Issue by Abhishek-90** [reactplay/react-play#1014]
### Descrcibe the bug?

When we try to filter the plays using #2PlaysAMonth tag, we are displayed that "Play Not Found"

### Steps to reproduce the bug?

1. Go to https://reactplay.io/plays
2. Click on Filter Icon near search bar.
3. Go to tag option, select #2PlaysAMonth option and click Apply.

### Expected behavior

All the plays should be filter and only plays having #2PlaysAMonth Should be displayed

### Desktop (Please provide your system information)

NA

### Screenshot / Screenshare

![Screenshot_1](https://user-images.githubusercontent.com/43419831/221584226-00c9b772-e459-4514-aab4-55f62923b39f.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/43419831/221584235-54a4cf3c-069f-4b95-9b28-4242467eded7.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
It's fixed now
