### ISSUE TITLE
🐛 [Bug report]: When activities on, the mobile view is missing the browse button

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#1019]
### Descrcibe the bug?

When activity is on, the reactplay web site misses the browse button on the mobile.

Expected the browse button should be available to see all the plays.

### Steps to reproduce the bug?

1. Launch reactplay.io on mobile view
2. Look out for the browse button

### Expected behavior

The browse button should be available.

### Desktop (Please provide your system information)

All

### Mobile (Please provide your device information)

All

### Screenshot / Screenshare

No Browse button

![image](https://user-images.githubusercontent.com/3633137/221747170-838ee6b8-9137-4be5-9965-577c963b467d.png)

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yeshwantthota** [comment]
can i work on this issue?

**Comment by atapas** [comment]
> can i work on this issue?

You can.

**Comment by thekrprince** [comment]
Can I work on this issue if it's not resolved?

**Comment by karthiknadar1204** [comment]
If this issue is still open ,i would like to work on it

**Comment by Tahmeerpasha** [comment]
If the issue is still open, I would like to work on this. Can you assign me this issue?

**Comment by atapas** [comment]
@Tahmeerpasha Do you want to take it up?

**Comment by Tahmeerpasha** [comment]
> @Tahmeerpasha Do you want to take it up?

Sure.

**Comment by jayshahWebDev** [comment]
issue is still open? i would like to work on it.
