### ISSUE TITLE
✨ [Feature request]: In filter modal creator dropdown should be a card list with image 

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#102]
**Is your feature request related to a problem? Please describe.**
Currently, the creator dropdown is a flat list. It doesn't give enough context of the GitHub profile

**Describe the solution you'd like**
Use a contact card drop-down  instead

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment]
@atapas @koustov , I would like to work on this issue.

**Comment by atapas** [comment]
@Sachin-chaurasiya Assigned. Let's discuss the design approach for this one first. Please open a discussion thread.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Assigned. Let's discuss the design approach for this one first. Please open a discussion thread.

@atapas , Sure will do that.

**Comment by Sachin-chaurasiya** [comment]
@atapas , Opened one discussion thread here https://github.com/atapas/react-play/discussions/213

**Comment by atapas** [comment]
Hey @Sachin-chaurasiya 

Are you on it?

**Comment by Sachin-chaurasiya** [comment]
> Hey @Sachin-chaurasiya
> 
> Are you on it?

Hey @atapas , Didn't get a chance to look further.

**Comment by atapas** [comment]
> > Hey @Sachin-chaurasiya
> > Are you on it?
> 
> Hey @atapas , Didn't get a chance to look further.

Will you work on it in the near future?

**Comment by Sachin-chaurasiya** [comment]
> > > Hey @Sachin-chaurasiya
> > > Are you on it?
> > 
> > Hey @atapas , Didn't get a chance to look further.
> 
> Will you work on it in the near future?

**Comment by Sachin-chaurasiya** [comment]
> > > Hey @Sachin-chaurasiya
> > > Are you on it?
> > 
> > 
> > Hey @atapas , Didn't get a chance to look further.
> 
> Will you work on it in the near future?

Yes @atapas , I will start working on it this weekend.
