### ISSUE TITLE
[#2PlaysAMonth]: Flash cards

### ISSUE THREAD

**Issue by raibove** [reactplay/react-play#1024]
### What's the Play about?

Create Flash Cards to quickly revise concepts.

### What ReactJS concept will be used to create this play?

Hooks, Component

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
> Can you tell me more about this, I would like to take this up :)

@raibove are you not working on it already?

**Comment by raibove** [comment]
I was working but didn't make any significant progress yet. If @elite16op wants to work on this you can unassign me from this issue

**Comment by elite16op** [comment]
Thanks a lot, I would love to make this 😄

**Comment by atapas** [comment]
> Thanks a lot, I would love to make this 😄

Assigned

**Comment by elite16op** [comment]
I have created the project on this repo https://github.com/elite16op/reactFC.git
I am not able to run after cloning your repo because of technical limitations, my system keeps on crashing.
