### ISSUE TITLE
[#2PlaysAMonth]: Wordle Game

### ISSUE THREAD

**Issue by SamirMishra27** [reactplay/react-play#1025]
## Wordle Unlimited

This play is about the popular text puzzle game **Wordle!** with enhanced features

- Ability to play unlimited wordle in a day
- Daily Streaks: Keep up your streak by playing wordle at least once a day. (No matter if you lose or win)
- In case of missing a day, the streak won't be reset but instead will be reduced by some points
- Guess the hidden word in 6 attempts!
- All time stats showing your number of games and attempts distribution on a graph.

## Concepts which will be used

- React's **`useState()`**
- React's **`useRef()`**
- React's **`useEffect()`**
- Functional Components &
- Props!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
Hey @SamirMishra27, it would be good if you add a descriptive title for the issue, thanks.
