### ISSUE TITLE
✨ [Feature request]: Add my blog url for the object detector play.

### ISSUE THREAD

**Issue by senali-d** [reactplay/react-play#1040]
### Is your feature request related to a problem? Please describe.

I have developed a play called Object Detector as a part of the 2Plays-A-Month challenge. Now I want to add the blog link to my play. It is already merge to main branch. Now I need to update Readme with my blog link.

Play name: Object Detector 
Play Link: https://reactplay.io/plays/senali-d/object-detector

### Describe the solution you'd like.

no

### Describe alternatives you've considered.

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishav1707** [comment]
Please provide your play blog link, I will add that link to the object detector README.md file

**Comment by ArslanYM** [comment]
@senali-d fixed in the above PR , i workd on it without getting assigned because It was becoming a stale issue.

**Comment by atapas** [comment]
> @senali-d fixed in the above PR , i workd on it without getting assigned because It was becoming a stale issue.

It's not stale @ArslanYM

**Comment by ArslanYM** [comment]
> > @senali-d fixed in the above PR , i workd on it without getting assigned because It was becoming a stale issue.
> 
> It's not stale @ArslanYM

I didnt say it is.

**Comment by atapas** [comment]
> > > @senali-d fixed in the above PR , i workd on it without getting assigned because It was becoming a stale issue.
> > 
> > 
> > It's not stale @ArslanYM
> 
> I didnt say it is.

My bad! Have you fixed it already? Should I assign it to you?

**Comment by ArslanYM** [comment]
> 

Yes it has been fixed in #1079

**Comment by ArslanYM** [comment]
@atapas yeah fixed in #1082
