### ISSUE TITLE
🐛 [Bug report]: ally fix for hamberger menu

### ISSUE THREAD

**Issue by shrilakshmishastry** [reactplay/react-play#1041]
### Descrcibe the bug?

Currently there is no aria-label provided for the hamburger menu 
<img width="1352" alt="Screenshot 2023-03-07 at 11 32 23 PM" src="https://user-images.githubusercontent.com/29778698/223509976-bfa1d0cb-ffc7-4ca8-b2d1-cb1fdfc34acc.png">

### Steps to reproduce the bug?

1. Go to landing page in mobile mode , you will get it by checking accessibility tree

### Expected behavior

add aria-label and aria-expanded to take care of visibility of menu

### Desktop (Please provide your system information)

firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyamtawli** [comment]
Can I work on it.

**Comment by atapas** [comment]
> Can I work on it.

Assigned to you.

**Comment by shyamtawli** [comment]
Hey, getting error while running npm install. Can you guide me into it? 
I have searched about it and I found that I have to update @mui/styles to a version that supports React 18

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-play@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from @mui/styles@5.11.12
npm ERR! node_modules/@mui/styles
npm ERR!   @mui/styles@"^5.9.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by deepchauhan2002** [comment]
hey, I want to work on this issue

**Comment by shyamtawli** [comment]
@deepchauhan2002 I am working on it.

**Comment by atapas** [comment]
This is done
