### ISSUE TITLE
🐛 [Bug report]: Error in the README.md file

### ISSUE THREAD

**Issue by Tonie-NG** [reactplay/react-play#1043]
### Descrcibe the bug?

When trying to run cypress locally, the npm command on the READ,E.md is `npm cypress:open` instead of `npm run cypress:open`

If approved, I would love to be assigned this issue

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshi-kaushal** [comment]
Hi! Glad you noticed this. Assigning this issue to you. Please ensure you follow [contribution guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md). Hop into our [community](https://discord.gg/vrTxWUP8Am) if you want to share anything.

**Comment by Tonie-NG** [comment]
Thank you @joshi-kaushal. Please help me with the versioning (I don't quite understand it). Can you help me (That is if I have to version at all?

**Comment by Tonie-NG** [comment]
@joshi-kaushal It's alright. Reading through the docs, I saw some mention of release version and stuff, just wanted to confirm. I've submitted a pull request, kindly check it out
