### ISSUE TITLE
🐛 [Bug report]: a tag styling of pink color which is affecting all the list tags in the entire repo

### ISSUE THREAD

**Issue by PriteshKiri** [reactplay/react-play#1046]
### Descrcibe the bug?

The li tag has been given a tag styling of pink color which is affecting all the list tags in the entire repo

### Steps to reproduce the bug?

Replace li tag with some class for styling in play-dictionary play 

### Expected behavior

Need to add a class instead of "li" tag for adding styling to the list element in play-dictionary play

### Desktop (Please provide your system information)

Browser: chrome

### Screenshot / Screenshare

This is the problem we are facing:
<img width="1130" alt="Screenshot 2023-03-08 at 11 48 51 AM" src="https://user-images.githubusercontent.com/77957844/223634609-6759efa9-82f3-4cb2-a4b4-eaf9811c7267.png">

Reason behind this issue
<img width="278" alt="Screenshot 2023-03-08 at 11 50 08 AM" src="https://user-images.githubusercontent.com/77957844/223634820-59e70cbb-850a-425a-aefc-486f01f0ee01.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@Abhishek-90 this mostly introduced from your play. Can you please check?

**Comment by Abhishek-90** [comment]
@atapas I'll fix it.

**Comment by atapas** [comment]
> @atapas I'll fix it.

Thanks! Assigned to you. Please raise a PR with fix.
