### ISSUE TITLE
🐛 [Bug report]: Typo in codeNchill play

### ISSUE THREAD

**Issue by PriteshKiri** [reactplay/react-play#1050]
### Descrcibe the bug?

Typo error on modal of code and chill

### Steps to reproduce the bug?

Rename it to codeNchill

### Expected behavior

Rename it to codeNchill

### Desktop (Please provide your system information)

Browser: Chrome

### Screenshot / Screenshare

<img width="845" alt="Screenshot 2023-03-09 at 6 50 43 PM" src="https://user-images.githubusercontent.com/77957844/224035566-7a6e236f-d7d4-44c4-817b-bbf3b8177168.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@PriteshKiri Let me know when the PR is ready.

**Comment by PriteshKiri** [comment]
Created a PR: https://github.com/reactplay/react-play/pull/1052
