### ISSUE TITLE
✨ [Feature request]: Add Dark Mode

### ISSUE THREAD

**Issue by Shoaib19** [reactplay/react-play#1051]
### Is your feature request related to a problem? Please describe.

There is no dark mode theme for web users.

### Describe the solution you'd like.

Add dark mode theme for web users.

### Describe alternatives you've considered.

Also can change the theme of the web from white to any other dark color.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishav1707** [comment]
> ### Is your feature request related to a problem? Please describe.
> There is no dark mode theme for web users.
> 
> ### Describe the solution you'd like.
> Add dark mode theme for web users.
> 
> ### Describe alternatives you've considered.
> Also can change the theme of the web from white to any other dark color.
> 
> ### Screenshot / Screenshare
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Because may be it is a combination of light mode as well as dark mode

**Comment by Shoaib19** [comment]
No, I don't agree only the hero image is comfortable for eye when user scrolls down he/she experience entire website in light mode.

**Comment by Palakkgoyal** [comment]
I would love to pickup this issue.

**Comment by Palakkgoyal** [comment]
Can I pickup this one?

**Comment by MeghavatiChaudhari** [comment]
@atapas sir @priyankarpal ma'am can you please assign this issue to me? surely I can do this.
