### ISSUE TITLE
🐛 [Bug report]: Tons of calls being made on play refresh

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#1058]
### Descrcibe the bug?

When you refresh a play page, there are many calls being made which are not related to the page. 

### Steps to reproduce the bug?

1. Open reactplay.io
2. Browse plays
3. Open any play
4. Open developer console 
5. Refresh the page
6. Notice network tab

### Expected behavior

Only relevant data needs to be fetched

### Desktop (Please provide your system information)

ALL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
I would like to work on this @koustov.

**Comment by koustov** [comment]
> I would like to work on this @koustov.

Sure @Sachin-chaurasiya

**Comment by koustov** [comment]
@Sachin-chaurasiya I suppose this is related to #894

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya I suppose this is related to #894

Okay, I will investigate it.
