### ISSUE TITLE
🐛 [Bug report]: The "browse" and "plays" links don't seem to work on the website

### ISSUE THREAD

**Issue by impressivewebs** [reactplay/react-play#1070]
### Descrcibe the bug?

If you click "browse" it just goes to the home page. Same with "view all plays". Similar problem when clicking a trending play.

### Steps to reproduce the bug?

1. Go to https://reactplay.io/
2. Click the "browse" button at the top

### Expected behavior

I expect to be able to browse plays.

### Desktop (Please provide your system information)

Windows 10, Brave Browser, v1.49.120.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Hey @impressivewebs Thanks for reporting this issue.

I just tied on Chrome, not having Brave. Will check there too. Could you please check on any other browser once?

**Comment by atapas** [comment]
Ok great. May be some cache issue. I am closing it for now.
