### ISSUE TITLE
🐛 [Bug report]: greetings.yml workflow message does not have proper formatting.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/react-play#1074]
### Descrcibe the bug?

greetings.yml workflow message does not have proper formatting.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/59080942/226877558-c484cbb7-f8b0-4ab6-ba20-0ed80d410fa1.png">

Make the changes in this file --> https://github.com/reactplay/react-play/blob/main/.github/workflows/greetings.yml

### Steps to reproduce the bug?

Refer to this issue comment --> https://github.com/reactplay/react-play/issues/1073#issuecomment-1479302592

### Expected behavior

Should have proper formatting.

### Desktop (Please provide your system information)

NA

### Mobile (Please provide your device information)

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joypoddar** [comment]
Hi @Sachin-chaurasiya ,

I wish to work on this issue. But before that, I need to understand what are the deliverables and if at all I have the required knowledge to work on this issue.

By proper formatting, do you mean:

1. ReactPlay Discord Community should appear as a link.
2. Should Stale Marking and its description appear in bold?

Is the pic below a close representation of what is required?

![image](https://user-images.githubusercontent.com/11984043/226891002-561ce52b-ffca-496d-a584-b29c809459ff.png)

**Comment by rahulpandey70** [comment]
This looks much better and readable.

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya ,
> 
> I wish to work on this issue. But before that, I need to understand what are the deliverables and if at all I have the required knowledge to work on this issue.
> 
> By proper formatting, do you mean:
> 
> 1. ReactPlay Discord Community should appear as a link.
> 2. Should Stale Marking and its description appear in bold?
> 
> Is the pic below a close representation of what is required?
> 
> ![image](https://user-images.githubusercontent.com/11984043/226891002-561ce52b-ffca-496d-a584-b29c809459ff.png)

Yes @joypoddar , Assigning this issue to you.

**Comment by Sachin-chaurasiya** [comment]
@joypoddar , 
1. You can use this extension to validate the yml files https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
2. No.

**Comment by Sachin-chaurasiya** [comment]
Hello @joypoddar , Any progress here? Let me know if you need any help or have any queries.
