### ISSUE TITLE
[Add a play]: Github profile finder

### ISSUE THREAD

**Issue by PriyanshShrivastava** [reactplay/react-play#1080]
This issue has been created in order to create a play name Github Finder. As it is mandatory for a play to be linked with one of the issue. The play Github Finder gives you a brief about a specific user in a well designed UI.

**Comment by PriyanshShrivastava** [comment]
I have created this issue to add a play as it was mantadory to link your play to an issue and I cannot find any similar open issue.

**Comment by atapas** [comment]
> I have created this issue to add a play as it was mantadory to link your play to an issue and I cannot find any similar open issue.

Yes! Can you please edit the description and add more details to it?

**Comment by PriyanshShrivastava** [comment]
Thanks for your input, I have updated the description.

**Comment by Vishrut19** [comment]
Hey ! I can work on this issue

**Comment by PriyanshShrivastava** [comment]
I just created this issue for my play and I don't know why is it not getting merged. I read and checked all the points @atapas can you please update.

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
