### ISSUE TITLE
🐛 [Bug report]: Clicking any links on landing page do not redirect

### ISSUE THREAD

**Issue by WhyNotSantosh** [reactplay/react-play#1083]
### Descrcibe the bug?

When landed on https://reactplay.io/ and clicked on any links, nothing happens. Url is changing but page is not redirected.

### Steps to reproduce the bug?

Go to https://reactplay.io/

Click on any link

Redirection doesn't work

### Expected behavior

When any link is clicked on https://reactplay.io/, then redirection should happen as expected.

### Desktop (Please provide your system information)

OS: Windows 10
Browser: Chrome
Version: 111.0.5563.147 (Official Build) (64-bit)

### Screenshot / Screenshare

[screen-recorder-thu-mar-30-2023-12-50-22.webm](https://user-images.githubusercontent.com/105787626/228869929-4c45b7e9-bbaa-4bed-a44c-36357d1db72e.webm)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WhyNotSantosh** [comment]
Able to  find some clues. The main.js file served from static folder is served differently. See screenshots for main.js file with and without issue.

<img width="960" alt="mainjscorrect" src="https://user-images.githubusercontent.com/105787626/229019445-c5268c5c-80d0-4179-8adc-7b9967729445.png">
<img width="960" alt="mainjserror2" src="https://user-images.githubusercontent.com/105787626/229019473-b6b8e830-c4e7-4e87-9cdc-eaef6d91a218.png">
<img width="960" alt="mainjserror" src="https://user-images.githubusercontent.com/105787626/229019500-37242185-488f-4616-9768-fd599033bf30.png">

**Comment by hrshtmlng** [comment]
same is the issue with me

**Comment by atapas** [comment]
This is no more reproducible. If it happens, check the browser cache.
