### ISSUE TITLE
🐛 [Bug report]: In mobile view, the filters are not viewable

### ISSUE THREAD

**Issue by niteshseram** [reactplay/react-play#1087]
### Descrcibe the bug?

In mobile view, the filters are not viewable and is being truncated like in the sceeenshot below

### Steps to reproduce the bug?

1. Got to this page https://reactplay.io/plays from mobile view
2. Open the filters beside the top search bar
3. Open any dropdown from the popup
4. The dropdown items are not viewable and is being truncated

### Expected behavior

I think we can make the dropdown title and dropdown in two separate line

### Desktop (Please provide your system information)

OS-Windows 11
Browser-Chrome
Version-Version-111.0.5563.115

### Mobile (Please provide your device information)

Device- Samsung
Browser-Chrome
Version-111.0.5563.115

### Screenshot / Screenshare

![Screenshot_20230401-170228_Chrome](https://user-images.githubusercontent.com/51370246/229286459-d9402bf5-a255-470c-aa18-9d5801581d75.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by niteshseram** [comment]
I can work on this if fix is needed for this

**Comment by Sachin-chaurasiya** [comment]
@niteshseram , the Issue is assigned, you can go ahead.
