### ISSUE TITLE
🐛 [Bug report]: Renaming the existing play name leads us to the error.

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1089]
### Descrcibe the bug?

Whenever a user tries to change the name of the play locally from the `edit play` button, the window shows this page 👇.

![Screenshot (775)](https://user-images.githubusercontent.com/91705825/229430309-e4c4c96d-bd24-460e-bb69-70d46740a643.png)

Every time we create a play, a new folder is automatically generated along with a new `.js / .ts` file that is linked to it. However, when we modify the name of the play, the corresponding` .js` file name does not update accordingly, resulting in an incorrect path error.

To make it work, we have to change the name of the file manually every time.

- If we modify the name of the play using the `edit play` button on our local version, the `play` will disappear from the plays section on the **deployed version** until we upload the corresponding `.js` file. Alternatively, we have to rename it back to its original name.

- As a result, the app cannot be run by others in the locals unless the user renames or reverts the name of the play file.

### Steps to reproduce the bug?

1. Go to the play that you've built
2. Click on the edit play button
3. Rename your play
4. Now you'll see the bug.

Note: Try to do it in locals first.

### Expected behavior

 Whenever the user edits the play through that button, it renames the play in real time. Currently, instead of this, it shows 

- the error screen
- then the user has to rename the file name according to the name of the play
- then the user has to restart the server
- after that, the play is visible to the user (but only to locals)

**Note**: The play will be removed from the deployed version (if you're working on the existing play) in real-time

### Desktop (Please provide your system information)

- OS: Windows 10
- Browser: Chrome, Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TejasShekar** [comment]
@Shivam-Katare There seems to be no such issue as pointed out by you. Added screen recording zip for your reference.

[Recording 2023-09-30 150825.zip](https://github.com/reactplay/react-play/files/12774365/Recording.2023-09-30.150825.zip)

**Comment by TejasShekar** [comment]
@priyankarpal @atapas Any update on closing this issue ?
