### ISSUE TITLE
Make changes to footer description and links.

### ISSUE THREAD

**Issue by joypoddar** [reactplay/react-play#1090]
![image](https://user-images.githubusercontent.com/11984043/229455977-83a74a68-284f-4cbd-afaf-791674784242.png)

Latest change "An open-source project made with ❤️  by team ReactPlay."

Reference
[Discord Discussion Link](https://discord.com/channels/982239924227031070/1073937423031074887/1092313845084725249)

Also, change link of `create` -> "https://docs.reactplay.io/How-To-Guides/how-to-create-play"  and `get started` -> "https://docs.reactplay.io/"

**Comment by joypoddar** [comment]
@atapas Kindly let me know if the change needs to be synchronized here too. Assuming its affirmative, do assign me to this issue.

**Comment by atapas** [comment]
Loooks good to me.. However, let me know if you want to add to the text.

**Comment by joypoddar** [comment]
Tapas Adhikary and team looked good to me...

**Comment by joypoddar** [comment]
@atapas Can we make it to an open-source project made with ❤️ by team ReactPlay.

**Comment by atapas** [comment]
> @atapas Can we make it to an open-source project made with ❤️ by team ReactPlay.

Sounds good. Please do the same for hustles also.
