### ISSUE TITLE
✨ [Feature request]: Add dependabot gh action

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1091]
### Is your feature request related to a problem? Please describe.

Dependabot is a tool that helps automate the process of keeping your project's dependencies up-to-date. Adding Dependabot to your project can have several benefits

### Describe the solution you'd like.

We can add a simple gh action 

### Describe alternatives you've considered.

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Do you want to take it up?

**Comment by priyankarpal** [comment]
> Do you want to take it up?

Yeah, I want to work on it.
