### ISSUE TITLE
✨ [Feature request]: Revamp Playlist Page

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1097]
### Is your feature request related to a problem? Please describe.

Today the playlist page is full of cards. The current playlist page is cluttered with numerous cards that don't give an appealing look. Additionally, the plays are not sorted or categorized, causing a mix-up of all the plays.

### Describe the solution you'd like.

We need to categorize the plays logically. 

### Describe alternatives you've considered.

T.B.D

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
If this issue is still available,i would like to work on it,please assign it to me
