### ISSUE TITLE
[Add a Play]: Video Preview

### ISSUE THREAD

**Issue by guptaanshik1** [reactplay/react-play#1101]
### What's the Play about?

User will search a video and when the user hovers over the video thumbnail for 2-5 seconds then user will see a preview of the video

### What ReactJS concept will be used to create this play?

Consuming APIs to render images conditionally and to use timer efficiently in react js.

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suzy-g38** [comment]
Can I work on this one?

**Comment by guptaanshik1** [comment]
Hi @suzy-g38 I have picked this one up

**Comment by suzy-g38** [comment]
> Hi @suzy-g38 I have picked this one up

Sorry, I misunderstood. I really wanted to work on something, all the other issues were taken by someone and then saw this one and was not assigned to anyone so thought maybe this can be my chance at last. Anyway sorry.

**Comment by guptaanshik1** [comment]
Hey @suzy-g38 please don't be sorry. You can contribute your own play. Please check react-play website for once.

**Comment by atapas** [comment]
Hey @suzy-g38 join our discord. Lots going on there for you to contribute. Ping me on discord, I'll guide you.

**Comment by suzy-g38** [comment]
> Hey @suzy-g38 join our discord. Lots going on there for you to contribute. Ping me on discord, I'll guide you.

Hey, @atapas thank you. Yesterday I already joined the discord channel as Vizard. I have pinged you.

**Comment by guptaanshik1** [comment]
Hi @atapas, can you give me discord link please.

**Comment by atapas** [comment]
> Hi @atapas, can you give me discord link please.

https://discord.gg/UfYj4MvW9A

**Comment by atapas** [comment]
> > Hey @suzy-g38 join our discord. Lots going on there for you to contribute. Ping me on discord, I'll guide you.
> 
> Hey, @atapas thank you. Yesterday I already joined the discord channel as Vizard. I have pinged you.

Pinged you there
