### ISSUE TITLE
🐛 [Bug report]: Button Text not centered

### ISSUE THREAD

**Issue by Abhishek-90** [reactplay/react-play#1107]
### Descrcibe the bug?

On the homepage, the button text for button `browse` and `Github` are not centered when viewed on mobile or smaller screens.

### Steps to reproduce the bug?

On Smaller screens:
1. Go to reactplay.io

On Bigger Screens:
1. Go to reactplay.io
2. Open console
3. Click on Device Toggle button

### Expected behavior

The text should appear in the center of the button as it appears on bigger devices.

### Desktop (Please provide your system information)

NA

### Screenshot / Screenshare

![Screenshot_1](https://user-images.githubusercontent.com/43419831/231482311-a66c544e-ed40-4fa2-8f8a-120358aa33af.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amanaakash** [comment]
Hey , can i contribute to solve this bug ?

**Comment by mohammedkharoda** [comment]
Can please review my code and merge it after review
