### ISSUE TITLE
chore:  add new Netlify image

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1116]
On the footer section, the Netlify image got removed(may be). We need to add a new image

![image](https://user-images.githubusercontent.com/88102392/232367310-3d918f66-9939-4749-b215-c6d7e32b5989.png)

**Comment by Saurav-Pant** [comment]
assign it to me i will work on it @priyankarpal

**Comment by atapas** [comment]
> assign it to me I will work on it

Done

**Comment by Saurav-Pant** [comment]
#1119 this is the PR
