### ISSUE TITLE
'Share about ReactPlay' link in footer doesn't work.

### ISSUE THREAD

**Issue by joypoddar** [reactplay/react-play#1123]
![image](https://user-images.githubusercontent.com/11984043/233560993-5dd9a4dd-f518-443b-a8b4-591c11c740ee.png)

**Comment by Sachin-chaurasiya** [comment]
Closing this issue as the problem mentioned in this issue is not an actual problem.

https://user-images.githubusercontent.com/59080942/233836799-86c5cf6a-46e8-4ad3-ab6e-4a9996b03ed5.mov
