### ISSUE TITLE
[Code update] Add React play api url in process.env variable

### ISSUE THREAD

**Issue by Angra974** [reactplay/react-play#1133]
When you want to change the API server to work on a different one than  https://api.github.com/repos/reactplay
we need to make changes in the FW code and modify 4 files.

In some configurations ( with Vitejs at least ), if you call https://api.github.com/repos/reactplay/something-here ( or anything like this on another API), you will get an error but the fetch function will try to get a valid response and fetch again. It's good to have your own local server to make the API call on it and don't spoil the react play API. We can get banned for some time ( experienced it ) and can't fetch the API again even if the correction is done.

Solution: 
Create an environment variable 
REACT_APP_PLAY_API_URL=https://api.github.com/repos/reactplay

and update the code in the 4 places where it is used.

After this, we just need to change the env variable to change the server URL without changing the main application code.
If reactplay needs to change the API's URL later, no need to modify the code too.

**Comment by villAsh** [comment]
can you assign me this issue?I would like to solve this
