### ISSUE TITLE
✨ [Feature request]: Automate the process to check and fix lint issues

### ISSUE THREAD

**Issue by supminn** [reactplay/react-play#1138]
### Is your feature request related to a problem? Please describe.

Whenever any new changes are made to the ReactPlay repository, we need to manually run the `yarn lint` to check for any lint errors and fix them accordingly. Failing to ensure this would cause failure in the overall project build. 

### Describe the solution you'd like.

We need to implement a pre-commit logic that would test for lint issues when a user is adding a new commit to this repository.

### Describe alternatives you've considered.

One possible solution could be using `husky`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Harsh-Daga** [comment]
Heyy,
Can I work on this issue?

**Comment by Sachin-chaurasiya** [comment]
> Heyy, If no one is working on this currently, can I work on this ?

Hello @Harsh-Daga , thanks for showing interest, I'm assigning this issue to you.

**Comment by shyamtawli** [comment]
Can I work on it.

**Comment by atapas** [comment]
@supminn what about the existing PR?

**Comment by supminn** [comment]
> @supminn what about the existing PR?

The PR is ready for merge. However, I was not sure on how to test it.

**Comment by shyamtawli** [comment]
> > @supminn what about the existing PR?
> 
> The PR is ready for merge. However, I was not sure on how to test it.

It can be tested at the time of commit I guess?
