### ISSUE TITLE
[Add a Play]: Two Play Rock Paper Scissors

### ISSUE THREAD

**Issue by Mrigakshi-RC** [reactplay/react-play#1139]
### What's the Play about?

This play is a typical dual-player rock paper scissor game.

### What ReactJS concept will be used to create this play?

Components and Hooks

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?
