### ISSUE TITLE
  ✨ [Feature request]: Adding of Dark-Light toggle button in the navbar

### ISSUE THREAD

**Issue by Bharadwajshivam28** [reactplay/react-play#1142]
### Is your feature request related to a problem? Please describe.

Adding of Feature in the NavBar

### Describe the solution you'd like.

We can Create a Dark-Light toggle button in the Navbar..  One can view it in dark and light mode both..

### Describe alternatives you've considered.

There is no alternative of this idea

### Screenshot / Screenshare

![Screenshot from 2023-04-29 23-02-31](https://user-images.githubusercontent.com/108119109/235316232-49258799-e6ab-45bc-83ae-f10cd0627632.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
Hello @Bharadwajshivam28 , Thanks for opening the feature request, can you provide the meaningful title for the same?

**Comment by Bharadwajshivam28** [comment]
@Sachin-chaurasiya not got your point

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya not got your point

No worries, I was talking about this title.
<img width="945" alt="image" src="https://user-images.githubusercontent.com/59080942/235320119-4c5bb277-8166-4118-be7d-6aa90015919d.png">

**Comment by Bharadwajshivam28** [comment]
@Sachin-chaurasiya Adding of Dark-Light toggle button in the navbar

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Adding of Dark-Light toggle button in the navbar

@Bharadwajshivam28 , Can you add the same in title?

**Comment by Bharadwajshivam28** [comment]
ya sure  @Sachin-chaurasiya

**Comment by Bharadwajshivam28** [comment]
@Sachin-chaurasiya updated it sir

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya updated it sir

@Bharadwajshivam28 , it should be 

✨ [Feature request]: Adding of Dark-Light toggle button in the navbar

**Comment by Bharadwajshivam28** [comment]
okay sir @Sachin-chaurasiya

**Comment by Bharadwajshivam28** [comment]
done with it @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
@Bharadwajshivam28 , Can you describe more, how would be you adding support for dark and light mode?

**Comment by Bharadwajshivam28** [comment]
yes i want to work on this feature..

Basically sir my idea is to implement an icon which can toggle light and dark mode when one clicks on it.. Like in night light mode is not much good so one can switch to dark mode..

Dropping two Screenshots.. One is of when user is in dark mode and other is of light mode..

![Screenshot from 2023-04-30 01-04-48](https://user-images.githubusercontent.com/108119109/235321125-ede25705-149f-4168-ba03-722e9fe60966.png)
![Screenshot from 2023-04-30 01-04-51](https://user-images.githubusercontent.com/108119109/235321128-2246709a-3705-4ad3-8fd6-a76f661cfee0.png)

@Sachin-chaurasiya

**Comment by Bharadwajshivam28** [comment]
this is one button and it changes in dark and light mode // in light mode it goes with sun icon and in dark mode it goes with moon icon

**Comment by Sachin-chaurasiya** [comment]
@Bharadwajshivam28 , That is the UI part, I was talking about how we are gonna support the light and dark modes, basically, if you toggle the button from light to dark then how we are gonna handle the dark mode changes?

We need to have some logic and theme for both modes right?

**Comment by Bharadwajshivam28** [comment]
yes we will have logic and theme both @Sachin-chaurasiya

**Comment by Bharadwajshivam28** [comment]
i have did it many times so i can add it in very good way

**Comment by Sachin-chaurasiya** [comment]
> i have did it many times so i can add it in very good way
> 
> 
> 
> @Sachin-chaurasiya 

@Bharadwajshivam28 , it would be great if you mention the approach and consideration in the PR description.

**Comment by Bharadwajshivam28** [comment]
ya sure sir i will do it when i will create the pr @Sachin-chaurasiya

**Comment by Bharadwajshivam28** [comment]
@Sachin-chaurasiya I am facing issue in running the project locally can you help me with commands..

like which commands and after which

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya I am facing issue in running the project locally can you help me with commands..
> 
> 
> 
> like which commands and after which

Sure @Bharadwajshivam28 , you can refer this doc https://docs.reactplay.io//local-development

**Comment by Bharadwajshivam28** [comment]
thanks @Sachin-chaurasiya

**Comment by mud1tx** [comment]
@Bharadwajshivam28 I can work on this issue if you no one is working on it.

**Comment by Vishrut19** [comment]
Is anyone working on it?

**Comment by Vishrut19** [comment]
Please assign me this @atapas

**Comment by Vishrut19** [comment]
Can you please let me know what should be the color scheme of dark mode and light mode?

**Comment by Hype16** [comment]
is anyone working on it ?

**Comment by ayush-chandil** [comment]
Can  I work on this Feature?
