### ISSUE TITLE
✨ [Feature request]: Adding a Button from which user can switch to different languages

### ISSUE THREAD

**Issue by Bharadwajshivam28** [reactplay/react-play#1143]
### Is your feature request related to a problem? Please describe.

Adding of a New Feature in React-Play

### Describe the solution you'd like.

React-Play is Globally viewed. People from Different Countries View React-Play. It can be difficult for people  of different countries to read content on  the page as not all can understand English..

We can create a language switching button where one can switch to different languages for better readable ..

### Describe alternatives you've considered.

No alternative because it can be one of best feature..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aaryan376** [comment]
I would like to work on this issue.

**Comment by aaqib605** [comment]
This would be an interesting addition to the project. I would love to work on this issue.
