### ISSUE TITLE
🐛 [Bug report]: Create button leads to File not found

### ISSUE THREAD

**Issue by swapn652** [reactplay/react-play#1147]
### Descrcibe the bug?

On clicking the `Create` button, it leads to a file that does not exist.

![image](https://user-images.githubusercontent.com/70851202/235659752-9b5a7ec7-0e22-4af2-a617-00be72df99d1.png)
![image](https://user-images.githubusercontent.com/70851202/235659826-a62daae9-611b-4c69-a5ed-99519f69a1b2.png)

### Steps to reproduce the bug?

1. Click on 'Create` button on top right corner

### Expected behavior

It should show some file.

### Desktop (Please provide your system information)

- OS: Windows
- Browser: Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@swapn652 Will you take up to fix it?

**Comment by atapas** [comment]
Hold On! I see it going to docs.

**Comment by swapn652** [comment]
Yes @atapas assign me. This is the content that we have to include, right? https://docs.reactplay.io/how-to-guides/how-to-create-play/

Else, if it's a problem with link I will check it out.

**Comment by swapn652** [comment]
I think this issue is related to the browser. I checked it out on Chrome and it's working fine, but it's causing problems on Edge. I posted another issue that's occuring on Edge but not on Chrome. @atapas

**Comment by swapn652** [comment]
It was an issue related to the cache. My bad, should've checked it twice.
