### ISSUE TITLE
✨ [Feature request]: Randomize play cards

### ISSUE THREAD

**Issue by shobhitexe** [reactplay/react-play#1159]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/reactplay/react-play/assets/29349136/8a72413f-a433-4d18-aacb-c2d3260af7ba)

As we can see on this image or in video attached below the cards always come on same sequence 
and the cards at bottom seems to get less opportunity 

### Describe the solution you'd like.

We can randomize the sequence of cards so on every render or view it will show random sequence 
making every card to get same opportunity

### Describe alternatives you've considered.

.

### Screenshot / Screenshare

Heres the attached video

https://github.com/reactplay/react-play/assets/29349136/fc81b0c5-a86e-4620-98fa-c6cd313ac055

### Additional context

You can assign this to me i would be very happy to take this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@shobhitexe 

Thanks for putting this issue.

Currently, the plays are arranged in the date-time sorted order. The recent play comes in the front. I think randomizing them alone will not be a good idea. I think we should provide some sorting mechanism instead.. like:

Sort by: 
- Newest
- Oldest
- Most Liked
- Random

Based on user selection, we can store than in local storage(as a preference) and always show the plays in that order. What do you think of this suggestion?

@Sachin-chaurasiya, you can provide your input too.

**Comment by Sachin-chaurasiya** [comment]
> @shobhitexe
> 
> Thanks for putting this issue.
> 
> Currently, the plays are arranged in the date-time sorted order. The recent play comes in the front. I think randomizing them alone will not be a good idea. I think we should provide some sorting mechanism instead.. like:
> 
> Sort by:
> 
> * Newest
> * Oldest
> * Most Liked
> * Random
> 
> Based on user selection, we can store them in local storage(as a preference) and always show the plays in that order. What do you think of this suggestion?
> 
> @Sachin-chaurasiya, you can provide your input too.

Sounds good, for logged-in users we can store this in preference instead of local storage.

**Comment by shobhitexe** [comment]
I'm glad to hear that! I'll be getting started on it soon.

**Comment by shobhitexe** [comment]
Hey I'm currently facing difficulties while setting up a project, as shown in the screenshot. I have already installed the dependencies using 'npm install --legacy-peer-deps,' but I am encountering an error. I'm wondering if there are any additional setup steps or if you have any tips to resolve this issue

![image](https://github.com/reactplay/react-play/assets/29349136/a7a46848-d43d-41fd-9f0e-f056178debfb)

**Comment by atapas** [comment]
> Hey I'm currently facing difficulties while setting up a project, as shown in the screenshot. I have already installed the dependencies using 'npm install --legacy-peer-deps,' but I am encountering an error. I'm wondering if there are any additional setup steps or if you have any tips to resolve this issue
> 
> 
> 
> ![image](https://github.com/reactplay/react-play/assets/29349136/a7a46848-d43d-41fd-9f0e-f056178debfb)
> 
> 

Can you please try yarn ?

**Comment by shobhitexe** [comment]
> > Hey I'm currently facing difficulties while setting up a project, as shown in the screenshot. I have already installed the dependencies using 'npm install --legacy-peer-deps,' but I am encountering an error. I'm wondering if there are any additional setup steps or if you have any tips to resolve this issue
> > ![image](https://user-images.githubusercontent.com/29349136/248451613-a7a46848-d43d-41fd-9f0e-f056178debfb.png)
> 
> Can you please try yarn ?


![image](https://github.com/reactplay/react-play/assets/29349136/e4960395-73f9-4a6f-84e8-c9de2efec295)
Same with yarn

**Comment by shobhitexe** [comment]
![image](https://github.com/reactplay/react-play/assets/29349136/512c086d-abe3-44e1-b5df-f6adfadde81c)

**Comment by atapas** [comment]
@shobhitexe with yarn it worked?

**Comment by shobhitexe** [comment]
> @shobhitexe with yarn it worked?

Same with yarn not working 
i tried re forking repo also any other tips or suggestions from your side

**Comment by Angra974** [comment]
> > @shobhitexe with yarn it worked?
> 
> Same with yarn not working i tried re forking repo also any other tips or suggestions from your side

Manually change your react-icons package to 4.8.0 and install again. Be sure to have this version.

**Comment by shobhitexe** [comment]
> > > @shobhitexe with yarn it worked?
> > 
> > 
> > Same with yarn not working i tried re forking repo also any other tips or suggestions from your side
> 
> Manually change your react-icons package to 4.8.0 and install again. Be sure to have this version.

Thanks ill try 🤝

**Comment by satishchakma** [comment]
Hi @shobhitexe  Is the problem resolved? It happened to me also. I tried 

`npm i --force`

and it worked for me.  Thank you.

**Comment by shobhitexe** [comment]
> Hi @shobhitexe Is the problem resolved? It happened to me also. I tried
> 
> `npm i --force`
> 
> and it worked for me. Thank you.

i tried this that time not working ill try again
