### ISSUE TITLE
🐛 [Bug report]: The page refresh give 404 on sub routes

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#1160]
### Descrcibe the bug?

When you refresh the page on ReactPlay subroutes, it gives page not found error.

### Steps to reproduce the bug?

1. Go to [Play Page](https://reactplay.io/plays)
2. Now Refresh the page
3. You should see a 404

<img width="269" alt="image" src="https://github.com/reactplay/react-play/assets/3633137/5a5430fc-1673-415f-93c4-d5634e62632b">

Please note: This is reproducible on:

- Any sub routes like ideas, leaderboard, etc
- Always on Incognito mode
- On non-incognito, please clear the application data and reproduce it. You can clear the app data from here
<img width="717" alt="image" src="https://github.com/reactplay/react-play/assets/3633137/f31a4961-e567-46e3-9203-8e2ae9385f63">

### Expected behavior

The Refresh should get us the correct page we are on.

### Desktop (Please provide your system information)

All

### Mobile (Please provide your device information)

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jatingodnani** [comment]
I will try
