### ISSUE TITLE
[Add a Play]: Share Threads

### ISSUE THREAD

**Issue by rmrokon** [reactplay/react-play#1164]
### What's the Play about?

This is a Twitter-like application. Users can create, edit, delete, and get threads.

### What ReactJS concept will be used to create this play?

Components, Hooks, React Router, React Query, etc.

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?

**Comment by rmrokon** [comment]
Thank you for closing the issue. There were some issues at my end and I couldn't work on it. I apologize for not keeping you posted.
