### ISSUE TITLE
[Add a Play]: CryptoApp

### ISSUE THREAD

**Issue by Akshat2Jain** [reactplay/react-play#1167]
### What's the Play about?

It is a Cryptocurrency Tracker app that shows Trending coins with their current market value.

### What ReactJS concept will be used to create this play?

Hooks, Context Api, Props, Axios, async/await

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alaminrifat** [comment]
@Akshat2Jain  are you still working on this?

**Comment by Akshat2Jain** [comment]
Naah! Busy doing some other work. You can take this btw

**Comment by alaminrifat** [comment]
okk.. thanks

**Comment by priyankarpal** [comment]
@alaminrifat you can work on this
