### ISSUE TITLE
✨ [Feature request]:  Community Carousel

### ISSUE THREAD

**Issue by nayan-dey** [reactplay/react-play#1170]
### Is your feature request related to a problem? Please describe.

In the "What's our community says" section it takes too much space and also the tweets are not properly aligned.

### Describe the solution you'd like.

I want to make a twitter Carousel on this section which can show 3 to 4 tweet at a time and it will scrollable which will take a little space at the main page.If it sounds good let me know. I will work on it.

### Describe alternatives you've considered.

I dont have any alternative idea.I think this should work absolutely fine.
Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhishek-90** [comment]
I would like to take it up. Please assign it to me.

**Comment by priyankarpal** [comment]
I think there are no issues with this section @nayan-dey 
![image](https://github.com/reactplay/react-play/assets/88102392/6217a57b-bb0a-49a8-8f20-1d6f78e1dd0f)
