### ISSUE TITLE
[Add a Play]: Image Gallery via Unsplash API

### ISSUE THREAD

**Issue by gorostiaga** [reactplay/react-play#1179]
### What's the Play about?

It is a image gallery that loads up images from Unsplash API

### What ReactJS concept will be used to create this play?

Components and hooks

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vishrut19** [comment]
Do we need to create a new play for this ?
