### ISSUE TITLE
✨ [Feature request]: Add StyledComponents as a dropdown option for Styling when Creating a New Play

### ISSUE THREAD

**Issue by JustCodeDaily** [reactplay/react-play#1187]
### Is your feature request related to a problem? Please describe.

No, It is not a problem that lets me frustrated

### Describe the solution you'd like.

I would like to add a new item in the dropdown menu which asks Styles, I would like to add Styled Components along with CSS and SCSS

### Describe alternatives you've considered.

We have been using CSS and SCSS widely, but I could see there is a large number of applications use Styled Components where one can Reuse, Extend components and maintain cleaner code. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@JustCodeDaily Please update the title of the issue.

**Comment by JustCodeDaily** [comment]
@atapas I have updated the title of the Issue :-)

**Comment by atapas** [comment]
> @atapas I have updated the title of the Issue :-)

Do you want to work on it?

**Comment by JustCodeDaily** [comment]
Yes, I would love to :-) @atapas
