### ISSUE TITLE
[Add a Play]: Guess the Magic Number 

### ISSUE THREAD

**Issue by JustCodeDaily** [reactplay/react-play#1191]
### What's the Play about?

This play is about Guessing a Magic Number which is >= 10 and <= 99 within 5 chances. 

- When the game is initialized a random number will be generated with the above condition
- User should create a keypad with numbers 0 to 9 and two icons X and ✓
- X should make them delete their guesses and ✓ to submit
- A welcome message before the game start and the message keeps changing depending upon their guesses (Nice Try, Give one more shot, Aaah, you aint lucky etc)
- A Check Box with "Cheat Mode" as a label as a helper tool - When enabled it should let the user know if their guess is close to the number generated (when the guessed number is lesser or greater than 5)

I have a very basic not so looking good semi functional instance here at 
[Instance URL](https://magic-number-8w8499s4o-justcodedaily.vercel.app/)

### What ReactJS concept will be used to create this play?

Components, Styled Components, React Hooks

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shiblijamal10** [comment]
In 2nd point of description can we add the input field in terms of the keypad for putting the user input?

**Comment by dirtyKitchen** [comment]
@shiblijamal10

Hello. Do you mean you need a text input instead of a button?

**Comment by JustCodeDaily** [comment]
I have also written a detailed blog on it [here](https://jcd.hashnode.dev/react-magic-number), Made few tweaks as well. Feel free to comment

**Comment by atapas** [comment]
@JustCodeDaily get started.

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?
