### ISSUE TITLE
✨ [Feature request]: UI Enhancement for of src/common/PlayCreated.jsx - Add Copy Button 

### ISSUE THREAD

**Issue by JustCodeDaily** [reactplay/react-play#1192]
### Is your feature request related to a problem? Please describe.

No it is not related to a problem. I would like to have a small copy button, so it is easy to copy and paste in the terminal 

### Describe the solution you'd like.

Add a copy icon something like this
![image](https://github.com/reactplay/react-play/assets/135980486/7dd52cfe-1852-43b0-a187-381419b19663)

### Describe alternatives you've considered.

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JustCodeDaily** [comment]
I can take this up. It should be a simpler one - by adding a SVG and enable copy function

**Comment by atapas** [comment]
What is PlayCard? Can you add some screenshot so that we understand it fully?

**Comment by atapas** [comment]
Hi @JustCodeDaily Any update to my question?

**Comment by JustCodeDaily** [comment]
Hey Reactplay/React-Play,

Apologies for the delay. I'm currently vacating and should be back home
tonight. I'll get the design along with a sample snippet by tomorrow EOD
(CET)

**Comment by JustCodeDaily** [comment]
![image](https://github.com/reactplay/react-play/assets/135980486/23e760fa-410e-43bf-9ce1-327d958fa914)
I would like to have something like this. 

- Improvising the page a bit
- Add Admonition for Info 
- Add Copy button at the top right end and enable to copy the command so can be easliy pasted in terminal

**Comment by MahirMahdi** [comment]
If no one's working on it, I would like to.

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
