### ISSUE TITLE
✨ [Feature request]: Migrate from CRA to Vite

### ISSUE THREAD

**Issue by ammaaraslam** [reactplay/react-play#1193]
### Is your feature request related to a problem? Please describe.

ReactPlay currently uses CRA as its build tool, which is now considered to be far back from other available tools in terms of performance and its limitations.

### Describe the solution you'd like.

To tackle this, migrating the project from using CRA to Vite would address these problems and improve the overall development experience. Vite is much faster, more efficient and provides more tools to improve developer experience.

### Describe alternatives you've considered.

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhijain1705** [comment]
can I work on this?

**Comment by ammaaraslam** [comment]
> can I work on this?

Hey @abhijain1705
Thanks for the interest in it, but we're almost done with the issue.
Please have a look at other open issues.
Thanks 🙏

**Comment by abhijain1705** [comment]
no worries

**Comment by tejaskh3** [comment]
Talked to @atapas and picking this up!

**Comment by atapas** [comment]
> > Talked to [@atapas](https://github.com/atapas) and picking this up!
> 
> ok, what if we can migrate to nextjs?

Let's move to vite first
