### ISSUE TITLE
[Add a Play]: Chess Game

### ISSUE THREAD

**Issue by kunalshokeen051** [reactplay/react-play#1197]
### What's the Play about?

A chess game played by user and the computer build using react, Chessboard.jsx (wrapper for chessboard.js) and chess.js.
It a classic game and comes under Advance Plays.

### What ReactJS concept will be used to create this play?

useState, UseEffect, UseMemo, Axios

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@kunalshokeen051 plz edit the title

**Comment by atapas** [comment]
> @atapas  I am new to opensource Can you suggest a title

Any title about play works
