### ISSUE TITLE
✨ [Feature request]: Dynamic Trending Plays Section

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1198]
### Is your feature request related to a problem? Please describe.

The `Trending Plays` section is static and is not updated according to the play's engagement.

### Describe the solution you'd like.

We can make the `Trending Plays` section dynamic where the `plays` will be updated automatically when they get more likes. 

### Describe alternatives you've considered.

Currently, we have only a likes option from where we can compare all the `plays` and according to the `play's likes`, we will show the play on this trending list.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/91705825/ba63e533-d0e6-4a5b-a50d-282a5a0d9594)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@Shivam-Katare What are the logic are you thinking of?

**Comment by Shivam-Katare** [comment]
- Currently, we can only compare plays with `likes`.Hence, we can showcase the `most-liked plays` in the Trending Plays Section. 

- The display of plays will dynamically adjust based on their popularity, with the play gaining the highest number of likes occupying the top position, followed by the remaining three `plays`.

So, we will display the 4 most loved plays in the trending sections. Any thoughts @atapas?

**Comment by Shivam-Katare** [comment]
> > * Currently, we can only compare plays with `likes`.Hence, we can showcase the `most-liked plays` in the Trending Plays Section.
> > * The display of plays will dynamically adjust based on their popularity, with the play gaining the highest number of likes occupying the top position, followed by the remaining three `plays`.
> > 
> > So, we will display the 4 most loved plays in the trending sections. Any thoughts @atapas?
> 
> certainly a good way to start.

Okay then, I'll start working on it

**Comment by Shivam-Katare** [comment]
Hey @atapas, Do I reopen the PR for this issue as it is stale for not having it reviewed?

**Comment by priyankarpal** [comment]
> Hey @atapas, Do I reopen the PR for this issue as it is stale for not having it reviewed?

you can submit the final PR

**Comment by Shivam-Katare** [comment]
> > Hey @atapas, Do I reopen the PR for this issue as it is stale for not having it reviewed?
> 
> you can submit the final PR

Okay.
