### ISSUE TITLE
✨ [Feature request]: Add Popup/ Modal with pure css

### ISSUE THREAD

**Issue by lifeofsoumya** [reactplay/react-play#1202]
### Is your feature request related to a problem? Please describe.

We can add a Modal or a popup that can put any component inside a modal

### Describe the solution you'd like.

Using only Vanilla CSS we can create the Modal styling and add the functionality just by triggering its visibility with the true and false state.

### Describe alternatives you've considered.

There are a lot of packages that can implement the same Modal but are heavy in size.

### Screenshot / Screenshare

![image](https://github.com/lifeofsoumya/react-play/blob/main/src/plays/popup-component/images/popup.png?raw=true)
![image](https://media.discordapp.net/attachments/989492105372127232/1111221606098931732/image.png?width=1440&height=646)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kunalshokeen051** [comment]
Using react-bootstrap is also a good option and it also dont utilize much resouces.

**Comment by Sam10-debug** [comment]
Id like to work on this , please assign it to me

**Comment by lifeofsoumya** [comment]
> Using react-bootstrap is also a good option and it also dont utilize much resouces.

I've implemented it with vanilla.

**Comment by Shahidkhatrii** [comment]
I would like to work on this issue
