### ISSUE TITLE
✨ [Feature request]: Improve UX with Custom Scrollbar on Website

### ISSUE THREAD

**Issue by Saurav-Pant** [reactplay/react-play#1203]
### Is your feature request related to a problem? Please describe.

The website currently uses the default scrollbar, which can be enhanced for a better user experience. 

### Describe the solution you'd like.

Requesting the implementation of a custom scrollbar in a visually appealing color to elevate the website's aesthetics. 
According to my preference, the color #00f2fe would suit well with the website's design. 

### Describe alternatives you've considered.

Changing the scrollbar color and size is the only alternative I have discovered

### Screenshot / Screenshare

![need to change this](https://github.com/reactplay/react-play/assets/103263909/ba6c02d0-e8b4-467f-aa2c-5fcbb0648057)

### Additional context

please assign it to me, I want to work on it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrTea7171** [comment]
I think this issue does not exist anymore. @atapas

**Comment by Programming-School-Pro-Coding** [comment]
Hello, I can work on this issue please assign it to me.

**Comment by HarshDubey1011** [comment]
please assign it to me, I want to work on it

**Comment by priyankarpal** [comment]
we can improve the scrollbar. do you want to work on this issue? @Saurav-Pant

**Comment by Saurav-Pant** [comment]
Yes, I want to work on it, @priyankarpal

**Comment by priyankarpal** [comment]
hello @Saurav-Pant can you update me on the progress of this particular issue?

**Comment by Saurav-Pant** [comment]
@priyankarpal, I have done this, but In committing the changes I am getting errors,

**Comment by letscodedanish** [comment]
@priyankarpal  I created a PR. have a check on it.

**Comment by priyankarpal** [comment]
> @priyankarpal, I have done this, but In committing the changes I am getting errors,

still, showing errors?

**Comment by Saurav-Pant** [comment]
> > @priyankarpal, I have done this, but In committing the changes I am getting errors,
> 
> still, showing errors?

Yes @priyankarpal, I'm still encountering errors. I've noticed that other individuals are commenting on or creating pull requests for this issue, so you can go ahead and unassign me or assign it to someone else

**Comment by ashllxyy** [comment]
Hi! Could you assign this to me? I want to work on this

**Comment by priyankarpal** [comment]
> Hi! Could you assign this to me? I want to work on this

it's already assigned to someone
