### ISSUE TITLE
Numbers of plays realised are not the same in leadearboad🐛 [Bug report]: 

### ISSUE THREAD

**Issue by Angra974** [reactplay/react-play#1211]
### Descrcibe the bug?

When you go to reactplay.io ( same in localhost ),
the count of plays created by the top creator of the month and the count displayed in the top creator list are not the same.

### Steps to reproduce the bug?

Go on reactplay.io/leaderboard to see the difference between the 2 numbers

### Expected behavior

Same count for the 2 informations

### Desktop (Please provide your system information)

Used vivaldi on windows 11.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/48807534/1ee42283-9f6f-469b-986d-18a8cbdf588f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Villain45** [comment]
I think the rhs list is of all time, and is lhs only of the ongoing month...

**Comment by Angra974** [comment]
> You want me to make the changes and do a PR?

Let @atapas tell us if it needs a change; Perhaps i'm the only one that are confuse by this or you can assign yourself to the task if you think others people might get confused too and do the PR.

**Comment by ambetack** [comment]
can you allow me to resolve this issue and do the PR for this this bug

**Comment by atapas** [comment]
> can you allow me to resolve this issue and do the PR for this this bug

Do you want to work on it?

**Comment by mashriram** [comment]
@atapas - Can i take up this issue and submit a PR
