### ISSUE TITLE
Using react-play with others builders show some problems that can be corrected to be ready to switch from CRA

### ISSUE THREAD

**Issue by Angra974** [reactplay/react-play#1212]
Others builders analysis can help to find problems in the current code, even if they are not blocking the application. 
These analisys can help to improve the actual code.

![image](https://github.com/reactplay/react-play/assets/48807534/a1cbe881-e535-4b21-b1a4-5d0a498e840f)

![image](https://github.com/reactplay/react-play/assets/48807534/8fc21d83-9c3c-4755-ad5e-c3ef93c1ac79)

![image](https://github.com/reactplay/react-play/assets/48807534/a83d39e9-4005-46e5-b1e2-e0f8714206df)

![image](https://github.com/reactplay/react-play/assets/48807534/edf2d7ee-1a0e-47f4-8411-82c58225c2bc)

![image](https://github.com/reactplay/react-play/assets/48807534/bb5d5896-473b-4eee-95d8-1cefa2f4b944)
![1](https://github.com/reactplay/react-play/assets/48807534/9e702a6c-bb01-4878-b8a1-bd912b0d0dfc)

error while building with react-scripts:
![image](https://github.com/reactplay/react-play/assets/48807534/efd97b47-c515-4467-bd0c-9527cc5e36ee)

Will happen only if using vite instead of CRA but will happen too with webpack outside CRA, in fact, you can find it installed with cra but not assessible to others builders.
![image](https://github.com/reactplay/react-play/assets/48807534/296c4c6f-16f4-42c0-9128-ac3393943c68)

**Comment by kunalshokeen051** [comment]
There are few errors like updating the saas dependency to Node-saas as the former one is depreciated and also material-styles is making some problems.
