### ISSUE TITLE
Error occurs when trying to add a Testimony in ReactPlay.io 🐛 [Bug report]: 

### ISSUE THREAD

**Issue by bahnisikhadhar** [reactplay/react-play#1214]
### Descrcibe the bug?

In the ReactPlay.io website when trying to add a testimony, it is not being added and shows an error pop up.

### Steps to reproduce the bug?

1) Go to the ReactPlay.io website's testimony section
2) Write testimony and Click on Add button 
3) The error pop-up shows

### Expected behavior

After writing a testimony and selecting the Category, when Clicking on add button, it should have been submitted

### Desktop (Please provide your system information)

OS : Windows 11 (Version 22H2)
Browser : Chrome (Version 114.0.5735.199)

### Screenshot / Screenshare

![Screenshot (312)](https://github.com/reactplay/react-play/assets/114249673/a8457586-99b8-4c37-8a8b-299a7fced975)

### Relevant log output

```shell
[
  {
    "extensions": {
      "code": "validation-failed",
      "path": "$.query"
    },
    "message": "not a valid graphql query"
  }
]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhishek-90** [comment]
I would like to take it up.

**Comment by satishchakma** [comment]
hi @bahnisikhadhar I have tried it today. Saw no error. Did you try again recently?
