### ISSUE TITLE
🐛 [Bug report]: When activities on, the mobile view is missing the "Events" text

### ISSUE THREAD

**Issue by satishchakma** [reactplay/react-play#1227]
### Descrcibe the bug?

When activity is on, the reactplay web site misses the"Events" text on the mobile. 

Expected the"Event" button should be available to see. The link is working and the icon is there but the text is missing or white color. Possibly

### Steps to reproduce the bug?

1. Launch reactplay.io on mobile view
2. Open the burger button/menu on mobile
3. Look out for the Events button on top

### Expected behavior

We should see the Button name/ the text "Events"

### Desktop (Please provide your system information)

Devices: Mac Os- ventura 13,
Browsers:  Chrome, Safari, 

### Mobile (Please provide your device information)

 iPhone 11,
 Browsers:  Chrome, Safari, 

### Screenshot / Screenshare

<img width="605" alt="reactplay bug" src="https://github.com/reactplay/react-play/assets/77580640/51baa458-c8b5-4cb0-af71-4d2d0eb3ac43">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satishchakma** [comment]
@atapas  @dear_project_managers, I already fixed this issue. Would you please assign me? Thank you.

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?
