### ISSUE TITLE
✨ [Feature request]:  Set the PORT number dynamically on local server.

### ISSUE THREAD

**Issue by Hat52** [reactplay/react-play#1243]
### Is your feature request related to a problem? Please describe.

When we try to create a new play on localhost and If we already have something running on port 3000 then the project successfully runs on a different port but when we hit the create play button it redirects to port 3000 which is not the intended port for the project.

### Describe the solution you'd like.

The current solution wants us to set the port number in a .env file If we do that it will successfully open the new play form on that port but what I am suggesting is that we exclude the need to set an env variable for this specific purpose.

### Describe alternatives you've considered.

none

### Screenshot / Screenshare

inside CreatePaly file 
![image](https://github.com/reactplay/react-play/assets/44437268/60c913eb-712b-479b-9a5c-4649332c4382)
This is the code that needs to be updated/

### Additional context

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hat52** [comment]
If this needs to be worked on then I would like to work on it.

**Comment by Hat52** [comment]
The attached screenshot has the port number 3001, I have changed that on local from 3000 to 3001

**Comment by atapas** [comment]
Please work on it.

**Comment by Angra974** [comment]
Be careful with this. You can start your app on port 3000. But process.env is not found, so you can't found process.env.RAECT_DEV_PORT.
And this variable is not set in .env file, so it's logic it will not be found. 
By default CRA starts on port 3000 even if you change this variable
You can add the port in the start script but will need to be done in the main app.
Best solution for you is to use command line with a tool like "kill-port"
Here how i use the application on local "npx kill-port 3000 && pnpm start" or other package manager.

**Comment by Hat52** [comment]
Thanks for heads up
