### ISSUE TITLE
✨ [Feature request]:  Add "Are you willing to take it up for implementation?" in all issue templates

### ISSUE THREAD

**Issue by Hat52** [reactplay/react-play#1246]
### Is your feature request related to a problem? Please describe.

Currently, when we create a new Issue, only the new play template has the option Are you willing to take it up for implementation? instead it should be on all the templates,

### Describe the solution you'd like.

We should add this option in all the templates.

### Describe alternatives you've considered.

no

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/44437268/f88143a6-9066-4e80-adda-3be847e42547)

### Additional context

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hat52** [comment]
Please add a description of how you want this issue to be handled and what the end result should be.

**Comment by priyankarpal** [comment]
also, we can add these checkboxes. What do you think? @Hat52  

![image](https://github.com/reactplay/react-play/assets/88102392/85b46fe1-3c3b-412a-b3b0-3c34b4f93908)

**Comment by Hat52** [comment]
Yes, we can do that, I think these need to be added to all the templates right?

**Comment by priyankarpal** [comment]
yeah! we have to add to all templates.

**Comment by priyankarpal** [comment]
@atapas please close this issue. merged https://github.com/reactplay/react-play/pull/1248
