### ISSUE TITLE
✨ [Feature request]: auto author assign for PRs

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1252]
### Is your feature request related to a problem? Please describe.

After creating a PR maintainers are assigning to the PR to the author. To automate this process we can add a GitHub Action

### Describe the solution you'd like.

The GitHub Action will automatically assign to the author who has created the PR.

### Describe alternatives you've considered.

n/a

### Screenshot / Screenshare

# Demo
![image](https://github.com/reactplay/react-play/assets/88102392/d2f96cec-5a8e-4b55-b437-2b10dc13cb1d)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhishek-90** [comment]
I would like to work on this issue. I came across one such feature where in order to assign an issue, all the contributor needs to do is comment `/assign` and github actions will take care of it.

**Comment by priyankarpal** [comment]
> I would like to work on this issue. I came across one such feature where in order to assign an issue, all the contributor needs to do is comment `/assign` and github actions will take care of it.

this is not for issue. it's for PRs if someone opens a PR gh action bot will assign the person to the PR

**Comment by Abhishek-90** [comment]
Alright, I got it. Can you assign this to me? 

Maybe we can also add an action as I mentioned to auto assign the issues as well.
