### ISSUE TITLE
✨ [Feature request]: Update Twitter icon to X

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1255]
### Is your feature request related to a problem? Please describe.

The problem we're facing is the presence of an outdated `Twitter icon` on the site, which needs to be updated to reflect the latest changes.

### Describe the solution you'd like.

We would like to replace the existing `Twitter icon `with the `X` icon.

### Describe alternatives you've considered.

As an alternative to using `Twitter's `SVG icon, we should switch to the `X icon's` SVG representation.

### Screenshot / Screenshare

![console log(data)](https://github.com/reactplay/react-play/assets/91705825/f552c584-f53d-4fe4-9d4e-fa10f1a23589)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrAJAY1** [comment]
I'm interested in working on this issue. I believe I can help update the Twitter icon to the X icon. Please assign this issue to me, and I will get started on it.

**Comment by priyankarpal** [comment]
Hello @mrAJAY1, please wait for maintainers to assign before making a PR. @Shivam-Katare opened this issue and wants to work on it.
![image](https://github.com/reactplay/react-play/assets/88102392/1731c137-f787-44a4-8f48-be13d0e7b3e3)

**Comment by mrAJAY1** [comment]
Ah, I may have momentarily forgotten my 'Wait for the Maintain-Assign Dance.' 🕺 My bad, @Shivam-Katare! You've got the floor – I'll just be here, practicing my patience and plotting my next ninja move. 🤣🥷

**Comment by Shivam-Katare** [comment]
Sure @mrAJAY1 no problem 👍. @priyankarpal do I start working on this issue?

**Comment by priyankarpal** [comment]
> Sure @mrAJAY1 no problem 👍. @priyankarpal do I start working on this issue?

yup! you can

**Comment by priyankarpal** [comment]
any updates? @Shivam-Katare

**Comment by Shivam-Katare** [comment]
Yes @priyankarpal, I will push the changes almost by the end of tomorrow
