### ISSUE TITLE
[Add a Play]: Color Guessing Game

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#1257]
### What's the Play about?

Build a Color Guess Game that you can give the user a color and he will choose from 6 squares + there are two levels Hard and Easy, Easy has 3 squares and hard has 6 squares.

### What ReactJS concept will be used to create this play?

I will use React States, Framer Motion and Styled-Components

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
you can work on this issue @Programming-School-Pro-Coding

**Comment by Programming-School-Pro-Coding** [comment]
Hello, Can I install framer motion ?

**Comment by Programming-School-Pro-Coding** [comment]
And I want join hacktoberfest

**Comment by Programming-School-Pro-Coding** [comment]
> Hello, Can I install framer motion ?

@priyankarpal

**Comment by priyankarpal** [comment]
framer motion is little bit heavy try to use alternative
