### ISSUE TITLE
🐛 [Bug report]: when fork the project and run `npm install` it gives me error

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#1258]
### Descrcibe the bug?

I see that it gives me the following error when run `npm install`:
![image](https://github.com/reactplay/react-play/assets/96921717/0bd741d7-6d42-4fab-b811-5317ef3fa146)
 

### Steps to reproduce the bug?

So We can update the Command in README File and Change the command to be `npm install --legacy-peer-deps` to help new contributors to install all packages without any error

### Expected behavior

.

### Desktop (Please provide your system information)

OS: Windows
Browser: [chrome, firefox]

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/96921717/0bd741d7-6d42-4fab-b811-5317ef3fa146)
 

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Programming-School-Pro-Coding** [comment]
I can work on this issue

Please Assign me

**Comment by priyankarpal** [comment]
> I can work on this issue
> 
> Please Assign me

I will suggest to use `pnpm` instead of `npm` or `yarn`.

**Comment by alaminrifat** [comment]
use this instead

`npm install --legacy-peer-deps`

**Comment by priyankarpal** [comment]
is it working? @Programming-School-Pro-Coding

**Comment by Angryman18** [comment]
`yarn` is recommended over `npm` in order to overcome this issue. you can follow along here https://docs.reactplay.io/local-development

**Comment by priyankarpal** [comment]
> `yarn` is recommended over `npm` in order to overcome this issue. you can follow along here https://docs.reactplay.io/local-development

also, we can use `pnpm` over `npm` & `yarn` what do you think @Angryman18?

**Comment by irfanmit** [comment]
it worked with _npm install --legacy-peer-deps_ thank you

**Comment by Programming-School-Pro-Coding** [comment]
> is it working? @Programming-School-Pro-Coding

Yes

**Comment by Programming-School-Pro-Coding** [comment]
> > `yarn` is recommended over `npm` in order to overcome this issue. you can follow along here https://docs.reactplay.io/local-development
> 
> also, we can use `pnpm` over `npm` & `yarn` what do you think @Angryman18?

I don't have pnpm in my device but i will install it
