### ISSUE TITLE
[Add a Play]: URL Shortner

### ISSUE THREAD

**Issue by alaminrifat** [reactplay/react-play#1259]
### What's the Play about?

✅ An URL shortener play using react

### What ReactJS concept will be used to create this play?

✅Components
✅Rest API
✅Axios
✅Custom Hook

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you
