### ISSUE TITLE
Dependencies conflicts after cloning

### ISSUE THREAD

**Issue by irfanmit** [reactplay/react-play#1263]
Hi, i am just starting my open source journey with this repo....i am glad.....#hackoctober........when i cloned the repo...after forking...in my pc....and run "npm install" i got missing packages issues....so when i run npm installl i get many conflicts....no matter what i to remove conflict....whehter i upgrade or downgarde some dependencies i still get conflicts....so i wanted to ask is there any professsional or some developer way to deal with conflicts....because many would get the same issue if i am getting...so how do they solve this?

**Comment by HarshDubey1011** [comment]
Hello, I also face the same issue. So after doing some seach I found a solution which works for me. I have added --legacy-peer-deps with npm install. for ex:- npm install --legacy-peer-deps. This will use the older NPM 6 style peer dependency resolution algorithm.

**Comment by priyankarpal** [comment]
you have to do `npm install --legacy-peer-deps`


similar to https://github.com/reactplay/react-play/issues/1258 so I'm closing this issue. if you're facing an issue related to this problem you can comment on #1258

**Comment by irfanmit** [comment]
The issue is solved development server started thank you
