### ISSUE TITLE
Prettier issue

### ISSUE THREAD

**Issue by irfanmit** [reactplay/react-play#1266]
Well i forked the project and created a new play....but after that i start my server...something like this error occurs...

- D:\REACT PROJECTS\Hackoctober_react-play\src\plays\faisal-play\Faisal-play.js
-   11:9   error  Insert `··`                                                                                                                                                                            
-                                                                                                       prettier/prettier
-   13:31  error  Delete `·`                                                                                                                                                                             
-                                                                                                       prettier/prettier
-   15:71  error  Replace `␍⏎··············Pellentesque·euismod,·urna·eu·tincidunt·consectetur,␍⏎··············nisi·nunc·ultricies·nisi,·eget·consectetur·nunc·nisi` with `·Pellentesque·euismod,·urna·eu␍⏎··············tincidunt·consectetur,·nisi·nunc·ultricies·nisi,·eget·consectetur·nunc·nisi·euismod`  prettier/prettier
-   18:14  error  Delete `·euismod`                                                                                                                                                                      
-                                                                                                       prettier/prettier
-   21:1   error  Insert `··`                                                                                                                                                                            
-                                                                                                       prettier/prettier
-   28:28  error  Insert `␍⏎`  

if code is correct (which was default and not written by me)....so why such error is there.....what is prettier thing.....how do i solve....is some package need to installed??

**Comment by priyankarpal** [comment]
could you share a screen recording it will help us to check the problem.

**Comment by irfanmit** [comment]
With _npm run format_ the issue is solved
