### ISSUE TITLE
[Add a Play]: Toast-Component

### ISSUE THREAD

**Issue by bhaveek424** [reactplay/react-play#1267]
### What's the Play about?

This Play is about creating a Toast Component, which is a pretty common component one can find in majority of UI component libraries, from scratch. This play will utilize context api, useMemo, useCallback and custom hooks. 

### What ReactJS concept will be used to create this play?

Components, Context API, Custom hooks, useEffect

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
