### ISSUE TITLE
🐛 [Bug report]: Search & Filter Issue 

### ISSUE THREAD

**Issue by sudipkundu999** [reactplay/react-play#1271]
## 1. Empty Search makes the page forever loading
If we press enter on the empty search field the page goes in forever loading as the GraphQL query breaks.

## 2. The filter popup doesn't close automatically when all filters are cleared and `Apply` is clicked.
- When the filter popup is emptied for all fields and `Apply` is clicked
- the operation is performed i.e filter is reset 
- but the popup is still open

## 1. Empty Search makes the page forever loading
- Go to https://reactplay.io/
- Click on `Browse`
- Click on the search field and hit `Enter`
- The page will load forever

## 2.  The filter popup doesn't close automatically when all filters are cleared and `Apply` is clicked.
- Go to https://reactplay.io/
- Click on `Browse`
- Click the filter icon. The filter popup will open.
- Type `Calculator by tea` in the `Text` field and select `Beginner` from the `Levels` field. Click `Apply`.
- You'll see only 1 play in the list.
- Now again open the filter popup and deselect `Beginner` from the `Levels` field & clear the `Text` field and hit `Apply`
- You'll be able to see in the background other plays are visible but the filter popup has not auto-closed.

## 1. Empty Search makes the page forever loading

Empty Search should not break the page and send it to forever loading

### 2. The filter popup doesn't close automatically when all filters are cleared and `Apply` is clicked.

The popup should auto-close when `Apply` is clicked after clearing all the fields.

### Desktop (Please provide your system information)

- OS: MacOS ventura 13.6
- Browser: Chrome 117

## 1. Empty Search makes the page forever loading
<img width="1440" alt="image" src="https://github.com/reactplay/react-play/assets/95222845/60d5f28e-2ce2-426e-9711-297d413df20b">

## 2. The filter popup doesn't close automatically when all filters are cleared and `Apply` is clicked.
<img width="1440" alt="image" src="https://github.com/reactplay/react-play/assets/95222845/4e3ea635-6e78-4d6d-9ad9-079b3e4a63ad">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudipkundu999** [comment]
Attaching a video for reference

https://github.com/reactplay/react-play/assets/95222845/40784fc8-257b-47a6-8cd4-9d7b2f69ecc8

**Comment by priyankarpal** [comment]
@sudipkundu999 are you into hacktoberfest?

**Comment by sudipkundu999** [comment]
@priyankarpal Yes I am
