### ISSUE TITLE
Unable to create new play

### ISSUE THREAD

**Issue by irfanmit** [reactplay/react-play#1273]
![IMG_20231002_165815675.jpg](https://github.com/reactplay/react-play/assets/97839373/769658ac-250e-4646-8b19-a6471f4e71fd)

I am not able to create new play..the following error pop up all the time(in the image)...do other facing same issue too? Or just me

**Comment by Programming-School-Pro-Coding** [comment]
Try to restart the server or Try to Sync your fork in your Account **[Your Repo](https://github.com/irfanmit/Hackoctober_react-play)**
