### ISSUE TITLE
[Add a Play]: tip calculator for bills

### ISSUE THREAD

**Issue by ayushsgithub** [reactplay/react-play#1277]
### What's the Play about?

A simple react app to calculate tip evenly where user can divide the total bill amount into sharing number of people and the tip, and distribute how much the bill is for per person

### What ReactJS concept will be used to create this play?

ReactJs concepts: useState, useEffect

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maha-sachin** [comment]
I want to work on this issue
