### ISSUE TITLE
✨ [Feature request]: Provide a link to the play from play idea page

### ISSUE THREAD

**Issue by HarshithaSolai** [reactplay/react-play#1282]
### Is your feature request related to a problem? Please describe.

Currently, when the user comes to the play ideas page looking for some ideas to practice, there is only the title and short description of some ideas listed there.

There are only two options they can do with any idea, 
1) Create their own idea (which takes to the same how-to-create-play/ section in docs)
2) Start a discussion on the repo for that idea

### Describe the solution you'd like.

From the user's point of view, when they come to the ideas page looking for some project ideas and wants to see what the project code/application looks like, he/she does not find it on that page.

My suggestion would be to : 

Provide a link to the play of that idea, it could be the code link/demo link which will help the users to get some idea.

### Describe alternatives you've considered.

An alternative suggestion would be to create another button **View Play** just like Create or Start discussion, on click of which the user is taken to the plays page of that idea. 

### Screenshot / Screenshare

![Screenshot 2023-10-04 at 10 13 48](https://github.com/reactplay/react-play/assets/14998623/5b401755-77dd-4ae0-bdac-6bc54bbedf26)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhishek-90** [comment]
@HarshithaSolai I think the whole idea of the Play Idea page is to give the contributor an idea of what type of plays can be created, why would they need a link to the play's code or url, all the plays are directly visibles on plays page?
