### ISSUE TITLE
[Add a Play]: Create QR Code Generator in React

### ISSUE THREAD

**Issue by BikramNarayan** [reactplay/react-play#1287]
### What's the Play about?

**Project Description:**
I propose creating a React project that allows users to input any text or link and converts it into a unique QR code. I plan to use the `qrcode.react` library to implement this feature.

Pls assign this issue to me.

### What ReactJS concept will be used to create this play?

**Proposed Tasks:**
- Set up a React project.
- Integrate the `qrcode.react` library.
- Create a user-friendly interface for input.
- Implement the QR code generation logic.
- Ensure proper error handling.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BikramNarayan** [comment]
Hello @joshi-kaushal,

Could you please assign this issue to me? I'm interested in working on it.

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
