### ISSUE TITLE
🐛 [Bug report]: UPDATE TWITTER LOGO

### ISSUE THREAD

**Issue by Roar022** [reactplay/react-play#1291]
### Descrcibe the bug?

As twitter has updated its logo, therefore it is necessary for website to be updated. 

### Steps to reproduce the bug?

1. Go to https://reactplay.io/
2. At right side of header you old twitter logo.

### Expected behavior

Updated twitter logo is **`X`**.

### Desktop (Please provide your system information)

Linux

### Relevant log output

```shell
Please provide this issue to me.
```

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we've changed the logo you can see 
![image](https://github.com/reactplay/react-play/assets/88102392/d1a26adb-40f7-4dbe-ab47-03cbff0cffa4)

**Comment by Roar022** [comment]
> we've changed the logo you can see ![image](https://user-images.githubusercontent.com/88102392/272836308-d1a26adb-40f7-4dbe-ab47-03cbff0cffa4.png)

![Screenshot_20231005_145533](https://github.com/reactplay/react-play/assets/111555339/3092ff1e-e711-4908-a3f4-7d631f02f92e)
But in the deployed site it is showing old twitter logo.

**Comment by priyankarpal** [comment]
Just yesterday, it displayed a new logo. :)

**Comment by Roar022** [comment]
> Just yesterday, it displayed a new logo. :)

in the deployed site it is showing old twitter logo, but in local machine it is showing new logo.

**Comment by priyankarpal** [comment]
> > Just yesterday, it displayed a new logo. :)
> 
> in the deployed site it is showing old twitter logo, but in local machine it is showing new logo.

maybe a caching issue

**Comment by saniyasaher20** [comment]
@priyankarpal I think it's not the caching issue, I have opened it in incognito modes and also in different browsers to cross-check. The problem is `react-icons` library version is `^4.3.1`. It needs to be updated.

**Comment by priyankarpal** [comment]
> @priyankarpal I think it's not the caching issue, I have opened it in incognito modes and also in different browsers to cross-check. The problem is `react-icons` library version is `^4.3.1`. It needs to be updated.

i guess this issue got solved
