### ISSUE TITLE
[Add a Play]: Making Drum Kit

### ISSUE THREAD

**Issue by Roar022** [reactplay/react-play#1292]
### What's the Play about?

A Drum kit is a web application or webpage that simulates the experience of playing a drum kit using only your computer keyboard or mouse. It's a fun and interactive way to create drum sounds and rhythms in a digital environment. 

### What ReactJS concept will be used to create this play?

- Event Listeners
- Audio Playback
- DOM Manipulation
- Conditional Statements
- Arrays and Data Structures
- Functions
- Timers and Animation
- Error Handling
- Event Propagation

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshi-kaushal** [comment]
Hi @Roar022! Do you want to create this play by yourself? Can assign this issue to you if you are willing to take it up

**Comment by Roar022** [comment]
> Hi @Roar022! Do you want to create this play by yourself? Can assign this issue to you if you are willing to take it up

YES.

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
