### ISSUE TITLE
🐛 [Bug report]: I can't create A Play and the website gives me an error about sending an api request to the analytics

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#1295]
### Descrcibe the bug?

When I create a react play it gives me error and return me to the home page

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

OS: Windows 11
Browser: Chrome

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/96921717/3308cdc5-fb9a-4f44-83bb-9826219021b1)
![image](https://github.com/reactplay/react-play/assets/96921717/13f475db-41cf-40b9-9d1f-f81f9e4abca1)
![image](https://github.com/reactplay/react-play/assets/96921717/defc0a38-0b4b-4a36-92e8-ff075053389b)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayushsgithub** [comment]
@Programming-School-Pro-Coding Did you start the dev server as per the instructions? Or after cloning the repo, did you make some changes in the repo?

**Comment by joshi-kaushal** [comment]
Can you please provide steps to reproduce this?

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding Did you start the dev server as per the instructions? Or after cloning the repo, did you make some changes in the repo?

I started the development as the instructions I start with `npm run start:nolint`, After cloning the repo no I didn't make any changes

**Comment by Programming-School-Pro-Coding** [comment]
> Can you please provide steps to reproduce this?

I cloned the repo and run the code

**Comment by priyankarpal** [comment]
> > Can you please provide steps to reproduce this?
> 
> I cloned the repo and run the code

yes https://github.com/reactplay/react-play/pull/1275 you can see the solution

**Comment by Programming-School-Pro-Coding** [comment]
> > > Can you please provide steps to reproduce this?
> > 
> > 
> > I cloned the repo and run the code
> 
> yes #1275 you can see the solution

Hey please reply to me at #1257

**Comment by atapas** [comment]
@Angra974 @priyankarpal We should disable the analytics now as we are not using it. Can we disable it with minimal changes?

**Comment by Angra974** [comment]
> @Angra974 @priyankarpal We should disable the analytics now as we are not using it. Can we disable it with minimal changes?

I do it in some mins if my network permit it ^^

**Comment by priyankarpal** [comment]
> @Angra974 @priyankarpal We should disable the analytics now as we are not using it. Can we disable it with minimal changes?

Yeah! we need to do
