### ISSUE TITLE
[Add a Play]: Hangman Game

### ISSUE THREAD

**Issue by ANKITy102** [reactplay/react-play#1297]
### What's the Play about?

I would like to develop Hangman game.

**Below is the description of the game:**

- Ask a question related to a word and let the user guess it.
- Limit users to a certain number of wrong guesses.
- Display parts of a hangman figure for each incorrect guess.
- If the hangman figure is fully formed, the user loses.

**Could you please assign me this issue?**

### What ReactJS concept will be used to create this play?

I will use React useState, useRef, useEffect hooks. 
It will  use react-dom and other libraries of the react.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshi-kaushal** [comment]
Hi @ANKITy102! Do you want to take this up and create a play by yourself?

**Comment by ANKITy102** [comment]
> Hi @ANKITy102! Do you want to take this up and create a play by yourself?

@joshi-kaushal 
Yes, I would like to create the play by myself. Thank you for assigning me.
