### ISSUE TITLE
[Add a Play]:Sudoku 

### ISSUE THREAD

**Issue by sukritmalpani** [reactplay/react-play#1301]
### What's the Play about?

Sudoku is a logic-based,combinatorial number-placement puzzle. In classic Sudoku, the objective is to fill a 9 × 9 grid with digits so that each column, each row, and each of the nine 3 × 3 subgrids that compose the grid contains all of the digits from 1 to 9. The puzzle setter provides a partially completed grid, which for a well-posed puzzle has a single solution.

**I want to implement this play feature.Can you please assign me this issue under the label of hacktoberfest.**

### What ReactJS concept will be used to create this play?

* **Components**: Sudoku board, individual cells, buttons for user interactions, a timer, and other UI elements.
* **State Management**: React's useState hook or a state management library like Redux can be used to store and update the state of the game.
* **Props**: Pass the current state of the board to individual cell components.
* **Event Handling**:event handlers like onClick to allow users to interact with the Sudoku board, selecting cells, and inputting numbers.
* **Conditional Rendering**: Conditionally render different components or messages (e.g., displaying a "Win" message when the puzzle is solved).
* **Component Lifecycle**: Functional components have hooks like useEffect. 

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mohit1310** [comment]
I would like to take this task
