### ISSUE TITLE
[Add a Play]: Flappy Bird Game

### ISSUE THREAD

**Issue by cyberviking5** [reactplay/react-play#1302]
### What's the Play about?

Flappy Bird is an endless game that involves a bird that the player can control. 
* The player has to save the bird from colliding with the hurdles like pipes. 
* Each time the bird passes through the pipes, the score gets incremented by one. 
* The game ends when the bird collides with the pipes or falls down due to gravity. 
* The sections below describe the steps that have to be taken for building this game.

**Could you please assign me this issue under hacktoberfest tag :)**

### What ReactJS concept will be used to create this play?

* React Components: Breaking down different parts of your game into reusable React components
* State Management: React's state management for handling game logic. Keeping track of the bird's position, the pipes, the score, and other game-related data.
* Score Keeping: React's state can be used to keep track of the player's score.
* Rendering: The game's visuals will be rendered using React's JSX and the ReactDOM library to display and update the game on the web page.
* User Input:Event handlers like onClick or onKeyPress to detect user input for controlling the bird's jump.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cyberviking5** [comment]
@joshi-kaushal could you please assign me this issue :)

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
