### ISSUE TITLE
✨ [Feature request]: use cdn links instead of images

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1304]
### Is your feature request related to a problem? Please describe.

Currently, we store images in our repository and would like to reduce the project size by utilizing CDN links.

### Describe the solution you'd like.

currently, we are storing images in our repo, we need to use CDN links to minimize the project size

### Describe alternatives you've considered.

.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Angra974** [comment]
Hi. 
Not a good idea in my opinion if I can voice it.
I'm on a very slow network, and other people too if I remember correctly some problems we had in May 2023.
The application itself is really slow. I've noted about 130 request on a page for the leaderboard when i was creating test for the page. It's a lot,. The application is not optimized enough. 

It will be ok for the reactplay.io as it will not host the images, but will slow down the development in localhost for others.
Doesn't think 
we can get an overall benefice from this.

I've send some modifications related to optimization of the script but as a whole project, it's not easy to move the boat so we can just take it with small steps.

Thinking about it, you can clone the plays repo on demand and ship only some basic in the main application.
And let the developper to download all the plays or only use the minumum provided. 
When you want to create a play, you don't need to have 100 in your folder.

**Comment by priyankarpal** [comment]
ok
