### ISSUE TITLE
✨ [Feature request]: Visually appealing small helping window

### ISSUE THREAD

**Issue by irfanmit** [reactplay/react-play#1305]
### Is your feature request related to a problem? Please describe.

When i was new here in the website [reactplay.io](url) and when i didn't know about the buttons and what they stand for....i hovered over them for some suggestion window to appear to brief me a little about them but there was none

### Describe the solution you'd like.

The solution that i would like to discuss....just like when your are working on a chrome tab...you hover over different tab you will notice a small visually appealing and pictorial helping window like this
![good first issue](https://github.com/reactplay/react-play/assets/97839373/adab02e2-8ad7-4c13-b48f-84e7862ec87c)

**I wanted a similar small helping window to appear for the newbies.. when they visit the website specifically for the home page.**

### Describe alternatives you've considered.

Well on the exact approach that i will use i am still working on it....i will find the most compatible approach that fits the already present code and will look for alternatives too

### Screenshot / Screenshare

![good first issue](https://github.com/reactplay/react-play/assets/97839373/8a2aba87-fc09-4b97-bb2b-f4f86370739c)

**Just like this i want here to appear when hovered over buttons**

![good first issue2 jpeg](https://github.com/reactplay/react-play/assets/97839373/7065c57e-df9c-4fbd-bead-a3a8aa0da7b4)

### Additional context

**Please assign the task to me**
I will use most compatible approach to add this feature

@irfanmit
Regards..

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by irfanmit** [comment]
> ### Is your feature request related to a problem? Please describe.
> When i was new here in the website [reactplay.io](url) and when i didn't know about the buttons and what they stand for....i hovered over them for some suggestion window to appear to brief me a little about them but there was none
> 
> ### Describe the solution you'd like.
> The visually appealing and interactive solution that i would like to discuss....just like when your are working on a chrome tab...you hover over different tab you will notice a small visually appealing and pictorial helping window like this ![good first issue](https://user-images.githubusercontent.com/97839373/273156975-adab02e2-8ad7-4c13-b48f-84e7862ec87c.jpeg)
> 
> I wanted a similar small helping window to appear for the newbies.. when they visit the website specifically for the home page.
> 
> ### Describe alternatives you've considered.
> Well on the exact approach that i will use i am still working on it....i will find the most compatible approach that fits the already present code and will look for alternatives too
> 
> ### Screenshot / Screenshare
> ![good first issue](https://user-images.githubusercontent.com/97839373/273158222-8a2aba87-fc09-4b97-bb2b-f4f86370739c.jpeg)
> 
> Just like this i want here to appear when hovered over buttons
> 
> ![good first issue2 jpeg](https://user-images.githubusercontent.com/97839373/273158434-7065c57e-df9c-4fbd-bead-a3a8aa0da7b4.png)
> 
> ### Additional context
> **Please assign the task to me** I will use most compatible approach to add this feature
> 
> @irfanmit Regards..
> 
> ### Record
> * [x]  I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
> * [x]  I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
> * [x]  I want to work on this issue
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hello @irfanmit Where would you like to add the feature?

**Comment by irfanmit** [comment]
> hello @irfanmit Where would you like to add the feature?

Yeah anywhere where there is some unknown button...that user don't know functionality... I will try with navbar(top section )buttons first

**Comment by priyankarpal** [comment]
@irfanmit here I just clicked on the `leader board` button, you can see there is already a text 

![image](https://github.com/reactplay/react-play/assets/88102392/8da0d6ee-c0d0-42b9-a674-cef5f843a81d)

**Comment by irfanmit** [comment]
> @irfanmit here I just clicked on the `leader board` button, you can see there is already a text 
> 
> ![image](https://github.com/reactplay/react-play/assets/88102392/8da0d6ee-c0d0-42b9-a674-cef5f843a81d)
> 

But hover over button like `browse` `events` `create`...there is none... it's not very mandatory to apply but it will be a bit visually appealing...so if you like the idea I may give a try
