### ISSUE TITLE
🐛 [Bug report]: Github Actions running on forked repos

### ISSUE THREAD

**Issue by sudipkundu999** [reactplay/react-play#1307]
### Descrcibe the bug?

The Github actions intended to run on this repo `reactplay/react-play`
are also running on forked repo `<username>/react-play`

Problems
- Triggering emails of failed workflows on forked repos
<img width="910" alt="image" src="https://github.com/reactplay/react-play/assets/95222845/bc31db15-b5ea-4c87-838b-f1a6a953167b">

- running unwanted workflow also uses the Free quota of GitHub Actions

### Steps to reproduce the bug?

1. Fork the repo (if not already)
2. Head over to the `actions` tab. You'll see something like this
<img width="1440" alt="image" src="https://github.com/reactplay/react-play/assets/95222845/03fe423c-f6f7-4f2e-b755-df0379ccbe26">

### Expected behavior

- The `actions` tab should be empty 
- No GitHub actions should run on forked repos

### Desktop (Please provide your system information)

- OS: MacOS 14.0
- Browser: Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
got the error. assigned to you
