### ISSUE TITLE
[Add a Play]: PAC MAN Game 

### ISSUE THREAD

**Issue by BikramNarayan** [reactplay/react-play#1309]
### What's the Play about?

I want to add an  **engaging** and  **interactive** **PAC MAN** game with interactive design with the iconic PAC MAN character, **colorful ghosts**, and a **maze-like environment.**

**Please assign this issue to me .**

### What ReactJS concept will be used to create this play?

useRef , useEffect , useState , Event Handling , Conditional Rendering , Component Structure

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue? @BikramNarayan

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
