### ISSUE TITLE
[Add a Play]: Adding a simple stopwatch application #hackoctober #React

### ISSUE THREAD

**Issue by irfanmit** [reactplay/react-play#1311]
### What's the Play about?

Hi, the play is a simple stopwatch application made in react....
It simply starts the timer when clicked on **start** and then stops and reset  when clicked on **reset** button and you can again click to start the timer

![WhatsApp Image 2023-10-03 at 4 45 37 PM](https://github.com/reactplay/react-play/assets/97839373/9484e015-a332-4200-ae57-2f3896575505)

### What ReactJS concept will be used to create this play?

A basic react js hooks like **useState** and **useEffect** are used to make this app

****### Please assign the task to me###**** 

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shashankpantiitbhilai** [comment]
assign this to me

**Comment by priyankarpal** [comment]
> assign this to me

already assigned to someone
