### ISSUE TITLE
✨ [Feature request]: sir can i add switching dark and light mode to this website

### ISSUE THREAD

**Issue by Parthasarathip123** [reactplay/react-play#1314]
### Is your feature request related to a problem? Please describe.

It is better to use dark and light mode in the website

### Describe the solution you'd like.

adding switch dark and light mode button

### Describe alternatives you've considered.

no

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Parthasarathip123** [comment]
can you assign me this work sir

**Comment by priyankarpal** [comment]
It may not be necessary. From a user perspective, a website that is easy to navigate and understand is more effective.

**Comment by Parthasarathip123** [comment]
ok thank you
