### ISSUE TITLE
✨ [Feature request]: Add FOSS India as our Event Partner

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#1324]
### Is your feature request related to a problem? Please describe.

Add FOSS India as our Event Partner. We are the community partner of FOSS India 3.0 happening in a few weeks.

### Describe the solution you'd like.

Modify the section where we list down the event partners.

### Describe alternatives you've considered.

None

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/3633137/5c735ba1-fd6e-48ad-bfca-a52caaaffe9a)

### Additional context

Talk to @atapas or @PriteshKiri for any additional context.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue could you assign me this one?

**Comment by priyankarpal** [comment]
> Hey, I would like to work on this issue could you assign me this one?

sure

**Comment by parthrc** [comment]
hey @priyankarpal , if @AKASH-PRASAD7 doesnt reply, can u please assign it to me, Thank you.

**Comment by parthrc** [comment]
Hello @priyankarpal , let me know if i can work on this

**Comment by parthrc** [comment]
hey @priyankarpal is this still available?, I would like to work on it. Thanks

**Comment by priyankarpal** [comment]
> hey @priyankarpal is this still available?, I would like to work on it. Thanks

assigned to you
