### ISSUE TITLE
✨ [Feature request]: Add play search result summary

### ISSUE THREAD

**Issue by janvi01** [reactplay/react-play#1325]
### Is your feature request related to a problem? Please describe.

Currently, when we search play(s), it just shows the resulting plays.

### Describe the solution you'd like.

We can add a summary of how many plays match the searched term similar to in GitHub when we search repositories.

<img width="1240" alt="Screenshot 2023-10-12 at 12 45 25 PM" src="https://github.com/reactplay/react-play/assets/34344234/a1ab52c1-9154-40ba-a5a1-4f6d00280d02">

Let's say we searched for "calcu" term. It should show "4 results for plays matching **calcu** sorted by Newest" below the search bar.

<img width="1792" alt="Screenshot 2023-10-12 at 12 55 23 PM" src="https://github.com/reactplay/react-play/assets/34344234/c28042b5-3d60-4269-b53a-8e0122e2e82d">

### Describe alternatives you've considered.

None

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
@janvi01 sounds good 🚀 what do you think @atapas ?

**Comment by janvi01** [comment]
> @janvi01 sounds good 🚀 what do you think @atapas ?

@atapas

**Comment by nayakswadhin** [comment]
Can you please assign this issue?? i would love work in this.

**Comment by janvi01** [comment]
@nayakswadhin I would work on this, you can look any other issues
