### ISSUE TITLE
Fix : overlapping of icon over the text 

### ISSUE THREAD

**Issue by Sa24miksha** [reactplay/react-play#1326]
### Is your feature request related to a problem? Please describe.

The "Become a Prime Sponsor" button has an issue , the icon in that while hovering overlaps the text .

![Screenshot 2023-10-12 155838](https://github.com/reactplay/react-play/assets/100412207/1bd60ac6-9062-4e15-a776-170226393426)

### Describe the solution you'd like.

While hovering on the button the text and icon should not be overlapped but should be at a distance when hovered .

### Describe alternatives you've considered.

The icon and text should be at a correct distance when hovered is the only alternate solution i have found.

### Screenshot / Screenshare

![Screenshot 2023-10-12 155838](https://github.com/reactplay/react-play/assets/100412207/a8f2031a-ed45-4517-bfbf-a595d195cf4a)

### Additional context

i have already worked on it , please assign this to me .

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@Sa24miksha are you planning to work on it?

**Comment by Sa24miksha** [comment]
@atapas yes i will work on it , i am making a PR soon
