### ISSUE TITLE
✨ [Feature request]: Create a Home page section for Twitter mentions

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#134]
**Is your feature request related to a problem? Please describe.**
We need a place on the home page that brings the mentions we get for the ReactPlayIO Twitter handle.

**Describe the solution you'd like**
Make the Twitter API cal to fetch last 10 Tweets that mentioned the @ReactPlayIO handle and show them like cards,

**Describe alternatives you've considered**
NONE

**Additional context**
The Twitter API Key will be supplied by Admin.

**Comment by DalpatRathore** [comment]
Who is working on this Twitter mentions issue?


I have used two ways to showcase the latest tweet:
- GitHub Profile --  `lowlighter/metrics` plugin with API Key and GitHub Action
- My Portfolio Web -- `react-twitter-embed` package without API Key

**Comment by atapas** [comment]
> Who is working on this Twitter mentions issue?
> 
> I have used two ways to showcase the latest tweet:
> 
> * GitHub Profile --  `lowlighter/metrics` plugin with API Key and GitHub Action
> * My Portfolio Web -- `react-twitter-embed` package without API Key

Can you explain the second solution? What does it bring? Iframe?

**Comment by DalpatRathore** [comment]
> Can you explain the second solution? What does it bring? Iframe?

### react-twitter-embed
- React Import 
  ![carbon](https://user-images.githubusercontent.com/69510006/166946068-6c3c0513-26c8-4221-84c1-688fb64db894.png)

- Iframe Compiled Code
  ![carbon (1)](https://user-images.githubusercontent.com/69510006/166946095-eef49725-e0ea-4f45-be5a-7ec969dd08d1.png)

- Package [react-twitter-embed](https://www.npmjs.com/package/react-twitter-embed)

**Comment by atapas** [comment]
> > Can you explain the second solution? What does it bring? Iframe?
> 
> ### react-twitter-embed
> * React Import
>   ![carbon](https://user-images.githubusercontent.com/69510006/166946068-6c3c0513-26c8-4221-84c1-688fb64db894.png)
> * Iframe Compiled Code
>   ![carbon (1)](https://user-images.githubusercontent.com/69510006/166946095-eef49725-e0ea-4f45-be5a-7ec969dd08d1.png)
> * Package [react-twitter-embed](https://www.npmjs.com/package/react-twitter-embed)

How about a non-iframe based solution?

**Comment by atapas** [comment]
> **Is your feature request related to a problem? Please describe.** We need a place on the home page that brings the mentions we get for the ReactPlayIO Twitter handle.
> 
> **Describe the solution you'd like** Make the Twitter API cal to fetch last 10 Tweets that mentioned the @ReactPlayIO handle and show them like cards,
> 
> **Describe alternatives you've considered** NONE
> 
> **Additional context** The Twitter API Key will be supplied by Admin.

Here is an idea:(Taken from https://hypefury.com/)

![image](https://user-images.githubusercontent.com/3633137/167239127-ea1b42fb-af4a-49bc-8cce-c9fc02378548.png)

**Comment by DalpatRathore** [comment]
> Here is an idea:(Taken from https://hypefury.com/)

> ![image](https://user-images.githubusercontent.com/69510006/167240082-f4d0b67a-9b68-4e94-af5e-894682a9d91d.png)

The solution idea looks impressive. Though I have not implemented the `non-iframe` based solution.

**Comment by Programming-School-Pro-Coding** [comment]
I can made that using node fetch

**Comment by Anirban-1490** [comment]
Anyone working on this issue ?

**Comment by atapas** [comment]
> Anyone working on this issue ?

Nope

**Comment by Anirban-1490** [comment]
> > Anyone working on this issue ?
> 
> Nope

can i work on it?

**Comment by Anirban-1490** [comment]
> > > Anyone working on this issue ?
> > 
> > 
> > Nope
> 
> can i work on it?
if yes then like what i have to can you run down on it a bit

**Comment by atapas** [comment]
> > > > > Anyone working on this issue ?
> > > > 
> > > > 
> > > > Nope
> > > 
> > > 
> > > can i work on it? if yes then like what i have to can you run down on it a bit
> > 
> > 
> > You are most welcome. Join our discord and let's discuss.
> 
> where can i find the discord link?

Here you go
https://discord.gg/wtnbTNX2
