### ISSUE TITLE
🐛 [Bug report]: Wordle tiles' re-render on every user interaction, in Wordle Play

### ISSUE THREAD

**Issue by SamirMishra27** [reactplay/react-play#1353]
### Descrcibe the bug?

In Wordle Play, if you are entering or deleting an alphabet, all tiles forcefully re-render, causing all animations to replay.

### Steps to reproduce the bug?

- Go to [My Wordle Play](https://reactplay.io/plays/samirmishra27/wordle)
- Try clicking on buttons, entering any words or backspace

### Expected behavior

Only the tile which was modified should re-render.

I believe this issue has originated from **Issue #1186** ([Code change](https://github.com/reactplay/react-play/pull/1186#discussion_r1232578849))

### Desktop (Please provide your system information)

OS: Windows 11 22H2
Browser: Microsoft Edge

### Screenshot / Screenshare

Video attached below for visual demo
<video src="https://github.com/reactplay/react-play/assets/68955143/c0c1e18c-4997-4d6b-8fe5-c759215afa0d">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthrc** [comment]
@priyankarpal can I work on this?
