### ISSUE TITLE
[Add a Play]: DrumKit

### ISSUE THREAD

**Issue by aaqib605** [reactplay/react-play#1355]
### What's the Play about?

Drumkit is a web app for playing drum sounds with keyboard keys.

### What ReactJS concept will be used to create this play?

Components, Props

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aaqib605** [comment]
@priyankarpal What else needs to be done?

**Comment by GaneshParmar** [comment]
Any one working on this?

**Comment by aaqib605** [comment]
> Any one working on this?

Yes
