### ISSUE TITLE
✨ [Feature request]: Animations on the three buttons "Learn" , "Create" ,and "socialize"

### ISSUE THREAD

**Issue by rverma-123** [reactplay/react-play#1363]
### Is your feature request related to a problem? Please describe.

yes when we are coming on home page there is no hover effect on the three botton

### Describe the solution you'd like.

es when we are coming on home page there is no hover effect on the three botton

### Describe alternatives you've considered.

es when we are coming on home page there is no hover effect on the three botton

### Screenshot / Screenshare

V\es when we are coming on home page there is no hover effect on the three botton

### Additional context

es when we are coming on home page there is no hover effect on the three botton

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
already fixed
