### ISSUE TITLE
✨ [Feature request]:  Convert the project into TailwindCSS

### ISSUE THREAD

**Issue by najmulhc** [reactplay/react-play#1373]
### Is your feature request related to a problem? Please describe.

I started to have a look at the project, and while visiting the codebase, I saw the CSS is written in raw CSS. However, it is hard for beginners me to understand the style while reading the JSX code. So I thought it would be interesting for us if we could consider this project converted into a Tailwind-based CSS.

### Describe the solution you'd like.

I have planned to convert each component has styles in raw CSS that will be converted into tailwind classes. 

### Describe alternatives you've considered.

I have thought about using any third-party tailwind CSS library like **DaisyUI**.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we are already using Tailwind CSS in our project. there are lots of codes we need to convert. what do you think @atapas?

**Comment by atapas** [comment]
> we are already using Tailwind CSS in our project. there are lots of codes we need to convert. what do you think @atapas? 

No this is different.

The ReactPlay platform uses raw CSS. The request is to translate that to tailwind. We should accept this issue.

**Comment by janvi01** [comment]
Hey @priyankarpal @atapas I would like to collaborate on this issue. I think the issue needs changes in bulk.

**Comment by atapas** [comment]
> Hey @priyankarpal @atapas I would like to collaborate on this issue. I think the issue needs changes in bulk.

Sure you can

**Comment by humayunkabir** [comment]
Hey @atapas, can I contribute in this issue?

**Comment by priyankarpal** [comment]
hello, @janvi01 and @najmulhc Can you update me on the progress of this particular issue?

**Comment by janvi01** [comment]
Hey @priyankarpal I won't be able to work on this now as I am filled with too much other work/stuff these days

**Comment by priyankarpal** [comment]
> Hey @priyankarpal I won't be able to work on this now as I am filled with too much other work/stuff these days

ok no issue

**Comment by priyankarpal** [comment]
> Hey @atapas, can I contribute in this issue?

I'm assigning you

**Comment by humayunkabir** [comment]
Is @najmulhc also working on this issue?

**Comment by priyankarpal** [comment]
@najmulhc Can you update me on the progress of this particular issue?

**Comment by priyankarpal** [comment]
> Is @najmulhc also working on this issue?

If @najmulhc doesn't update within the next three days, you can start working on it.

**Comment by humayunkabir** [comment]
> > Is @najmulhc also working on this issue?
> 
> 
> 
> If @najmulhc doesn't update within the next three days, you can start working on it.

I can start working at the end of December, I am on vacation right now.

**Comment by priyankarpal** [comment]
> > > Is @najmulhc also working on this issue?
> > 
> > 
> > If @najmulhc doesn't update within the next three days, you can start working on it.
> 
> I can start working at the end of December, I am on vacation right now.

ok

**Comment by mdsaifullah365** [comment]
I want to contribute. Please, assign me to this issue. @priyankarpal @atapas

**Comment by bhansa** [comment]
I'm happy to look into this, please let me know if someone is working on this code and I should collaborate.

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
