### ISSUE TITLE
[Refactor] I want to refactor and add js docs comment into `formatDate` method 

### ISSUE THREAD

**Issue by saddam-selise** [reactplay/react-play#1374]
### File Name

src/common/utils/commonUtils.js

### Reason for Refactoring the Code

Reson for refactoring:

- Readability: The code lacks readability due to non-descriptive variable names and a lack of clear structure.
- Maintainability: The code is not easily maintainable, as changing the date formatting would require modifications in multiple places.
- Performance: The code is not optimized for performance, with potentially costly operations like splitting the date string into an array and incorrect date object instantiation.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I am in Hacktoberfest
- [X] I want to work on this issue

**Comment by atapas** [comment]
PR https://github.com/reactplay/react-play/pull/1376
