### ISSUE TITLE
[Add a Play]: DevCafe

### ISSUE THREAD

**Issue by Soab42** [reactplay/react-play#1375]
### What's the Play about?

DevCafe is a vibrant online space where developers, coders, and tech enthusiasts come together to share knowledge, discuss coding challenges, and savor the aroma of innovation. Grab a virtual coffee, engage in tech talks, and find the inspiration and insights you need to excel in the world of coding and development. Join the DevCafe community and fuel your passion for all things tech.

### What ReactJS concept will be used to create this play?

useState, useEffect, useContext, React Router, React-Redux

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Soab42** [comment]
can i use redux and any option to access the  database?

**Comment by priyankarpal** [comment]
any updates? @Soab42

**Comment by Soab42** [comment]
yes! actually almost complete.  Last finishing touch up need. https://devcafee.netlify.app/ here is the demo looks like.

**Comment by priyankarpal** [comment]
> yes! actually almost complete. Last finishing touch up needed. https://devcafee.netlify.app/ here is the demo looks like. Please! give me suggestions if you see any issues.

you can add

**Comment by Soab42** [comment]
![Screenshot 2023-12-18 183757](https://github.com/reactplay/react-play/assets/108150913/e88205b8-819d-4704-8b1f-cbeb2715d96a)
I'm getting this problem when I run react-play locally.

**Comment by priyankarpal** [comment]
> ![Screenshot 2023-12-18 183757](https://private-user-images.githubusercontent.com/108150913/291292081-e88205b8-819d-4704-8b1f-cbeb2715d96a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTIzNTMsIm5iZiI6MTcwMjkxMjA1MywicGF0aCI6Ii8xMDgxNTA5MTMvMjkxMjkyMDgxLWU4ODIwNWI4LTgxOWQtNDcwNC04YjFmLWNiZWIyNzE1ZDk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxNTA3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjc2OWUxZGMzM2Q5OWE5YTU1ODkwNzEyNDc5NTZhNDViMzViZDI0Y2ViYjE2NmNkODM0NWQxZjY1YjIwZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gb07QsSq15jE7Xhv_5cOXWqKBXcp-2aJ7RsIaGEbZIY) I'm getting this problem when I run react-play locally.

can you share the exact details of how to produce this error?

**Comment by Soab42** [comment]
just open that project on vs code and hit yarn start.  then it says network errors.

**Comment by Soab42** [comment]
![image](https://github.com/reactplay/react-play/assets/108150913/cf2e96cf-8501-439f-b7b7-697e0feb798d)

**Comment by Soab42** [comment]
![image](https://github.com/reactplay/react-play/assets/108150913/c931b07b-4e22-4d06-b409-adc423688937)
![image](https://github.com/reactplay/react-play/assets/108150913/e51a519f-3a2f-44f8-9d26-c0ac64b7fa10)
maybe that is the issue
