### ISSUE TITLE
[Refactor] Excessive Prop Usage in Component

### ISSUE THREAD

**Issue by Luiz-Eduardo-BL** [reactplay/react-play#1379]
### File Name

src/common/Testimonial /TestimonialModal.jsx

### Reason for Refactoring the Code

I’ve noticed an issue in the code where a component is receiving an excessive number of props. This is generally considered a code smell and can lead to difficulties in maintaining and understanding the code.

**Rule of Thumb for Prop Usage**
As a rule of thumb, three props is fine, five props is a code smell, and more than seven props is a disaster. In our case, the component is receiving more than seven props, which is far beyond the recommended limit.

**Impact of Excessive Prop Usage**
This excessive usage of props can make the component bloated and hard to maintain. If the number of props is making the component bloated, then we have reached our limit. Proper composition should help us avoid passing props through multiple components.

**Proposed Solution**
One potential solution to this issue is to group similar props into one object and pass it. This approach can help to reduce the number of props being passed and make the code cleaner and easier to understand.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I am in Hacktoberfest
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Your suggestion to group similar props into one object makes sense. You can work on this issue @Luiz-Eduardo-BL

**Comment by Luiz-Eduardo-BL** [comment]
Okay, got it. I'll start working on it now.
