### ISSUE TITLE
🐛 [Bug report]: Favicon not available on plays

### ISSUE THREAD

**Issue by joshi-kaushal** [reactplay/react-play#1383]
### Descrcibe the bug?

Favicons are not visible on individual plays. However, they are visible on our homepage.

### Steps to reproduce the bug?

1. Open any play from reactplay.io

### Expected behavior

I expected to see ReactPlay icon on title bar

### Browser
- Microsoft Edge
- Version 119.0.2151.44 (Official build) (64-bit)

## Operating system 
- Windows 10 64bit

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/53049546/ff790968-f3c1-4367-a19f-787896c456cf)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
@v4xsh
