### ISSUE TITLE
[Add a Play]: Github User Search

### ISSUE THREAD

**Issue by dev-keshav** [reactplay/react-play#1386]
### What's the Play about?

Github User Search app fetches GitHub user's data using the GitHub API, displaying public repositories and storing search history in the browser's local storage. It offers an efficient way for developers to explore and access GitHub projects.

### What ReactJS concept will be used to create this play?

useState Hook, useEffect, useDisclosure(Chakra-UI), 

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-keshav** [comment]
Need help... Whenever I do click on create a play button after filling the details then this happens:
![Screenshot 2023-11-22 010354](https://github.com/reactplay/react-play/assets/71294563/9f803262-b945-4967-8537-52da0c501065)

**Comment by v4xsh** [comment]
Hi, can you please tell where exactly are you facing this problem
