### ISSUE TITLE
just simple one line css code need changes  

### ISSUE THREAD

**Issue by fnHabib** [reactplay/react-play#1388]
### File Name

app.css

### Reason for Refactoring the Code

.list-home-features .home-features-item .item-icon ![ReactPlay - One app to learn, create, and share ReactJS projects  (18 11 2023 14_32)](https://github.com/reactplay/react-play/assets/72821468/9739e8d4-9c1a-42d7-b116-5dfa0b2dec18)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I am in Hacktoberfest
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I don't think we need a cursor pointer for the section now; It appears that there are no links currently connected.
