### ISSUE TITLE
chore: remove `hacktoberfest` checkbox from issue templates

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1390]
### File Name

.github/ISSUE_TEMPLATE

### Reason for Refactoring the Code

remove all `I am in Hacktoberfest` from all issue templates 

![image](https://github.com/reactplay/react-play/assets/88102392/fc140bf3-a0db-480e-a2cf-1a96fa174f3f)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I am in Hacktoberfest
- [ ] I want to work on this issue

**Comment by yash358** [comment]
Hey @priyankarpal can you check my PR #1409
