### ISSUE TITLE
🐛 [Bug report]: @faker-js/faker: faker.name is deprecated since v8.0 and will be removed in v10.0. Please use faker.person instead.

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1396]
### Descrcibe the bug?

[@faker-js/faker]: faker.image.imageUrl has been deprecated since v8.0 and will be removed in v9.0. Please use faker.image.url instead.

### Steps to reproduce the bug?

visit https://reactplay.io & check the console, you will see `[@faker-js/faker]` error. We need to change the deprecated package 

### Expected behavior

n/a

### Desktop (Please provide your system information)

OS: Kali Linux
Browser: Brave

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/760aa524-bd8c-4a7c-9eff-3286d3415bc0)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devAlisha** [comment]
I want to work on this issue

**Comment by priyankarpal** [comment]
> I want to work on this issue

sure
