### ISSUE TITLE
🐛 [Bug report]: Linting error on QuizApp.tsx

### ISSUE THREAD

**Issue by kenselasie** [reactplay/react-play#1398]
### Descrcibe the bug?

After cloning the repo and running yarn start, there is a linting error on QuizApp.tsx

### Steps to reproduce the bug?

1. Clone repo
2. yarn install
3. yarn start

### Expected behavior

App should run without any linting errors

### Desktop (Please provide your system information)

OS: Mac
browser: Brave / Chrome

### Screenshot / Screenshare

<img width="708" alt="Screenshot 2023-11-28 at 7 33 10 PM" src="https://github.com/reactplay/react-play/assets/49798394/bee9e777-47b4-4e3c-a768-99620268c143">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
try this `yarn start:nolint`

check the readme https://github.com/priyankarpal/react-play/tree/main?tab=readme-ov-file#-start-the-development-mode

**Comment by kenselasie** [comment]
Readme says "...However make sure that you run start script at least once before committing your code. Code with linter error may not be reviewed."

But wont run with this lint error not fixed.

**Comment by priyankarpal** [comment]
check the PR https://github.com/reactplay/react-play/pull/1400

**Comment by Angra974** [comment]
Usually, this notification is when something was submitted without formatting and escape from linting.
We have some ways to bypass the linting without husky running.
It's not the good way but sometimes you need to do it, or you do it without thinking about it.
One solution is the application was submitted without a prior installation so husky package is not installed and won't run.
The second solution is to tell git to not use husky.

Currently, 
you need, i think to run a "yarn format" to correct the files with prettier as it seems like some identation are not right in the code.
