### ISSUE TITLE
🐛 [Bug report]: Unable to Load Plays on "reactplay.io/plays" Page

### ISSUE THREAD

**Issue by saifscripter** [reactplay/react-play#1402]
### Descrcibe the bug?

ReactPlay users are experiencing difficulties loading plays from the "reactplay.io/plays" page. The problem appears to be related to network resource loading errors. 

### Steps to reproduce the bug?

1. Navigate to "https://reactplay.io".
2. Click on the "Browse" button.
3. A loading screen will appear, and you will notice the plays are not loading.

### Expected behavior

Expecting to view plays created by contributors.

### Desktop (Please provide your system information)

OS: Windows 11
Browser: Chrome
Version 119.0.6045.200

### Mobile (Please provide your device information)

N/A

### Screenshot / Screenshare

<img width="960" alt="image" src="https://github.com/reactplay/react-play/assets/90335282/7d9b94c7-4430-4a70-a223-3bb8a4fd526d">

### Relevant log output

<img width="315" alt="image" src="https://github.com/reactplay/react-play/assets/90335282/ca97063c-836d-4a35-9474-f25851c79827">

<img width="340" alt="image" src="https://github.com/reactplay/react-play/assets/90335282/c9e23cea-0916-43b7-83d9-4845baffeab0">

<img width="792" alt="image" src="https://github.com/reactplay/react-play/assets/90335282/c1d2b426-de02-4890-a8a6-f6a9a83d40a5">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Yes, I am also experiencing the same issue.

**Comment by priyankarpal** [comment]
Recently Nhost has deprecated the old backend URL and we had to move to the new URL convention.. else the data fetching will fail. 

join our discord server for updates 

https://discord.com/channels/982239924227031070/983209230729379901/1184336384127934504

**Comment by priyankarpal** [comment]
fixed https://github.com/reactplay/react-play/pull/1405

**Comment by saifscripter** [comment]
Thanks for the fix.
