### ISSUE TITLE
🐛 [Bug report]: header appears to break and display incorrectly

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1406]
### Descrcibe the bug?

When viewing the playlist page in responsive mode, the header appears to break and display incorrectly.

### Steps to reproduce the bug?

n/a

### Expected behavior

n/a

### Desktop (Please provide your system information)

n/a

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/d0806c9e-2132-463b-aeb7-5d25929da900)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by White-edvil99** [comment]
#1406 accepted

**Comment by priyankarpal** [comment]
> #1406 accepted

sure

**Comment by bhushan2311** [comment]
can i work on this issue?

**Comment by priyankarpal** [comment]
hello @White-edvil99 any updates?

**Comment by White-edvil99** [comment]
Actually I was busy somewhere else in othe project so i didn't get time for this one..

**Comment by clavy123** [comment]
Hello @AlirezaEbrahimkhani, if you have resolved this issue by changing the media queries, the menu will not be displayed when toggled. Could you please assign this to me?
