### ISSUE TITLE
🐛 [Bug report]: Tip calculator design is not showing all content  and the calculator is not working , some button is is not showing 

### ISSUE THREAD

**Issue by ImtiazNayeemShawon** [reactplay/react-play#1408]
### Tip calculator design is not showing all content  and the calculator is not working, some buttons are not showing 

1. Design is broken down
2. The state is not updating perfectly
3. The Percentage applying button Is hidden but when hovering randomly it shows so it is a design issue 
4. The total amount is not showing 
<img width="604" alt="Screenshot 2023-12-13 at 7 26 15 PM" src="https://github.com/reactplay/react-play/assets/89548269/9dfb6801-9bb2-4e57-bc63-7ae32a7e7214">

### Steps to reproduce the bug?

1. Go to the React Play website 
2. Check the tip calculator application
3. check the code base in github

### Expected behavior

- When I enter the amount on the total amount field after fillup the total people amount field it sets the state to 0 again  
- total amount, total person is not showing anything that means the state is not updating 
- tips percentage is not showing its hidden for CSS issue 

### **Macbook air m2**
<img width="278" alt="Screenshot 2023-12-13 at 7 31 47 PM" src="https://github.com/reactplay/react-play/assets/89548269/65bc2ccd-9e43-47f4-9aa9-88ab8ab11412">

**Macos**: Sonoma 
**RAM**: 8GB
**Chip**: m2

### Screenshot / Screenshare

<img width="604" alt="Screenshot 2023-12-13 at 7 26 15 PM" src="https://github.com/reactplay/react-play/assets/89548269/58c0c76e-4b1e-49ab-92d2-981d0132c3c6">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by Sarthak97Jain** [comment]
Hey , i tried to reproduce the code in my local , but i am getting errors while running the project (did npm install --force also) , can you pls help me Run the App on my local.
![Screenshot (121)](https://github.com/reactplay/react-play/assets/82368183/444b0e70-3bc9-46f8-ab6d-22fe4853746e)

**Comment by ImtiazNayeemShawon** [comment]
Same problem I can't run the project on local and getting this error 
![image](https://github.com/reactplay/react-play/assets/89548269/28c0e02e-5367-44f2-8e55-53be9d5d4da8)

**Comment by ehasanrobin** [comment]
use npm run lint:fix or yarn run lint:fix to avoid eslint error and you can run the project
