### ISSUE TITLE
🐛 [Bug report]: Activities After Getting Auth Are Not Working

### ISSUE THREAD

**Issue by chhakuli123** [reactplay/react-play#1413]
### Descrcibe the bug?

After getting auth done user should be able to like any project but it's not behaving as it should.

### Steps to reproduce the bug?

- We have to put the region and subdomain in nhost initialization.

### Expected behavior

After getting auth done user should be able to like any project but it's not behaving as it should.

### Desktop (Please provide your system information)

Chrome

### Mobile (Please provide your device information)

Chrome

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/103095813/dbbf5d81-2784-45d3-9d28-0cd2782f2d70)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes we have to fix it asap

**Comment by chhakuli123** [comment]
Hi @priyankarpal 
While pushing the code it gives me 403 error. 
![image](https://github.com/reactplay/react-play/assets/103095813/1b781992-0a61-469f-b31d-fab2e49e5cba)

**Comment by priyankarpal** [comment]
> Hi @priyankarpal While pushing the code it gives me 403 error. ![image](https://private-user-images.githubusercontent.com/103095813/293115222-1b781992-0a61-469f-b31d-fab2e49e5cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzQ5OTIsIm5iZiI6MTcwMzczNDY5MiwicGF0aCI6Ii8xMDMwOTU4MTMvMjkzMTE1MjIyLTFiNzgxOTkyLTBhNjEtNDY5Zi1iMzFkLWZhYjJlNDllNWNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwMzM4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmY5ZWYyMzFhMDlkY2QzYWMyMmRhZmNiODNkOWY4M2NkNzkzZTU5NjhjOWI2Njk5YmMzNDllYmJkMTU0MWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vgour6bcK32t_9ZmwbCSzTAiRA29-JLQJZZ7jLM0g5c)

you've to clone the forked repo
