### ISSUE TITLE
perf: improve performance of reactplay.io

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1419]
### Descrcibe the bug?

we have to improve the performance, Accessibility, Best Practices, and SEO of the site.

### Steps to reproduce the bug?

1. visit https://reactplay.io & open the developer tool then click on the lighthouse tab & produce the report
![image](https://github.com/reactplay/react-play/assets/88102392/e2308433-09e4-459c-81b5-8bb1ab7d02e6)
 

### Expected behavior

.

### Desktop (Please provide your system information)

.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/a8d05e6d-3a76-4248-a004-b32d53e2a140)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janvi01** [comment]
I can work on this.

**Comment by priyankarpal** [comment]
> I can work on this.

sure
