### ISSUE TITLE
🐛 [Bug report]: The Dynamic Banner's title is not properly aligned

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1420]
### Descrcibe the bug?

The Dynamic Banner's title is not left aligned. Currently, it is right-aligned, and due to this, it seems too wired.

### Steps to reproduce the bug?

1. Go to **ReactPlay Site**
2. Click on the **Browse Play** button
3. Then, you can see that, **Dynamic Banner's Title** will not be `left-aligned`

### Expected behavior

The title of the plays must be `left-aligned` so it will look better currently it seems that something is broken.

### Desktop (Please provide your system information)

- OS: Windows
- Browser: Chrome, Edge

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/91705825/2d283a30-043a-46e8-bbab-7a453b45bb85)
![Screenshot (1432)](https://github.com/reactplay/react-play/assets/91705825/600ddd74-e7f9-4dd8-a846-ed087e6b6146)
![Screenshot (1433)](https://github.com/reactplay/react-play/assets/91705825/f9bc7d0e-4bb9-4d57-b3ac-8cb78931a6f8)
![Screenshot (1434)](https://github.com/reactplay/react-play/assets/91705825/1547bc0d-4923-4fd8-a3b4-85641ad176cb)
![Screenshot (1435)](https://github.com/reactplay/react-play/assets/91705825/d3a1c36a-a6ab-4824-8994-64016043d6f8)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes, it should be `left-aligned`.

**Comment by Priyanshu2117** [comment]
is this issue resolved?

**Comment by priyankarpal** [comment]
any updates? @Shivam-Katare

**Comment by Shivam-Katare** [comment]
Yes @priyankarpal I am raising a PR today.

**Comment by rookieCoder9** [comment]
@priyankarpal Hey I believe @Shivam-Katare is busy somewhere as it has been a week since he told to raise a PR. Can you assign the issue to me ? I am a FrontEnd Developer and it is a single line CSS fix and won't take much time.

**Comment by priyankarpal** [comment]
> @priyankarpal Hey I believe @Shivam-Katare is busy somewhere as it has been a week since he told to raise a PR. Can you assign the issue to me ? I am a FrontEnd Developer and it is a single line CSS fix and won't take much time.

sure
