### ISSUE TITLE
🐛 [Bug report]:  UI Issues in various small and medium sized devices

### ISSUE THREAD

**Issue by clevercoderjoy** [reactplay/react-play#1424]
### Descrcibe the bug?

The browse and create button on the footer overlaps other content when viewed on different small to medium sized devices.
This issue does not persist with every such device but with some of the devices.
I am attaching an image for the same with various devices that I have found.

Sol: The best solution is to move the email us and Netlify logo in a container, make it a flexbox, and move the browse and create button just below that container.
This way it will work fine on all the devices and will not overlap other contents on the footer.

![Untitled](https://github.com/reactplay/react-play/assets/74505057/5f841508-eab6-4c5f-80c0-56dd4ba0ba6e)

The image added contains a screenshot from 3 devices on which I have found the bug. There might be others too.

### Steps to reproduce the bug?

If you are using the website on a desktop, then switch to responsive view and try switching between the available devices.

If you are using a small to medium-sized device then just scroll down to the footer section and the buttons that are overlapping will be just there.

This issue is only with some of the small to medium-sized devices so you might not see this issue on your device.

### Expected behavior

The browse and create button should not be overlapped with other footer content.

### Desktop (Please provide your system information)

Laptop: Acer Nitro 5
OS: Windows 11
Browser: Chrome version 120.0.6099.225 (Official Build) (64-bit)

### Mobile (Please provide your device information)

Mobile: Samsung f54
OS: Android 14
UI: One UI 6.0

### Screenshot / Screenshare

![Untitled](https://github.com/reactplay/react-play/assets/74505057/ac932c8a-3f53-4248-8d78-324a8699413b)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
got it assigned to you @clevercoderjoy

**Comment by clevercoderjoy** [comment]
Thanks, I will finish this up in max to max 2 days.
