### ISSUE TITLE
🐛 [Bug report]: `npm run build` not working

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1432]
### Descrcibe the bug?

site not building in local development & prod 

### Steps to reproduce the bug?

1. `npm i` to install dependencies
2. `npm run dev` to run the site 
3. when you want to build the site using `npm run build` it gives us the error 

### Expected behavior

.

### Desktop (Please provide your system information)

- Kali Linux

### Screenshot / Screenshare

![reactplay](https://github.com/reactplay/react-play/assets/88102392/e4f73ab3-d6e4-4f52-8b5a-b3ec4dc214d2)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> Hi friend. Just to know, why do you use "npm run build" and you have a problem with pnpm ? Any idea?

If we run `pnpm run build`, we still get an error

**Comment by Angra974** [comment]
> > Hi friend. Just to know, why do you use "npm run build" and you have a problem with pnpm ? Any idea?
> 
> If we run `pnpm run build`, we still get an error

Yeah I know. Send you some tips on the discord channel about what i found yesterday about this.

**Comment by priyankarpal** [comment]
> > > Hi friend. Just to know, why do you use "npm run build" and you have a problem with pnpm ? Any idea?
> > 
> > 
> > If we run `pnpm run build`, we still get an error
> 
> Yeah I know. Send you some tips on the discord channel about what i found yesterday about this.

ok ok

**Comment by bhansa** [comment]
> > Hi friend. Just to know, why do you use "npm run build" and you have a problem with pnpm ? Any idea?
> 
> If we run `pnpm run build`, we still get an error

@priyankarpal can you post the error you're getting while building the project.


I have setup the project in gitpod and getting this error while running `npm run build`
```bash
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../node_modules/open' in '/workspace/react-play/node_modules/plays/test'
```

**Comment by priyankarpal** [comment]
yes same error @bhansa 

here is the error in vs code (local setup)
```bash
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../node_modules/open' in '/home/pewpew/Desktop/react-play/node_modules/.pnpm/plays@0.7.0/node_modules/plays/test'
```

**Comment by bhansa** [comment]
I realize that it is originating from here:

```javascript
(function(root, server, browser) {
    if (typeof document == 'undefined') server();
    else browser(root);
}(this, function() {
    require('../node_modules/open')(__dirname + '/index.html');
}, function(root) {
    var aok = root.aok
      , log = aok.log
      , plays = root.plays
      , create = Object.create
      , isArray = Array.isArray;
```

where it is not able to find the node module open.

I'm looking in this direction. I will try couple of ways and confirm back my analysis.

**Comment by priyankarpal** [comment]
> I realize that it is originating from here:
> 
> ```js
> (function(root, server, browser) {
>     if (typeof document == 'undefined') server();
>     else browser(root);
> }(this, function() {
>     require('../node_modules/open')(__dirname + '/index.html');
> }, function(root) {
>     var aok = root.aok
>       , log = aok.log
>       , plays = root.plays
>       , create = Object.create
>       , isArray = Array.isArray;
> ```
> 
> where it is not able to find the node module open.
> 
> I'm looking in this direction. I will try couple of ways and confirm back my analysis.

ok sure. The test file is looking for an `index.html` file in `node_modules/open/` folder but here is an `index.js` file.


discord discussion https://discord.com/channels/982239924227031070/1202465168634810399

**Comment by priyankarpal** [comment]
@bhansa any updates?

**Comment by priyankarpal** [comment]
> Hi @priyankarpal, I could not spend time on it past few days. I will try to get something tomorrow.

ok

**Comment by bhansa** [comment]
Hi @Sachin-chaurasiya, I see that you have removed the `plays` dependency.
Is the build working for you?

As per my analysis It is utilized here:
https://github.com/reactplay/react-play/blob/main/src/common/playlists/PlayMeta.jsx#L3

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya, I see that you have removed the `plays` dependency. Is the build working for you?
> 
> As per my analysis It is utilized here: https://github.com/reactplay/react-play/blob/main/src/common/playlists/PlayMeta.jsx#L3

Hello @bhansa , yes build is working, and here https://github.com/reactplay/react-play/blob/main/src/common/playlists/PlayMeta.jsx#L3 we are importing all the plays from the plays directory, not the plays package.

**Comment by bhansa** [comment]
Understood! Thanks for explaining and fixing the issue as well @Sachin-chaurasiya.
