### ISSUE TITLE
✨ [Feature request]: add our meetup link icon in the footer 

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1434]
### Is your feature request related to a problem? Please describe.

add the meetup link icon & link  to the footer of the reactplay website 

meetup link: https://www.meetup.com/reactplay-bengaluru/

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/8b6dcca8-9167-4fd6-8443-bc5991b70d25)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ranitasahaa1230** [comment]
Hi @priyankarpal, I want to work on this issue, Could you please assign me this?

**Comment by ranitasahaa1230** [comment]
@priyankarpal , thank you for assigning me this issue.
What would be the icon for this? Should I add it on my own, or will someone provide it?

**Comment by priyankarpal** [comment]
> @priyankarpal , thank you for assigning me this issue. What would be the icon for this? Should I add it on my own, or will someone provide it?

it should be the meetup website's icon(round) 
![meteup](https://github.com/reactplay/react-play/assets/88102392/0aac511b-77f0-4afe-93d4-39e7fa1bf07f)
https://www.meetup.com/reactplay-bengaluru/

**Comment by priyankarpal** [comment]
hello @ranitasahaa1230 any updates?

**Comment by clavy123** [comment]
Can you assign this to me if it's not done yet @priyankarpal ?

**Comment by ranitasahaa1230** [comment]
> hello @ranitasahaa1230 any updates?

Hi @priyankarpal , it would be done by 13th February

**Comment by clavy123** [comment]
> hello @ranitasahaa1230 any updates?

I have completed this task, so could you please allow me to proceed with the PR?

**Comment by priyankarpal** [comment]
> > hello @ranitasahaa1230 any updates?
> 
> Hi @priyankarpal , it would be done by 13th February. I was facing some issues after installing the packages, so that's why it's taking time

ok ok now you can check we have fixed the build issue

**Comment by priyankarpal** [comment]
> > hello @ranitasahaa1230 any updates?
> 
> I have completed this task, so could you please allow me to proceed with the PR?

already assigned

**Comment by priyankarpal** [comment]
As there have been no updates, we need to assign someone
