### ISSUE TITLE
[Question] Error while rpm start

### ISSUE THREAD

**Issue by Meetverma** [reactplay/react-play#1436]
#Error after forking 
##upon running `npm start`

`/Users/meetverma/Documents/contributions/react-play/src/plays/quiz-app/QuizApp.tsx
  216:25  error  Insert `··`  prettier/prettier
  217:23  error  Insert `··`  prettier/prettier
  218:1   error  Insert `··`  prettier/prettier

✖ 4 problems (3 errors, 1 warning)
  3 errors and 0 warnings potentially fixable with the `--fix` option.`

I've already ran 
`npm install --legacy-peer-deps`
Still the issue persists

**Comment by priyankarpal** [comment]
hello @Meetverma it's a linting issue use this command to fix the errors `npm run lint:fix` Also, please use the existing pull request template to create an issue

**Comment by Meetverma** [comment]
Thanks for the reply @priyankarpal 
I've solved it and created the pull request 
please review and merge🙏🏻
[Link to PR](https://github.com/reactplay/react-play/pull/1437)

**Comment by priyankarpal** [comment]
> Thanks for the reply @priyankarpal I've solved it and created the pull request please review and merge🙏🏻 [Link to PR](https://github.com/reactplay/react-play/pull/1437)

The PR you've created is assigned to someone so we can't approve your PR https://github.com/reactplay/react-play/issues/1434
