### ISSUE TITLE
✨ [Feature request]: add discord icon to header

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1443]
### Is your feature request related to a problem? Please describe.

we need to add the discord icon to the header. As it is an important CTA and should be on the top

### Describe the solution you'd like.

discord invite link : https://discord.gg/9nFHKdfWMx
### Describe alternatives you've considered.

.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/9f725928-022e-4d49-9b05-5eafb1d57104)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clavy123** [comment]
Hello @priyankarpal I can work if you assign this to me.

**Comment by priyankarpal** [comment]
sure. give me the error screenshot

**Comment by priyankarpal** [comment]
pull the latest changes & run

**Comment by atapas** [comment]
> Hello @priyankarpal I can work if you assign this to me.Also,Why I am not able to login via NHhost.The page is continuously refreshing .

@chhakuli123 Adding you here.. Could you please check/help?
