### ISSUE TITLE
🐛 [Bug report]:  wrong width of play cards

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1447]
### Descrcibe the bug?

there is an issue with play cards we need to add a valid width for all play cards

file lines: https://github.com/reactplay/react-play/blob/39e591e961901a3fe686a3b507a79332d8e07fa1/src/common/playlists/playlist.css#L104

https://github.com/reactplay/react-play/blob/main/src/App.css

### Steps to reproduce the bug?

.

### Expected behaviour

wrong width

### Desktop (Please provide your system information)

kali linux
brave
latest version

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/095045d8-e2a2-4479-a676-41e59a45ee7d)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clevercoderjoy** [comment]
plz assign this one to me
once I finish the current issue I will start working on this one

**Comment by priyankarpal** [comment]
> plz assign this one to me once I finish the current issue I will start working on this one

sure
