### ISSUE TITLE
🐛 [Bug report]: center banner texts

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1449]
### Descrcibe the bug?

visit https://reactplay.io/plays & see the banner text is in the wrong position. we need to fix the position left side & middle  

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

kali linux
brave
latest

### Mobile (Please provide your device information)

.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/7ed91cf0-07e0-4c2a-8839-9ab62b64e09d)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
If this issue is up for grabs,I would like to work on it,marking my first pr to the repo

**Comment by priyankarpal** [comment]
> If this issue is up for grabs,I would like to work on it,marking my first pr to the repo

assigned to you

**Comment by prasenarthi** [comment]
I would like to fix this bug

**Comment by Akshaygore1** [comment]
a simple change is there for this

.dynamic-banner-container {
    color: #fff;
    justify-content: flex-start;
    position: flex; // delete this 
    width: 100%;

     // add these 2
    display: flex;
    align-items: center;
}

**Comment by karthiknadar1204** [comment]
have started the work, had my exams going on so was a bit inactive

**Comment by priyankarpal** [comment]
hello @karthiknadar1204 any updates?

**Comment by Akshaygore1** [comment]
> hello @karthiknadar1204 any updates?

should i do it can you assign to me @priyankarpal

**Comment by priyankarpal** [comment]
> > hello @karthiknadar1204 any updates?
> 
> should i do it can you assign to me @priyankarpal

sure

**Comment by Akshaygore1** [comment]
https://github.com/reactplay/react-play/pull/1471

Fixed @priyankarpal
