### ISSUE TITLE
🐛 [Bug report]: need to fix footer position

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1450]
### Descrcibe the bug?

if you visit the play page & check any play the footer position is different from the actual footer position, if you go to another play then the footer position is different again so we need to set a fixed footer position 

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

kali linux 
brave
latest version

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/28741c7e-7edc-4ce2-b7e1-6d8572e079e1)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prasenarthi** [comment]
i would like to fix this

**Comment by priyankarpal** [comment]
> i would like to fix this

sure

**Comment by prasenarthi** [comment]
@priyankarpal 
bug fixed. please review and update. thank you

**Comment by priyankarpal** [comment]
any updates? @prasenarthi
