### ISSUE TITLE
🐛 [Bug report]: replace to meetup link 

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1451]
### Descrcibe the bug?

replace the link to the meetup link in the `Events` button 

meetup link : https://www.meetup.com/reactplay-bengaluru/events/

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

.

### Mobile (Please provide your device information)

.

### Screenshot / Screenshare

![Screenshot_2024-02-14_15-40-13](https://github.com/reactplay/react-play/assets/88102392/30834c82-d6d6-4ad2-83b8-cd207095f42a)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clavy123** [comment]
@priyankarpal  assign this to me

**Comment by Maianki** [comment]
@priyankarpal would love to contribute. Can you please assign this to me.

**Comment by priyankarpal** [comment]
> @priyankarpal  assign this to me

sure

**Comment by clavy123** [comment]
@priyankarpal its done please check.
