### ISSUE TITLE
🐛 [Bug report]:  Testimonial card position 

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1452]
### Descrcibe the bug?

need to fix testimonial card position check the screenshot 

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

kali 
brave 
latest

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/5ce5ff0d-0108-44f5-8524-3bdc51173d3c)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Siddh744542** [comment]
@priyankarpal  can you elaborate a little more what changes are required??

**Comment by priyankarpal** [comment]
> @priyankarpal can you elaborate a little more what changes are required??

The PFP & name should be left & the tag `general` should be right

**Comment by Siddh744542** [comment]
@priyankarpal i am working on this can you assign this to me

**Comment by priyankarpal** [comment]
> @priyankarpal i am working on this can you assign this to me

sure
