### ISSUE TITLE
✨ [Feature request]: add `release-drafter` ci/cd github action for automatic releases  

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1455]
### Is your feature request related to a problem? Please describe.

We need to add the `release-drafter` GitHub Actions workflow for automatic releases. This will help us maintain a more streamlined and efficient release process.

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

### Screenshot / Screenshare

.

### Additional context

.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maianki** [comment]
@priyankarpal  would love to work on this issue. Can you please assign this to me.
