### ISSUE TITLE
✨ [Feature request]: New UI For the Play Cards

### ISSUE THREAD

**Issue by Akshaygore1** [reactplay/react-play#1460]
### Is your feature request related to a problem? Please describe.

The current UI for the play cards section exhibits significant visual deficiencies and alignment inconsistencies. The design lacks aesthetic appeal, with colors, fonts, and spacing choices failing to engage users effectively. Alignment issues further detract from the user experience, leading to confusion and difficulty in navigating the content. Improving the UI and alignment of the play cards section is essential to enhance user engagement and streamline interaction. By refining the layout, optimizing spacing, and selecting more suitable visual elements, we can ensure a more intuitive and visually pleasing experience for our users.

![ReactPlay - Plays](https://github.com/reactplay/react-play/assets/92959398/63bf80aa-0754-475d-aa6a-bdf9e4807e3c)

### Describe the solution you'd like.

I Created New UI For this I hope you will like the UI
![ReactPlay - Plays · 02 51 · 02-17](https://github.com/reactplay/react-play/assets/92959398/1900838e-9512-4bd8-9b04-c12accd7ebad)

### Describe alternatives you've considered.

Please Give the Feedback So i can Make more useful contribution

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I already created an issue for the wrong image size https://github.com/reactplay/react-play/issues/1447

we need to change the UI a little bit if you want to work on it you can

**Comment by Akshaygore1** [comment]
But i am not able to push the code I don't know why
remote: Permission to reactplay/react-play.git denied to Akshaygore1.
fatal: unable to access 'https://github.com/reactplay/react-play.git/': The requested URL returned error: 403

this error is coming

**Comment by Akshaygore1** [comment]
> I already created an issue for the wrong image size #1447
> 
> we need to change the UI a little bit if you want to work on it you can

what should i change can you suggest

**Comment by priyankarpal** [comment]
> But i am not able to push the code I don't know why remote: Permission to reactplay/react-play.git denied to Akshaygore1. fatal: unable to access 'https://github.com/reactplay/react-play.git/': The requested URL returned error: 403
> 
> this error is coming

you've to fork the repo & clone the fork repo

**Comment by priyankarpal** [comment]
> > I already created an issue for the wrong image size #1447
> > we need to change the UI a little bit if you want to work on it you can
> 
> what should i change can you suggest

add some padding to the inside of the card but avoid changing the hover color of the tech stack.

**Comment by Akshaygore1** [comment]
https://github.com/reactplay/react-play/pull/1461
