### ISSUE TITLE
🐛 [Bug report]: change the link to meetup link

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1462]
### Descrcibe the bug?

change to the meetup link  in the `events` text 

meetup link: https://www.meetup.com/reactplay-bengaluru/events/

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

.

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/199c3821-9545-4124-9a36-ee9f26c1399d)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clavy123** [comment]
I will do this assign this to me.

**Comment by priyankarpal** [comment]
> I will do this assign this to me.

sure

**Comment by clavy123** [comment]
changes done @priyankarpal
