### ISSUE TITLE
🐛 [Bug report]: fix the alignment 

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1467]
### Descrcibe the bug?

we need to fix the alignment that I mentioned in the below screenshot

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

brave 
kali 

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/b3142112-512e-42f2-954e-d281bdd7fe1e)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clavy123** [comment]
Assign this to me @priyankarpal .

**Comment by priyankarpal** [comment]
> Assign this to me @priyankarpal .

sure

**Comment by priyankarpal** [comment]
hiii @clavy123 after adding another contributor this issue got solved automatically so I have to close this

**Comment by IdoBouskila** [comment]
@priyankarpal I think it's not really centered.

Recent Version |  More Centered Version (Maybe?)
:-------------------------:|:-------------------------:
![image](https://github.com/reactplay/react-play/assets/94786579/cafae34a-f58e-465e-a185-a684231b65ba)  |  ![image](https://github.com/reactplay/react-play/assets/94786579/0b53cb48-e9f0-4965-8c2b-d69e80f075d1)



WDYT? 🤔

**Comment by priyankarpal** [comment]
> @priyankarpal I think it's not really centered.
> 
> Recent Version	More Centered Version (Maybe?)
> ![image](https://private-user-images.githubusercontent.com/94786579/308555694-cafae34a-f58e-465e-a185-a684231b65ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjYxNzksIm5iZiI6MTcwOTEyNTg3OSwicGF0aCI6Ii85NDc4NjU3OS8zMDg1NTU2OTQtY2FmYWUzNGEtZjU4ZS00NjVlLWExODUtYTY4NDIzMWI2NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEzMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NTM3YmNkZDRlMzllMGE2MGUxYzhhODNiMTAyNGJmYTMzNDExYjM0MDVjMDg2MmE2M2M2OThkMGRmYzY0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzbM1Ve09Oa5tiirGj4DLGn-En2qSm6YdYg17bPgxgc)	![image](https://private-user-images.githubusercontent.com/94786579/308556576-0b53cb48-e9f0-4965-8c2b-d69e80f075d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjYxNzksIm5iZiI6MTcwOTEyNTg3OSwicGF0aCI6Ii85NDc4NjU3OS8zMDg1NTY1NzYtMGI1M2NiNDgtZTlmMC00OTY1LThjMmItZDY5ZTgwZjA3NWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEzMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjY5NDllMzc3MTM2ZTlmMDQ2MjhkN2IyYTRjYWE5MzFjOGZhNWZhMDBiOGNlYjMwNGI1MzAwY2MyZDFjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tNwx90tKy3nmlYjdMFm9N17sc8hlINcYgP0WQk6jXMU)
> WDYT? 🤔

i think we should move it to the right a little bit

**Comment by IdoBouskila** [comment]
> i think we should move it to the right a little bit

I will try to work on it today :) @priyankarpal

**Comment by priyankarpal** [comment]
> > i think we should move it to the right a little bit
> 
> I will try to work on it today :) @priyankarpal

sure
