### ISSUE TITLE
🐛 [Bug report]: fix header items alignment 

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1473]
### Descrcibe the bug?

We need to improve the alignment of these items for better UI design. The logo should be aligned with the banner text, and the search bar should be centered.

### Steps to reproduce the bug?

.

### Expected behavior

.

### Desktop (Please provide your system information)

brave
kali

### Screenshot / Screenshare

![image](https://github.com/reactplay/react-play/assets/88102392/9a3d34eb-6e97-42d5-b270-86afa9b1ac88)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shivam-Katare** [comment]
Hey @priyankarpal, you can assign this issue to me. I will work on it.

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, you can assign this issue to me. I will work on it.

sure
