### ISSUE TITLE
🐛 [Bug report]: Hovering over the trending plays is not working properly when trying to select it from the bottom 

### ISSUE THREAD

**Issue by Mouh1b** [reactplay/react-play#1480]
### Descrcibe the bug?

i can not select the trending plays box until I reach the middle of the box content when I try to select it from the bottom

### Steps to reproduce the bug?

1.go exactly bellow the trending plays field.
2.try selecting one of the examples while dragging the mouse slowly to it .
3.you'll find that you can't select it until your mouse go past the middle of the box.

### Expected behavior

the on-hover action must activate as soon as I hover my mouse anywhere inside the box in the Trending Plays field

### Desktop (Please provide your system information)

OS: windows 10
Browser: Opera
Version: the current active one

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Karansgithub** [comment]
Hi @priyankarpal ,
I would like to work on it, can you assign me?

**Comment by priyankarpal** [comment]
> ### Descrcibe the bug?
> i can not select the trending plays box until I reach the middle of the box content when I try to select it from the bottom
> 
> ### Steps to reproduce the bug?
> 1.go exactly bellow the trending plays field. 2.try selecting one of the examples while dragging the mouse slowly to it . 3.you'll find that you can't select it until your mouse go past the middle of the box.
> 
> ### Expected behavior
> the on-hover action must activate as soon as I hover my mouse anywhere inside the box in the Trending Plays field
> 
> ### Desktop (Please provide your system information)
> OS: windows 10 Browser: Opera Version: the current active one
> 
> ### Mobile (Please provide your device information)
> _No response_
> 
> ### Screenshot / Screenshare
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Record
> * [x]  I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
> * [x]  I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
> * [x]  I want to work on this issue
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

got the error. do you want to work on this issue @Mouh1b ?

**Comment by theskrypter** [comment]
Hi @priyankarpal I've figured out that this was due to the positioning of the .play-card-container class. Adding 'position: relative' to the .play-card-container class ensures immediate activation of the on-hover action anywhere inside the box in the Trending Plays card.

I want to make a PR if no one is assigned already.

**Comment by priyankarpal** [comment]
> Hi @priyankarpal I've figured out that this was due to the positioning of the .play-card-container class. Adding 'position: relative' to the .play-card-container class ensures immediate activation of the on-hover action anywhere inside the box in the Trending Plays card.
> 
> I want to make a PR if no one is assigned already.

sure feel free to raise the pr
