### ISSUE TITLE
No Popup for install in Mobile

### ISSUE THREAD

**Issue by rapidtrader** [reactplay/react-play#1493]
I am unable to get a popup to install app in mobile browser.

can you fix or share the code of implementation of PWA for mobile app.

**Comment by priyankarpal** [comment]
do you want to work on this issue? @rapidtrader

**Comment by Programming-School-Pro-Coding** [comment]
> I am unable to get a popup to install app in mobile browser.
> 
> can you fix or share the code of implementation of PWA for mobile app.

Can you explain or provide screenshots ?

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
