### ISSUE TITLE
Screen Css issue at both mobile and desktop view 

### ISSUE THREAD

**Issue by RanaZaeem0** [reactplay/react-play#1494]
### Descrcibe the bug?

when you open the game you can see a clear issue in CSS view 

### Steps to reproduce the bug?

how to solve
1) add responsive CSS by using tailwind css

### Expected behavior

The Expected behavior by making it more responsive user friendly for all view devices like mobile iPad and desktop

### Desktop (Please provide your system information)

chrome

### Mobile (Please provide your device information)

window

### Screenshot / Screenshare

<img width="904" alt="sa1" src="https://github.com/reactplay/react-play/assets/149497053/4d335092-6e60-4c7d-9d61-f2324521e131">
<img width="404" alt="sa2" src="https://github.com/reactplay/react-play/assets/149497053/893db1f4-e939-45a0-a898-02073942af09">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RanaZaeem0** [comment]
thank you i already start working

**Comment by priyankarpal** [comment]
> thank you i already start working

any update?

**Comment by RanaZaeem0** [comment]
Hi,
Sorry for the delay,
give me 1 day I will solve this
