### ISSUE TITLE
Search bar issue when u open search bar in mobile its not responsive

### ISSUE THREAD

**Issue by RanaZaeem0** [reactplay/react-play#1495]
### Descrcibe the bug?

when the user try to input any detail in mobile is not responsive 

### Steps to reproduce the bug?

1) making its responsive

### Expected behavior

with the help of tailwind css we can solved this issue 
1) making its responsive

### Desktop (Please provide your system information)

chrome

### Mobile (Please provide your device information)

mobile pixel 1

### Screenshot / Screenshare

<img width="435" alt="inpo2" src="https://github.com/reactplay/react-play/assets/149497053/1acae28b-f0c2-4f01-870d-4e67ee6c7c89">
<img width="328" alt="inpu`1" src="https://github.com/reactplay/react-play/assets/149497053/ed81d0b0-784e-463e-93c2-a053e28ff1af">

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned

**Comment by RanaZaeem0** [comment]
thank you i alredy started working

**Comment by RanaZaeem0** [comment]
<img width="280" alt="solved 1" src="https://github.com/reactplay/react-play/assets/149497053/aef0c0a2-ce17-4312-9a24-71cd1b22c9de">



here is the picture of the mobile view

**Comment by priyankarpal** [comment]
ok
