### ISSUE TITLE
Important: migrate from ReactJS to NextJS

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1497]
## Project Update

We are excited to announce that we are moving our ReactPlay project from ReactJS to NextJS. This change will improve performance and server-side rendering, making our project faster and smoother. 

During this transition, we will be updating dependencies, changing the file structure, and modifying the code to work with NextJS. We appreciate your patience and support as we work through these changes. 

If you have any questions or need help, feel free to reach out. Thank you for being a part of our community!

## Repository update
- there is a branch named `nextjs-migration` where you need to send the pull request regarding nextjs migration
- after that this branch will be merged to the `main` branch
- we will use Vercel for deployment

![image](https://github.com/reactplay/react-play/assets/88102392/bb241e62-7bc4-4388-9180-62bb73d5eded)

 

### [Join Discord](https://discord.gg/D4kwR93xtH) 🔥

**Comment by AtulPatidar1709** [comment]
Hi @priyankarpal  I am interested in this Project, can I work with you on this Project?

**Comment by priyankarpal** [comment]
> Hi @priyankarpal I am interested in this Project, can I work with you on this Project?

yup sure you can

**Comment by shreya-mangade** [comment]
Hi @priyankarpal I am interested in this Project, can I work with you on this Project?

**Comment by priyankarpal** [comment]
yup sure
