### ISSUE TITLE
Design for Footer Component In NextJS

### ISSUE THREAD

**Issue by Abhishek-90** [reactplay/react-play#1499]
We need a design to migrate existing Footer Component in ReactPlay from react to nextjs. We need to conclude whether the component will be a `client component` or an `RSC`

`Note`: This issue is only related to Design phase, no code changes are needed.

**Comment by Ankuristic** [comment]
hello @priyankarpal can i take this issue and start working on this . could you tell at this stage we are working on only design not any coding part
