### ISSUE TITLE
[Next.JS Migration]: Next JS initialization

### ISSUE THREAD

**Issue by AnshumanMahato** [reactplay/react-play#1504]
This is in reference to #1502.

## To do :

- [ ] Create next app 
- [ ] Prepare base layout with Navigation and Footer.
- [ ] Global css
- [ ] Routing
- [ ] Config and environment files

These are some of the major stuff that will be migrated in this issue along with anything required by these to work. The goal is to have the foundation from where we can move forward.

**Comment by AnshumanMahato** [comment]
@priyankarpal it all seems good, then assign this to me and I'll start on it.

**Comment by priyankarpal** [comment]
> @priyankarpal it all seems good, then assign this to me and I'll start on it.

For now, let's finish the design part first before starting the coding.

**Comment by joshi-kaushal** [comment]
Is there any update on this? I'd love to contribute.

**Comment by priyankarpal** [comment]
> Is there any update on this? I'd love to contribute.

yes
