### ISSUE TITLE
[Add a Play]: zoomlogin

### ISSUE THREAD

**Issue by day-lee** [reactplay/react-play#1512]
### What's the Play about?

Clone project for the Zoom login page and help chatbot

### What ReactJS concept will be used to create this play?

1. State management
2. Conditional rendering
3. Routing
4. useEffect
5. Asynchronous data fetching
6. react-chatbot-kit library

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by day-lee** [comment]
Hi, 
I am trying to add my play but keep getting errors. It looks like a network issue. Can you please have a look at the error messages below and suggest what I should do next? 

>> Reading play information
     INFO : Monday, Sep 23, 2024: INFO :  Reading play information of "9f957cde-b8d6-4875-abac-1d79cfa7a220"
Error occured
file:///block/block/.npm/_npx/9c6151e77f6ebd53/node_modules/create-react-play/lib/services/datasource/index.js:49
        `Status ${err.response.status} : ${err.response.statusText}`
                               ^
TypeError: Cannot read properties of undefined (reading 'status')


Many thanks,

**Comment by priyankarpal** [comment]
try `npm` or `pnpm`

**Comment by priyankarpal** [comment]
merged
