### ISSUE TITLE
🐛 [Bug report]: Styling Issue with Filter Owner

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1518]
### Descrcibe the bug?

The `filter by owners` should be correctly aligned and in a single line.

### Steps to reproduce the bug?

1. Go to the ReactPlay Site
2. Click on the Browse button
3. Click on the `filter option` at the top side of your screen
4. Click on the `Owners Filter` to see unmatched styling

### Expected behavior

The filter owners should be correctly aligned and in a single line. If a name is too long, we can truncate it with ... and show the full name in a tooltip on hover. The current styling looks weird.

### Desktop (Please provide your system information)

OS: Windows
Browser: Chrome

### Screenshot / Screenshare

![image](https://github.com/user-attachments/assets/e97d7812-44d1-414c-8ccc-9173a263ab54)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [x] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanishq-singh-2407** [comment]
can you please assign it to me? I want to work on this.

**Comment by Sachin-chaurasiya** [comment]
> can you please assign it to me? I want to work on this.

Hey @tanishq-singh-2407  , sure assigned to you, feel free to join [ReactPlay Discord Community](https://discord.gg/vrTxWUP8Am).

**Comment by priyankarpal** [comment]
> can you please assign it to me? I want to work on this.

are you into hacktoberfest?

**Comment by tanishq-singh-2407** [comment]
Yes

**Comment by priyankarpal** [comment]
> Yes

ok

**Comment by tanishq-singh-2407** [comment]
Looks something like this!
<img width="703" alt="react-play-1" src="https://github.com/user-attachments/assets/9deb9076-ce56-413a-96fd-1745a5bdb0d3">
do I also need to write test case for tooltip?

**Comment by priyankarpal** [comment]
> Looks something like this! <img alt="react-play-1" width="703" src="https://private-user-images.githubusercontent.com/76192403/372553643-9deb9076-ce56-413a-96fd-1745a5bdb0d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MzMxNzIsIm5iZiI6MTcyNzgzMjg3MiwicGF0aCI6Ii83NjE5MjQwMy8zNzI1NTM2NDMtOWRlYjkwNzYtY2U1Ni00MTNhLTk2ZmQtMTc0NWE1YmRiMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDAxMzQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZTBlOWU3Yzk3YmFhOWYxZmYyMGFlNjY2Njg5OWEzMjAxNzhkNGYzZDFhMjQ3MzczZjFmZGVlNjFkMTY5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oY52Bg4JOKgr5eWkWFjy7eYTh0OSGG_LlwLHQH6lWE4">

looks good to me
