### ISSUE TITLE
🐛 [Bug report]: An issue with the Language filter

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1519]
### Descrcibe the bug?

If I open a filter modal and directly select a language from the options, choosing any one of them select that language but does not check the box. Because of this, I can check the same language twice.

![image](https://github.com/user-attachments/assets/86175935-14ac-4946-b1b6-02a11d840705)

If I apply these changes, reopen a modal, and try to deselect one of them, it deselects both from the list but keeps one in the options. The filtering works fine, but the UI does not function properly.

![image](https://github.com/user-attachments/assets/32404298-438c-4b9f-8416-16af13d11341)

### Steps to reproduce the bug?

1. Go to the ReactPlay Site
2. Click on the Browse button
3. Click on the filter options at the top of your screen
4. Click on the `Filter By Language` to see the incorrect behaviour of `Languages Filter`behavior

### Expected behavior

The check box and the selected item must be consistent.

### Desktop (Please provide your system information)

OS: Windows
Browser: Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Arun-cn** [comment]
can i work on this ?

**Comment by Sachin-chaurasiya** [comment]
> can i work on this ?

Hey @Arun-cn , sure assigned to you, feel free to join [ReactPlay Discord Community](https://discord.gg/vrTxWUP8Am).

**Comment by KrishDave1** [comment]
Can I work on this?Please assign this issue to me.

**Comment by priyankarpal** [comment]
@Arun-cn Can you update me on the progress of this particular issue?

**Comment by PriteshKiri** [comment]
Hey @Arun-cn,

Are you still working on this issue?

**Comment by priyankarpal** [comment]
> @Arun-cn Can you update me on the progress of this particular issue?



> Can I work on this?Please assign this issue to me.

do you want to work on it?
