### ISSUE TITLE
🐛 [Bug report]: Styling Issue with Contributors Page

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1521]
### Descrcibe the bug?

The contributor's page does not display the full image of the user. The image is cut off at the top.

![image](https://github.com/user-attachments/assets/77eef051-9c57-4e62-bbb3-e2bbe3d3a728)

When clicking on the badges (if available), the modal/dialog box opens on the left side. It should open in the center of the screen.

![image](https://github.com/user-attachments/assets/11b713fe-b581-432a-92e8-e946afa0c81a)

The text inside that modal should be in markdown format.

Instead of showing ~~ReactPlay([https://reactplay.io/](https://reactplay.io/))~~, it should display [ReactPlay](https://reactplay.io/) with clickable links.

The page is also not responsive, but it should be.

![image](https://github.com/user-attachments/assets/afb9eacd-7a38-453d-8052-478d68d1eb0d)

### Steps to reproduce the bug?

1. Go to the ReactPlay site
2. Click on the browse button
3. Open any play
4. Click on the Creator of that Play(the steps are shown below now...)

https://github.com/user-attachments/assets/a1e3bee1-593c-449a-bfa6-889eaae5ce3b

### Expected behavior

- The cut-off image should be properly visible
- The page must be responsive
- The modal should open at the center of the screen
- The text inside the modal must be in markdown format with clickable links.

### Desktop (Please provide your system information)

Browser: Chrome
OS: Windows

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Goutamchoudhary907** [comment]
I want to work on this , can you assign this to me

**Comment by priyankarpal** [comment]
> I want to work on this , can you assign this to me

Unfortunately, you can only work one issue at a time,  to allow other contributors to work.

**Comment by RohitMangale** [comment]
I'd like to contribute to this issue. Could you please assign it to me and add the Hacktoberfest tag?

**Comment by priyankarpal** [comment]
> I'd like to contribute to this issue. Could you please assign it to me and add the Hacktoberfest tag?

sure

**Comment by KrishDave1** [comment]
I can work on this issue.Can you assign this to me?

**Comment by priyankarpal** [comment]
@RohitMangale Since there haven't been any updates, we will have to unassign this issue from you.

**Comment by priyankarpal** [comment]
> I can work on this issue.Can you assign this to me?

assigned to you

**Comment by KrishDave1** [comment]
On looking at the issue myself, I see that the image being cutoff is no longer the case.Also, modal is also centered properly.Should I go ahead and change the other 2 for this issue?

**Comment by priyankarpal** [comment]
> On looking at the issue myself, I see that the image being cutoff is no longer the case.Also, modal is also centered properly.Should I go ahead and change the other 2 for this issue?

@Shivam-Katare

**Comment by Shivam-Katare** [comment]
Yes, @KrishDave1 you're correct, it's no longer a case now. So, you can work on the other two issues with this page. 

These ones:

> The text inside that modal should be in markdown format.
> 
> Instead of showing ReactPlay(https://reactplay.io/), it should display [ReactPlay](https://reactplay.io/) with clickable links.
> 
> The page is also not responsive, but it should be.

**Comment by PriteshKiri** [comment]
Hey @KrishDave1,

Any updates on the issue ?

**Comment by KrishDave1** [comment]
> Hey @KrishDave1,
> 
> Any updates on the issue ?

Was a bit busy before 2 days.Will do it in 1-2 days

**Comment by KrishDave1** [comment]
@Shivam-Katare @PriteshKiri So there are 2 ways to solve this problem.
1)We can convert the entire description in markdown text.Here the database will have to be updated to incorporate the markdown format.
2)I can hardcode for just the links I see(i.e ReactPlay link , Nhost link , and stackstream link).
I can do any of these.Please suggest which approach should be done

**Comment by KrishDave1** [comment]
@PriteshKiri @Shivam-Katare Please mention which approach I should take.Thanks

**Comment by Shivam-Katare** [comment]
Hey @KrishDave1, you can go for a 2nd approach, which is hardcoding the links.
