### ISSUE TITLE
✨ [Feature request]: Share button to share plays

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1522]
### Is your feature request related to a problem? Please describe.

Implement a feature to share play directly on socials, directly from the play cards.

![image](https://github.com/user-attachments/assets/6b424378-a1ee-460d-8c1c-4ea2af6400f2)

### Describe the solution you'd like.

We can show a share button by hovering over the play and we could add a button to share on `X` or `LinkedIn` with a good amount of elements. This could include the play title, description, thumbnail image, or a direct link to the play.

Where should the share button be placed? You can position it wherever it enhances user experience.

### Describe alternatives you've considered.

We could also add a dropdown that appears when a user clicks on an options icon (e.g., three dots). This could provide more sharing options, such as sharing on Twitter or copying a link.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kalvakeerthi** [comment]
Can you please assign this issue to me .I want to work on this issue.

**Comment by tanishq-singh-2407** [comment]
Can I work on this?

**Comment by Adil-Khan-N** [comment]
Could you please assign this issue to me?

**Comment by priyankarpal** [comment]
> Can I work on this?

sure assigned to you
