### ISSUE TITLE
✨ [Feature request]: Add Testimonial Button

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1523]
### Is your feature request related to a problem? Please describe.

There should be an option to add a testimonial directly from here, instead of clicking on the View All button and then adding it. Having the option here along with View All would be more convenient.

![image](https://github.com/user-attachments/assets/ab7ed947-52cc-44c0-b1fe-b35f68d1b187)

### Describe the solution you'd like.

There should be a button or link for submitting a testimonial directly on the same page where the testimonials are displayed. This button could be placed next to or below the "View All" button. Users would be able to add a testimonial without navigating to a separate page.

### Describe alternatives you've considered.

On the same page, we can add a **Modal for Testimonials**. Instead of redirecting to a different page, a modal could pop up when users click "Add Testimonial." This would allow users to add their feedback without leaving the current page.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Adil-Khan-N** [comment]
Could you please assign this issue to me?

**Comment by priyankarpal** [comment]
> Could you please assign this issue to me?

Unfortunately, you can only work one issue at a time,so other contributors can work.

**Comment by day-lee** [comment]
Can I work on this?

**Comment by Abhishek-90** [comment]
Assigning to you @day-lee, Happy Coding!

**Comment by KrishDave1** [comment]
This issue has not been resolved till now.Can I work on this issue?

**Comment by day-lee** [comment]
@KrishDave1 Hi, I am currently working on it locally.

**Comment by PriteshKiri** [comment]
Hey @day-lee ,

Any updates on the issue?

**Comment by day-lee** [comment]
Hi, @PriteshKiri 

 When I click on the `+Testimonial` button on https://reactplay.io/testimonials page, it doesn't show me the modal page, however, I can see it locally without problem.
When I look at the network tab, I can see some token problem. 

I think I can reuse the modal component and simply add a button to trigger it on the rending page. However, I wonder if it would work fine and show up on the page when deployed or not. Can I have your opinion please? 
Thanks,

![image](https://github.com/user-attachments/assets/7de1a400-4b6b-4277-af45-053d47e316eb)

**Comment by nilaygit-10721** [comment]
This issue has not been resolved till now.Can I work on this issue?

**Comment by PriteshKiri** [comment]
@Shivam-Katare @Sachin-chaurasiya can you please check the suggestion by @day-lee ?

**Comment by PriteshKiri** [comment]
@nilaygit-10721 the issue is under discussion. Can you please checkout other issues?

**Comment by Sachin-chaurasiya** [comment]
> Hi, @PriteshKiri
> 
> When I click on the `+Testimonial` button on https://reactplay.io/testimonials page, it doesn't show me the modal page, however, I can see it locally without problem. When I look at the network tab, I can see some token problem.
> 
> I think I can reuse the modal component and simply add a button to trigger it on the rending page. However, I wonder if it would work fine and show up on the page when deployed or not. Can I have your opinion please? Thanks,
> 
> ![image](https://private-user-images.githubusercontent.com/73591588/376262199-7de1a400-4b6b-4277-af45-053d47e316eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzIxMjksIm5iZiI6MTczMDg3MTgyOSwicGF0aCI6Ii83MzU5MTU4OC8zNzYyNjIxOTktN2RlMWE0MDAtNGI2Yi00Mjc3LWFmNDUtMDUzZDQ3ZTMxNmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA1NDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYTFiOTZjYTQwNGE4OGQyOWIyZWRlYzU5Y2Y3ODNhNGE1YWRjMjIxMGUzZmYwNGUwMzlmNDZhZWJlZGYyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xlvTkVLB5UTEbBIY1WypWLbArRCPG7A3Zqo9RcllQlo)

Hey @day-lee, in order to add a testimonial, users need to authenticate via GitHub. When they click the `+Testimonial` button, we retrieve the user token from Nhost and then display the add testimonial page. However, I noticed that the URL `https://auth.nhost.run/v1/token` is failing, which is why the add testimonial page isn't rendering properly. cc: @priyankarpal can you check why `https://auth.nhost.run/v1/token` is failing on production?
