### ISSUE TITLE
Issue While Running Project Locally

### ISSUE THREAD

**Issue by vinaysanwal** [reactplay/react-play#1532]
### File Name

/src/plays/index.js

### Reason for Refactoring the Code

Issue While Running the Project Locally :

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue
- [X] I am a Hacktoberfest contributor

**Comment by Karna0005** [comment]
To solve the error, try to download the typescript versions which are in between 4.3.5 and 5.4.0 
for example: you can download typescript version 5.3.0

**Comment by Sachin-chaurasiya** [comment]
Hi @vinaysanwal, welcome to the community! Thank you for reporting the issue. It seems like it’s just a warning and not a critical error. Are you unable to run the project locally because of this? Could you please provide more details?

**Comment by hamzathul** [comment]
![Screenshot from 2024-10-05 12-28-44](https://github.com/user-attachments/assets/20569b7a-99e0-40f1-bf48-d7a5e1f3841e)

I am also facing some kind of issues while running the Project.

**Comment by Sachin-chaurasiya** [comment]
> ![Screenshot from 2024-10-05 12-28-44](https://github.com/user-attachments/assets/20569b7a-99e0-40f1-bf48-d7a5e1f3841e)
> 
> 
> 
> I am also facing some kind of issues while running the Project. 

@hamzathul , did you follow the project setup guide?

**Comment by vinaysanwal** [comment]
> > ![Screenshot from 2024-10-05 12-28-44](https://private-user-images.githubusercontent.com/83232962/373853287-20569b7a-99e0-40f1-bf48-d7a5e1f3841e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTM3NTksIm5iZiI6MTcyODI5MzQ1OSwicGF0aCI6Ii84MzIzMjk2Mi8zNzM4NTMyODctMjA1NjliN2EtOTllMC00MGYxLWJmNDgtZDdhNWUxZjM4NDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5MzA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NWY3ODQxZDJlMzhhNDUxMWE3OGEzNjg0Y2RjNTIyZGVjOWM4MDNmMjM4N2YwNjU2MjlhOGFiZjJmYzMzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7aH9hY5RQ3YqJ7aKP5kUnC7snf-YKnlAWD9KgfShDOM)
> > I am also facing some kind of issues while running the Project.
> 
> @hamzathul , did you follow the project setup guide?

**Comment by PriteshKiri** [comment]
Hey @vinaysanwal,

Can you please share the link to the docs that you followed?

**Comment by PriteshKiri** [comment]
Closing the issue because of lack of progress.
