### ISSUE TITLE
🐛 [Bug report]: Getting 502 Bad Gateway Error if we cancel the authorization

### ISSUE THREAD

**Issue by vinaysanwal** [reactplay/react-play#1538]
### Descrcibe the bug?

Getting 502 Bad Gateway Error if we cancel the authorization

### Steps to reproduce the bug?

1) Goto : https://reactplay.io/plays/priteshkiri/codenchill
2)Click on Like
<img width="1728" alt="Screenshot 2024-10-07 at 7 51 25 PM" src="https://github.com/user-attachments/assets/478a8f7d-f5a6-475d-901d-1b390df140d2">

3) It will give authorize to github popup
4)Cancel it 
<img width="1728" alt="Screenshot 2024-10-07 at 7 51 45 PM" src="https://github.com/user-attachments/assets/cfb5b1b0-485d-4a9e-8373-39d1efff2d16">

5)502 bad gateway error
<img width="1728" alt="Screenshot 2024-10-07 at 7 52 05 PM" src="https://github.com/user-attachments/assets/852f468c-3a7f-4850-bde7-8761ba6f8fe0">

### Expected behavior

if user cancel the authorization it should come back to the screen where user was previously

### Desktop (Please provide your system information)

Macos , chrome 

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
can you check once?

**Comment by tanishq-singh-2407** [comment]
can I work on this?

**Comment by PriteshKiri** [comment]
@priyankarpal the issue is still there. I just checked.

**Comment by tanishq-singh-2407** [comment]
Sorry instead of adding this comment here I accidentally added to another issue which I was part of.

I don't think the problem is from our side, its either backend or from nhost side.
Even nhost `cancel` button don't work as of now [check here](https://app.nhost.io/signin)

_Originally posted by @tanishq-singh-2407 in https://github.com/reactplay/react-play/issues/1540#issuecomment-2408613053_
