### ISSUE TITLE
✨ [Feature request]: Add the number badge to the comment icon

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#154]
**Is your feature request related to a problem? Please describe.**
Currently, each of the plays has a way to provide and view comments

![image](https://user-images.githubusercontent.com/3633137/167126180-ae6f761a-0f02-4eee-97a2-518243c8e5c9.png)

It will be great if the icon indicates the number of comments a play has.

**Describe the solution you'd like**
The solution is to use the GitHub GraphQL API to fetch the number of discussions for a discussion id and show as a badge. The JSX part of the code is already there but commented.

**Describe alternatives you've considered**
If we can't show the number, let us at least indicate if the play has a comment or not with a visual clue.

**Additional context**
Read more about the comment system implementation from here: https://blog.greenroots.info/comment-system-using-react-and-github-discussions

**Comment by ashutoshdhande** [comment]
@atapas how the number of comments should be displayed?

As on hovering the icon or to the side of icon (this will look odd in my opinion).

**Comment by atapas** [comment]
> @atapas how the number of comments should be displayed?
> 
> As on hovering the icon or to the side of icon (this will look odd in my opinion).

That part of the code of showing the number is already in place. You can uncomment it in the jsx file and see. It appears like a badge on the icon.

Next, part of the issue, we need to figure out how to get the comment count for a play.

**Comment by k3yss** [comment]
I am pretty new to React, but I think I can work on this issue, can someone assign it to me?
