### ISSUE TITLE
🐛 [Bug report]: Like buttion is not working

### ISSUE THREAD

**Issue by priyankarpal** [reactplay/react-play#1540]
### Descrcibe the bug?

After completing authentication using GitHub, when you open any play and click on the like button, the like button does not work.

### Steps to reproduce the bug?

.

### Expected behavior

something is wrong with the like button 

### Desktop (Please provide your system information)

- kali linux
- Brave

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanishq-singh-2407** [comment]
can I work on this?

**Comment by priyankarpal** [comment]
> can I work on this?

sure assigned

**Comment by KrishDave1** [comment]
Can you assign this issue to me? @priyankarpal

**Comment by priyankarpal** [comment]
> Can you assign this issue to me? @priyankarpal

already assigned to someone

**Comment by tanishq-singh-2407** [comment]
I don't think the problem is from our side, its either backend or from nhost side.
Even nhost `cancel` button don't work as of now [check here](https://app.nhost.io/signin)

**Comment by priyankarpal** [comment]
> I don't think the problem is from our side, its either backend or from nhost side. Even nhost `cancel` button don't work as of now [check here](https://app.nhost.io/signin)

@atapas please check

**Comment by tanishq-singh-2407** [comment]
> I don't think the problem is from our side, its either backend or from nhost side. Even nhost `cancel` button don't work as of now [check here](https://app.nhost.io/signin)

Ignore this please,

Here issue is not there when I checked.

**Comment by PriteshKiri** [comment]
@tanishq-singh-2407 are you still working on this like issue?
