### ISSUE TITLE
[Refactor] I want to refactor and add js docs comment inside common/utils methods exclude commonUtils.js

### ISSUE THREAD

**Issue by saddamhr** [reactplay/react-play#1550]
### File Name

src/common/utils

### General reasons:
- Readability: The code lacks readability due to non-descriptive variable names and a lack of clear structure.
- Maintainability: The code is not easily maintainable, as changing the date formatting would require modifications in multiple places.
- Performance: The code is not optimized for performance, with potentially costly operations like splitting the date string into an array and incorrect date object instantiation.

Individual file reasons:
- **In `coverImageUtil.js` will add the following**
  - error handling
  - js docs comment missing
 - **In `fakeUser.js` will add the following**
    - Avoid unnecessary imports: Since faker.image.urlLoremFlickr is deprecated and faker.image provides other image generators, I replaced it with faker.image.nature() for a cleaner solution.
    - Removed redundant Array.from(Array()): Simplified array generation using Array(THRESHOLD).fill(null).map(...).
    - js docs comment
  - **In `formatCount.ts` will add the following**
      - DRY (Don't Repeat Yourself): Avoids repetitive parsing of the viewCount.
      - Early return in formatViewCount: Added a return for cases where the viewCount is less than 1,000.
      - Optimized handling for duration: Simplified the construction of the formatted time string.
      - js docs comment

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue
- [X] I am a Hacktoberfest contributor

**Comment by priyankarpal** [comment]
sure assigned to you

**Comment by PriteshKiri** [comment]
Thanks for your contribution @saddamhr 🙌
