### ISSUE TITLE
[Refactor] I want to refactor `constants/index.js` file

### ISSUE THREAD

**Issue by saddamhr** [reactplay/react-play#1551]
### File Name

src/constants/index.js

### Reason for Refactoring the Code

- Will add `Object.freeze({})` the best way to declare constant in js
- Will Improve variable naming

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue
- [X] I am a Hacktoberfest contributor

**Comment by priyankarpal** [comment]
sure assigned to you

**Comment by PriteshKiri** [comment]
Hey @saddamhr!

The PR of this issue will be counted under the NINJA CHALLENGE. Join our [discord community](https://discord.gg/9nFHKdfWMx) for more details.

**Comment by priyankarpal** [comment]
any updates @saddamhr

**Comment by saddamhr** [comment]
> any updates @saddamhr

I'm working on it.
