### ISSUE TITLE
✨ [Feature request]: Improve UI of the play name Typing Speed Test

### ISSUE THREAD

**Issue by BayajidAlam** [reactplay/react-play#1552]
### Is your feature request related to a problem? Please describe.

![screencapture-reactplay-io-plays-makdoom-typing-speed-test-2024-10-12-17_26_04](https://github.com/user-attachments/assets/5ef13e51-49dd-4421-ad20-bc5457f0a1eb)
This ui is not looking that good because of the typing section are in bottom. User has to scroll down to type.

### Describe the solution you'd like.

I want to re design it like this picture:
![Screenshot from 2024-10-12 17-30-10](https://github.com/user-attachments/assets/42ab488b-f909-40e6-aa63-6c2cb7e69371)

### Describe alternatives you've considered.

I have one more alternative like, keeping the same shape and improve it following way:
![Screenshot from 2024-10-12 17-31-27](https://github.com/user-attachments/assets/688e03db-a0e7-4793-b924-5183c111d226)

### Screenshot / Screenshare

![Screenshot from 2024-10-12 17-30-10](https://github.com/user-attachments/assets/42ab488b-f909-40e6-aa63-6c2cb7e69371)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhi9ab** [comment]
I could help fix this issue. Could you assign this to me ?

**Comment by abhi9ab** [comment]
I could help fix this issue. Could you assign this to me ?

**Comment by BayajidAlam** [comment]
Please assign me, I have create this issue to contribute

**Comment by PriteshKiri** [comment]
Thanks for your contribution @BayajidAlam 🙌
