### ISSUE TITLE
[Add a Play]: Daily journal

### ISSUE THREAD

**Issue by GhadaRV** [reactplay/react-play#1556]
### What's the Play about?

This play is about writing daily entries, categorising them by mood or topic, and reviewing past entries.

### What ReactJS concept will be used to create this play?

Functional components, hooks, ..

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PriteshKiri** [comment]
Hey @GhadaRV,

Thanks for contributing to Reactplay. Looking forward to your play 🙌

**Comment by PriteshKiri** [comment]
Hey @GhadaRV!

The PR of this issue will be counted under the NINJA CHALLENGE. Join our [discord community](https://discord.gg/9nFHKdfWMx) for more details.

**Comment by priyankarpal** [comment]
any updates? @GhadaRV

**Comment by GhadaRV** [comment]
Hello,
Just finishing up some styling and will be submitting it soon.
