### ISSUE TITLE
✨ [Feature request]: I want to improve the UI of play video preview

### ISSUE THREAD

**Issue by BayajidAlam** [reactplay/react-play#1559]
### Is your feature request related to a problem? Please describe.

- No loading state
- This search bar is not  ooking that good
- There is no gap in two video
- Right side has extra space and video is located in left

![WhatsApp Image 2024-10-15 at 1 16 30 PM](https://github.com/user-attachments/assets/809e872a-cb53-4752-9a54-a7476981f17a)

### Describe the solution you'd like.

I can solve all of the given problem

### Describe alternatives you've considered.

Not necessary I think

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PriteshKiri** [comment]
Hey @BayajidAlam!

Have assigned you the issue. We are looking forward to your contribution 🙌 

The PR of this issue will be counted under the NINJA CHALLENGE. Join our [discord community](https://discord.gg/9nFHKdfWMx) for more details.

**Comment by BayajidAlam** [comment]
@PriteshKiri Thanks for assigning me the issue! I’m excited to contribute 🎉. Just a quick note – I’m participating in Hacktoberfest, so I’d like this PR to count towards that, if possible. Could you please confirm if that’s okay?

Looking forward to contributing!

**Comment by PriteshKiri** [comment]
Yes @BayajidAlam!!

PR for this issue will be counted under hacktoberfest.
