### ISSUE TITLE
✨ [Feature request]: Improve PlayHeader

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1562]
### Is your feature request related to a problem? Please describe.

1. When there is too much information in the play header, like long descriptions and not many tags, it becomes too large. The description stretches across the header, causing content to shift too far to the left. This creates layout problems where important elements, such as the dates are collapsing or overlapping.

![image](https://github.com/user-attachments/assets/ebdcdcd6-ae3f-42ed-aedb-bf3c95ce6e62)

2. When the play header contains too much information, such as tags and a lengthy description, the height of the header increases significantly. This reduces the available space for viewing the actual play content.

![image](https://github.com/user-attachments/assets/404036c5-d746-4ced-ae8c-0b021f770e80)

### Describe the solution you'd like.

For the first issue, we could set a maximum width for the description area in the play header.

For the second issue, we could add a "Collapse" button that folds the entire play header, leaving only essential elements like the back button, title, and icons (like/edit/share). When clicked, the button would toggle the full header view, allowing users to expand or collapse it based on their preference, ensuring they can focus on the play content.

![image](https://github.com/user-attachments/assets/070689b8-0f80-4a76-a3d9-a786627e4151)

**NOTE**: Feel free to suggest any other ideas you believe are effective. The above solutions are just suggestions.

### Describe alternatives you've considered.

No alternative.

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [X] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrhat05** [comment]
since the tags and date will occupy constant space we can fix its width and leave the description responsive also for second issue as you said collapse we implement it and also increase the necessary margin for good visibility

**Comment by priyankarpal** [comment]
> since the tags and date will occupy constant space we can fix its width and leave the description responsive also for second issue as you said collapse we implement it and also increase the necessary margin for good visibility

do you want to work on it?

**Comment by joshua-jinu** [comment]
Hey @Shivam-Katare, I would like to work on this, can i be assigned

**Comment by priyankarpal** [comment]
> Hey @Shivam-Katare, I would like to work on this, can i be assigned

assigned to you
