### ISSUE TITLE
[Play] Currency Exchange template using Tailwindcss and react

### ISSUE THREAD

**Issue by tejinder-sharma** [reactplay/react-play#164]
Hello,

I am Tejinder Sharma want to contribute to open-source projects.

So I thought of making a website template using Tailwincss and ReactJS.

Will it come under the Project section? If yes, can I contribute?

Thanks,

Tejinder Sharma

**Comment by atapas** [comment]
@tejinder-sharma Welcome!!

Please update the issue details with the entire details of the play. Like what it is going to be etc.

Please get started with it by creating a branch. If you face any problems, feel free to open a discussion from here(under the QA): https://github.com/atapas/react-play/discussions

**Comment by tejinder-sharma** [comment]
Thank You Tapas for replying,

I am working on a Currency Exchange template using Tailwindcss and react. I will update you soon after the completion of the project.

**Comment by atapas** [comment]
@tejinder-sharma TailwindCSS is in now. You can submit this play :)

**Comment by tejinder-sharma** [comment]
Thank you Tapas, I am going to make it soon.

**Comment by atapas** [comment]
@tejinder-sharma Are you planning this one?
