### ISSUE TITLE
Add Support for TailwindCSS to ReactPlay

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#165]
We have decided to add support for TailwindCSS and SASS.

### Discussed in https://github.com/atapas/react-play/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **joshi-kaushal** April 20, 2022</sup>
Hello,

As we go ahead and get contributions from people around the globe, I think we should have a standard set for styling.

Tailwind CSS seems like a great option for me since it is widely accepted, has a minimal learning curve, and most importantly the styling is standardized. 

I can take the whole responsibility of integrating our existing app with Tailwind.</div>

**Comment by atapas** [comment]
I see this play merge will add the SASS Support. So this issue needs to take care of Tailwind alone.


https://github.com/atapas/react-play/pull/163/files

**Comment by vasantisuthar** [comment]
Can I add tailwind support to my react play, so that it can be merged. As I have already did that 😄

**Comment by atapas** [comment]
> Can I add tailwind support to my react play, so that it can be merged. As I have already did that 😄

I would say go ahead and convert your play to support Tailwind. If someone picks this issue in isolation and just adds support, that will be even faster as the scope of the changes will be limited.

**Comment by nirban256** [comment]
Hello @atapas Sir, I would like to work on this issue

**Comment by atapas** [comment]
> Hello @atapas Sir, I would like to work on this issue

All yours.

**Comment by atapas** [comment]
Hello @vasantisuthar Could you please review the PR once?

https://github.com/atapas/react-play/pull/183
