### ISSUE TITLE
[Add a Play]: QR Code Generator

### ISSUE THREAD

**Issue by murtuzaalisurti** [reactplay/react-play#175]
## What's the Play about?
A simple QR code generator for anything such as text, url, etc. Also, with an option to download the QR code! Check out a [similar web app](https://qr-codes.vercel.app) (PWA) made by me using Vanilla JS.

## What ReactJS concept will be used to create this play?
Nothing new, just some basic React JS concepts.

## Are you willing to take it up for implementation?
Yes

**Comment by atapas** [comment]
@murtuzaalisurti When are you planning this one?

**Comment by murtuzaalisurti** [comment]
> @murtuzaalisurti When are you planning this one?

one or two weeks

**Comment by Vipul2504** [comment]
I have to make this in react? or vanilla Js?

**Comment by atapas** [comment]
> I have to make this in react? or vanilla Js?

React

**Comment by murtuzaalisurti** [comment]
@atapas I will work on this play now!

**Comment by atapas** [comment]
> @atapas I will work on this play now!

Collaborate with @koustov on how to create a play using new framework. You will beta test it while doing that. Thanks!

**Comment by murtuzaalisurti** [comment]
Play creation done! 
Now adding the play to the repo using the new workflow. ✅
