### ISSUE TITLE
✨ [Feature request]: Establish a color palette for this application

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#191]
**Is your feature request related to a problem? Please describe.**
It's not a problem

**Describe the solution you'd like**
It would be better to create a common color palette for this application. It's for better usage and consistency across the app. However, this doesn't restrict the players to add their own during play creation. 
The idea is to make a suggestive palette, not a `constraint`. 
One can still create a play beyond the suggested color palette as long as he/she feels so.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Vipul2504** [comment]
hey I wanted to contribute to this issue

**Comment by atapas** [comment]
> Hey, I am not able to install a dependency. When I run npm install in the root folder it gives me error

What error do you get?

**Comment by Vipul2504** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-play@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from react-shimmer-effect@1.0.9
npm ERR!   react-shimmer-effect@"^1.0.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ADMIN\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by atapas** [comment]
@Vipul2504 

Please try `npm install --legacy-peer-deps` if it helps you. Thanks!

**Comment by atapas** [comment]
@Vipul2504 Are you still working on this one?

**Comment by jainPrajwal** [comment]
Hey @atapas , its the first time I am contributing.. would love to take up this task!
Do let me know. Thanks..!

**Comment by iamkelv** [comment]
@atapas can you assign me this issue? I will like to work on it

**Comment by Nwakaego-Ego** [comment]
Hi Atapas

If this issue is still open, please assign it to me
