### ISSUE TITLE
🐛 [Bug report]: Console log Statement No Need on Production

### ISSUE THREAD

**Issue by Rafat97** [reactplay/react-play#194]
**Describe the bug**
I visited website and checking the developer console. I saw there is a lots of `console.log` statement. Example screenshot given bellow. In production I think, we don't need those `console` statement. 

**To Reproduce**
1. Go to 'https://www.reactplay.io/'
2. Open Developer Console

**Expected behavior**
No need console statement on production build.  

**Screenshots**
![image](https://user-images.githubusercontent.com/21246862/169021346-a386ba76-cc4b-4494-9b74-370a7d44b8a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome,
 - Version 101.0.4951.67

**Comment by atapas** [comment]
Agree we should clear them on production. Do you have a strategy and want to work on this issue? @Rafat97

**Comment by Rafat97** [comment]
Mainly I use this code in root file. Where `ReactDOM.render` was used. 

```js
/** Removing console.log in production */
if (process.env.NODE_ENV !== "development") {
  console.log = () => {};
  console.error = () => {};
  console.warn = () => {};
  console.clear();
  console.disableYellowBox = true;
}
```

**Comment by atapas** [comment]
@Rafat97 Sounds good. Do you want to give it a try in ReactPlay? I can assign the issue to you then.

Btw... I usually leave the errors in production to log. How about that?

**Comment by Rafat97** [comment]
> @Rafat97 Sounds good. Do you want to give it a try in ReactPlay? I can assign the issue to you then.
> 
> Btw... I usually leave the errors in production to log. How about that?

We just need to remove `console.error = () => {}`. 

Also. I am glad if I can contribute anything. You can add  me into this issue. I will add the given code into `index.js` file -
```
if (process.env.NODE_ENV !== "development") {
  console.log = () => {};
  console.debug = () => {};
  console.info = () => {};
  console.clear();
  console.disableYellowBox = true;
}
```

Thank you @atapas

**Comment by atapas** [comment]
Thank you @Rafat97 The issue is yours. You can test it with a production-like preview build after you open the PR. Thanks!

**Comment by Rafat97** [comment]
@atapas, Can I use `docker-compose` ?

**Comment by atapas** [comment]
> @atapas, Can I use `docker-compose` ?

The app doesn't have the containarize support yet. It is mostly driven by the dev build and deployed on vercel.

**Comment by Rafat97** [comment]
Will I create `docker-compose` file for both production & development environment?

**Comment by atapas** [comment]
> Will I create `docker-compose` file for both production & development environment?

Ok

**Comment by Rafat97** [comment]
@atapas . 
Check https://github.com/reactplay/react-play/pull/271 PR. 
I fixed it. 

If there is any issue let me know. 
Thank you.
