### ISSUE TITLE
✨ [Feature request]: If a play doesn't have a blog, link it to the Readme

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#200]
**Is your feature request related to a problem? Please describe.**
Each of the play has a read me file that is supposed to explain the technical details of the play like what it is, how it was built, etc. The ReactPlay should check if a play creator supplied a blog link for a play. In case it is empty, the link can be to the Readme file.

**Describe the solution you'd like**
Each of the play has a read me file that is supposed to explain the technical details of the play like what it is, how it was built, etc. The ReactPlay should check if a play creator supplied a blog link for a play. In case it is empty, the link can be to the Readme file.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ryzncodes** [comment]
Hello! Would it be possible for me to contribute to this issue? This would be my first open source contribution.

**Comment by atapas** [comment]
> Hello! Would it be possible for me to contribute to this issue? This would be my first open source contribution.

Surely possible. Assigned to you. Please feel free to ask if you need help: https://github.com/atapas/react-play/discussions/categories/q-a

**Comment by Programming-School-Pro-Coding** [comment]
Good Idea

**Comment by atapas** [comment]
Hi @ryzncodes Are you still on it?

**Comment by Programming-School-Pro-Coding** [comment]
> Hi @ryzncodes Are you still on it?

Hey Sir

Assign me

**Comment by Programming-School-Pro-Coding** [comment]
I finished the Code now

**Comment by atapas** [comment]
> I finished the Code now

@Programming-School-Pro-Coding Where?

**Comment by Programming-School-Pro-Coding** [comment]
> > I finished the Code now
> 
> @Programming-School-Pro-Coding Where?

For this issue: #200

**Comment by Programming-School-Pro-Coding** [comment]
> > I finished the Code now
> 
> @Programming-School-Pro-Coding Where?

I don't understand you

**Comment by atapas** [comment]
> > > I finished the Code now
> > 
> > 
> > @Programming-School-Pro-Coding Where?
> 
> I don't understand you

Where is the code? I mean Pull Request?

**Comment by Programming-School-Pro-Coding** [comment]
> > > > I finished the Code now
> > > 
> > > 
> > > @Programming-School-Pro-Coding Where?
> > 
> > 
> > I don't understand you
> 
> Where is the code? I mean Pull Request?

Confirm my pull request to create another one

**Comment by atapas** [comment]
> > > > > I finished the Code now
> > > > 
> > > > 
> > > > @Programming-School-Pro-Coding Where?
> > > 
> > > 
> > > I don't understand you
> > 
> > 
> > Where is the code? I mean Pull Request?
> 
> Confirm my pull request to create another one

No, they are independent. You can create a new branch from the main and start on this one without waiting for another one to merge. Each issue should have new branch and new PR.

**Comment by Programming-School-Pro-Coding** [comment]
> > > > > > I finished the Code now
> > > > > 
> > > > > 
> > > > > @Programming-School-Pro-Coding Where?
> > > > 
> > > > 
> > > > I don't understand you
> > > 
> > > 
> > > Where is the code? I mean Pull Request?
> > 
> > 
> > Confirm my pull request to create another one
> 
> No, they are independent. You can create a new branch from the main and start on this one without waiting for another one to merge. Each issue should have new branch and new PR.

Done

**Comment by Programming-School-Pro-Coding** [comment]
> > > > > > I finished the Code now
> > > > > 
> > > > > 
> > > > > @Programming-School-Pro-Coding Where?
> > > > 
> > > > 
> > > > I don't understand you
> > > 
> > > 
> > > Where is the code? I mean Pull Request?
> > 
> > 
> > Confirm my pull request to create another one
> 
> No, they are independent. You can create a new branch from the main and start on this one without waiting for another one to merge. Each issue should have new branch and new PR.

The Pull Request #246

**Comment by Programming-School-Pro-Coding** [comment]
> > > > > > I finished the Code now
> > > > > 
> > > > > 
> > > > > @Programming-School-Pro-Coding Where?
> > > > 
> > > > 
> > > > I don't understand you
> > > 
> > > 
> > > Where is the code? I mean Pull Request?
> > 
> > 
> > Confirm my pull request to create another one
> 
> No, they are independent. You can create a new branch from the main and start on this one without waiting for another one to merge. Each issue should have new branch and new PR.

The Pull Request: #246
