### ISSUE TITLE
✨ [Feature request]: Play statistics: View Count

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#218]
**Describe the solution you'd like**
One of the best ways to show play engagement is through "view count". Good to have the stat implemented. Later point of time this data can be used for sorting mechanism

**Describe alternatives you've considered**
NA

**Additional context**
Need a UI suggestion before starting the imeplementation.

**Comment by atapas** [comment]
Its a good one. So prereq is to get the meta in DB?

**Comment by shrilakshmishastry** [comment]
@atapas me and @vasantisuthar would love to take it up, as it's a part of what we are building

**Comment by atapas** [comment]
Sure, take it up
