### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by Asterisk-z** [reactplay/react-play#232]
create the agreed ui for password generator
![passwordui](https://user-images.githubusercontent.com/56372709/170171005-ebc4a5bf-a039-48bd-9f76-e2a0576dd154.PNG)

**Comment by atapas** [comment]
@Asterisk-z Please go ahead and create the PR. I am assuming you are doing the suggested changes.

**Comment by atapas** [comment]
> @Asterisk-z Please go ahead and create the PR. I am assuming you are doing the suggested changes.

Hi @Asterisk-z please confirm if you will be implementing it.

**Comment by Asterisk-z** [comment]
Yes @atapas

**Comment by Asterisk-z** [comment]
PR co

> Yes @atapas

PR Coming up soon
