### ISSUE TITLE
✨ [Feature request]: Add a sponsor/support option in the header

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#235]
**Is your feature request related to a problem? Please describe.**
No, it is a feature.

We can have an option for visitors to show their support by,

- Sponsoring(We can link to GitHub Sponsor)
- Sharing about ReactPlay on Twitter

**Describe the solution you'd like**
An icon that shows "Support/Sponsor". Click on it a "Callout" comes with the option to Sponsor link and Share on Twitter. A few lines of motivating text also will be good.

First, we need to settle on the design.

**Describe alternatives you've considered**
Open to alternate thoughts

**Additional context**
None

**Comment by vasantisuthar** [comment]
This is a nice idea, people will get more engaged with react-play showing their support.

**Comment by nirmalkc** [comment]
Here is a proposal for the support of the sponsor.

![image](https://user-images.githubusercontent.com/6359059/175309970-d8f674da-3e9c-4f13-9604-eea7b1b5bc93.png)

@atapas , please suggest appropriate text for both the button labels as well as the description text.

**Comment by Programming-School-Pro-Coding** [comment]
> Here is a proposal for the support of the sponsor.
> 
> ![image](https://user-images.githubusercontent.com/6359059/175309970-d8f674da-3e9c-4f13-9604-eea7b1b5bc93.png)
> 
> @atapas , please suggest appropriate text for both the button labels as well as the description text.

Nice

**Comment by atapas** [comment]
This is done.
