### ISSUE TITLE
✨ [Feature request]: Fetch play list from data store

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#236]
**Is your feature request related to a problem? Please describe.**

It is a feature. Currently, the play metadata is being fetched from the JSON file. It has to move to the back-end data store.

**Describe the solution you'd like**
- Setup data store
- Insert play records
- Modify the UI code to fetch the data from data store

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Programming-School-Pro-Coding** [comment]
What Data store do you want to use ?

**Comment by Programming-School-Pro-Coding** [comment]
Sanity or MongoDB

**Comment by Programming-School-Pro-Coding** [comment]
> > Sanity or MongoDB
> 
> NHost

Ok, Assign me too

**Comment by Programming-School-Pro-Coding** [comment]
> > Sanity or MongoDB
> 
> NHost

Do you have a team in NHost ?

**Comment by Programming-School-Pro-Coding** [comment]
> > Sanity or MongoDB
> 
> NHost
Why do you want to use NHost ?

**Comment by atapas** [comment]
> > > Sanity or MongoDB
> > 
> > 
> > NHost
> 
> Ok, Assign me too

There is someone working on it already. Please help us with the other issues. Thanks!

**Comment by Programming-School-Pro-Coding** [comment]
> 

Ok

**Comment by murtuzaalisurti** [comment]
@atapas should we update this?

**Comment by atapas** [comment]
> @atapas should we update this?

No, I have created this issue to consume the query you have created. Will get on it this Saturday. You can continue to build the mutation queries and push them in the back-end project.
