### ISSUE TITLE
Filtering: Create multi selector for selecting levels, creator, and Tags

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#24]
**Is your feature request related to a problem? Please describe.**

Right now, we can select only a combination of 1 level, 1 creator, and 1 Tag at a time. We need to enable users to select multiple values from each of the criteria to form a filtering combination.

**Comment by shrilakshmishastry** [comment]
@atapas I would love to give it a try for this

**Comment by atapas** [comment]
We need to start a discussion on this to finalize the design for it.

**Comment by shrilakshmishastry** [comment]
Shall I start a new discussion in the discussion section about it? referring Nirmal?

**Comment by atapas** [comment]
> Shall I start a new discussion in the discussion section about it? referring Nirmal?

You can start a discussion with initial thoughts of solving it. Some handwritten sketch will help too.

**Comment by supminn** [comment]
Hi @shrilakshmishastry 
Have you been able to get this feature implemented? If not, can I try to get it implemented?

**Comment by shrilakshmishastry** [comment]
Please go ahead

**Comment by Sachin-chaurasiya** [comment]
@supminn , Assigned to you!

**Comment by supminn** [comment]
While working on this issue, I observed that the support for adding `clause` to children `conditions` is not available on https://github.com/koustov/json-graphql-parser
I have raised an [issue](https://github.com/koustov/json-graphql-parser/issues/5) for this.

cc: @koustov
