### ISSUE TITLE
✨ [Feature request]: Using vite instead of webpack or swc with webpack

### ISSUE THREAD

**Issue by sidiDev** [reactplay/react-play#242]
**Is your feature request related to a problem? Please describe.**

When I started creating a play, I was shocked that React play is so slow, and this is a big and big problem, I spent hours trying to build a play, because the development experience was so bad, what I mean is that when I run this command "npm run start", it's takes longer than expected, and sometime I turn off my laptop and turn it on to speed up the running of the app. 

**Describe the solution you'd like**
The solution that I highly recommend is to use [vite](https://vitejs.dev/), or [swc](https://swc.rs/) with webpack.

**Comment by atapas** [comment]
Thanks for the feedback @sidiDev. Just wanted to check if you want to pick it up and try improving?

**Comment by sidiDev** [comment]
Yes of course, I'm happy to work on improving development experience of React play.

**Comment by atapas** [comment]
> Yes of course @atapas , I'm happy to work on improving development experience of React play.

Sure thing.

**Comment by senali-d** [comment]
@atapas I love to work on this

**Comment by ijayhub** [comment]
@senali-d  hi are  you working on it?

**Comment by senali-d** [comment]
I didn't get time to work on this. If you interested on this please go ahead.

**Comment by ijayhub** [comment]
Good morning, okay...

**Comment by fluentmoheshwar** [comment]
Can I work on it?
