### ISSUE TITLE
🐛 [Bug report]: Add Readme.md file for all the missing Plays!

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#248]
**Describe the bug**
Some of the plays missing `readme.md` files.

These plays were created before the automatics Readme file generation. Hence the readme is missing. Please add readme files.

1. why-react
2. clock
3. data-time-counter
4. movies
5. org-tree
6. counter

![image](https://user-images.githubusercontent.com/3633137/170991357-13ac3e48-fc86-4d2f-96bb-2c37561f7e26.png)

**To Reproduce**

Go to the play folder of all the plays mentioned above, and check.

**Expected behavior**
 Readme should be added.

**Comment by Programming-School-Pro-Coding** [comment]
@atapas This is your play

**Comment by atapas** [comment]
> @atapas This is your play

Please file issues with proper descriptions

**Comment by Programming-School-Pro-Coding** [comment]
> > @atapas This is your play
> 
> Please file issues with proper descriptions

I don't understand you

**Comment by Programming-School-Pro-Coding** [comment]
A List of All the plays that don't have any readme file: 
1. clock
2. counter
3. data-time-counter
4. movies
5. org-tree
6. why-react

**Comment by atapas** [comment]
@Programming-School-Pro-Coding Are you taking this up?

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding Are you taking this up?

Do you want from me to add the readme files ?

I think you want the creators of these plays create the readme file of its play

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding Are you taking this up?

I will take it up now

 don't worry i will finish it in minutes

**Comment by Programming-School-Pro-Coding** [comment]
@atapas Please describe why-react play because i don't have any description for it

**Comment by Programming-School-Pro-Coding** [comment]
#251

**Comment by Programming-School-Pro-Coding** [comment]
@atapas I don't have the role to assign it to you please assign yourself
