### ISSUE TITLE
✨ [Feature request]: Create A Repositories for all these templates

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#256]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create A New Repository in the organization for each template to be easy to clone.
Each Play should have a repository in this organization

**Additional context**

I am happy to work on this

**Comment by atapas** [comment]
Please provide more details about this. Not very clear on it.

**Comment by Programming-School-Pro-Coding** [comment]
> Please provide more details about this. Not very clear on it.

Done

**Comment by atapas** [comment]
@koustov is working on the design of it already. Stay tuned to know more about it next week.
