### ISSUE TITLE
[Add a Play]: Calculator using React

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#257]
Thank You! 

## What's the Play about?
A Calculator using React JS, Hooks, JSX

## What ReactJS concept will be used to create this play?
Hooks

## Are you willing to take it up for implementation?
Yes

**Comment by Programming-School-Pro-Coding** [comment]
#254

**Comment by atapas** [comment]
> Thank You!
> 
> ## What's the Play about?
> ## What ReactJS concept will be used to create this play?
> ## Are you willing to take it up for implementation?

Add all the details plz.
