### ISSUE TITLE
✨ [Feature request]: Common notification/alert mechanism

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#274]
**Is your feature request related to a problem? Please describe.**
Plays would need to add notification of any kind for better interaction with the player. The idea is to have a base toast/modal/popup/inline alert that can be used by all plays for more intuitive interaction with the user.

**Describe the solution you'd like**
A common notification/alert mechanism would be helpful here. Create a hook that will be accessible from all the plays.
Need UI design first. 
e.g.: [react-toastify](https://www.npmjs.com/package/react-toastify)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Programming-School-Pro-Coding** [comment]
Hi Sir

Please tell me more because i don't get you

**Comment by Programming-School-Pro-Coding** [comment]
> **Is your feature request related to a problem? Please describe.** Plays would need to add notification of any kind for better interaction with the player.
> 
> **Describe the solution you'd like** A common notification mechanism would be helpful here. Create a hook that will be accessible from all the plays. Need UI design first.
> 
> **Describe alternatives you've considered** NA
> 
> **Additional context** NA

How we will tell the player about the notification and what is the notification that we will ask him ?

**Comment by Programming-School-Pro-Coding** [comment]
> > **Is your feature request related to a problem? Please describe.** Plays would need to add notification of any kind for better interaction with the player.
> > **Describe the solution you'd like** A common notification mechanism would be helpful here. Create a hook that will be accessible from all the plays. Need UI design first.
> > **Describe alternatives you've considered** NA
> > **Additional context** NA
> 
> How we will tell the player about the notification and what is the notification that we will ask him ?

Can we use email ?

**Comment by koustov** [comment]
> > > **Is your feature request related to a problem? Please describe.** Plays would need to add notification of any kind for better interaction with the player.
> > > **Describe the solution you'd like** A common notification mechanism would be helpful here. Create a hook that will be accessible from all the plays. Need UI design first.
> > > **Describe alternatives you've considered** NA
> > > **Additional context** NA
> > 
> > 
> > How we will tell the player about the notification and what is the notification that we will ask him ?
> 
> Can we use email ?

Not really. Here I am looking for `on UI notification/alert`. BTW, I have updated the title and description for better understanding.
