### ISSUE TITLE
🐛 [Bug report]: Github API limit exceeded

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#275]
**Describe the bug**
If you are using the application for a while, the GH API limit will eventually exceed. This will cause empty names in the play thumbnail and other places.
![image](https://user-images.githubusercontent.com/7145967/172035108-f7cfe679-2482-4f1e-b857-99ede4bba107.png)

Note: 
- GH API limit is per IP based. So if I am getting this error means, it's just got exhausted for my public address.
- We can still live with an error message however the UI shouldn't show empty data
  ![image](https://user-images.githubusercontent.com/7145967/172035161-c6c9c998-a8ee-402d-aa8e-07aa544da82c.png)
- This is a tracking issue. It should get solved as the application meta-information moves toward DB

**To Reproduce**
Just traverse through the application for some time.

**Expected behavior**
UI shouldn't show empty information

**Screenshots**
Already attached

**Comment by atapas** [comment]
It gets renewed daily basis. So if you try it the next day, it will work again for several days.

Yes, i to fix but not alarming. Also if we use these calls authenticated way, we will get a better rate limit. So let's consider that too.

**Comment by koustov** [comment]
Yes, it's a temporary issue, and the authenticated user gets more limit. It's definitely not a high severity one. 
The idea is to just use the user name from play-meta when the git user name is not available.

**Comment by atapas** [comment]
This issue is no more relevant as we do not make any GitHub API calls to retrieve the user info like full name and image. Hence closing this issue.
