### ISSUE TITLE
✨ [Feature request]: Add a link to navigate to all plays

### ISSUE THREAD

**Issue by vasantisuthar** [reactplay/react-play#280]
Add a link to navigate to all plays when play is not found

<img width="960" alt="2022-06-05 (2)" src="https://user-images.githubusercontent.com/63599802/172048164-1f631814-f136-4f86-8bdb-6176c75e25b0.png">

It would be good if we add a text that will link to all the plays back when the play is not found.

I would like to work on this issue.

**Comment by Sachin-chaurasiya** [comment]
@vasantisuthar , One more thing we can do here is instead of `play not found `, we can say `play not found for {searchText}`.

**Comment by vasantisuthar** [comment]
There is already a React play home button at the top, we shall only include all plays button, what say @Sachin-chaurasiya @Programming-School-Pro-Coding

**Comment by atapas** [comment]
> There is already a React play home button at the top, we shall only include all plays button, what say @Sachin-chaurasiya @Programming-School-Pro-Coding

But you are already on the plays page when this message appears. How about that?

**Comment by Sachin-chaurasiya** [comment]
> @vasantisuthar , One more thing we can do here is instead of `play not found `, we can say `play not found for {searchText}`.

@atapas , Your thought on this.

**Comment by atapas** [comment]
@Sachin-chaurasiya 

I think we shouldn't overengineer this one. A reasonable fix to me is to enhance the message with the search text as you suggested. Can we get it done? I see the issue has been assigned to @vasantisuthar

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya 
> 
> I think we shouldn't overengineer this one. A reasonable fix to me is to enhance the message with the search text as you suggested. Can we get it done? I see the issue has been assigned to @vasantisuthar 

@atapas , Yes.

**Comment by vasantisuthar** [comment]
Okay so I can update the text message.

**Comment by atapas** [comment]
@vasantisuthar / @Sachin-chaurasiya this issue is around for a long time. Can any of you please take care?

**Comment by Sachin-chaurasiya** [comment]
> @vasantisuthar / @Sachin-chaurasiya this issue is around for a long time. Can any of you please take care?

Sure @atapas, @vasantisuthar let me know if you need any help on this.

**Comment by vasantisuthar** [comment]
@Sachin-chaurasiya does it really need to be modified, I guess we shouldn't now as the page looks clear to me.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya does it really need to be modified, I guess we shouldn't now as the page looks clear to me.

@vasantisuthar , we can do something like this.

![image](https://user-images.githubusercontent.com/59080942/182311960-a7c6ee37-c40f-4eb7-9b68-1e8c3f6ea7ea.png)

**Comment by vasantisuthar** [comment]
Cool I will do it, I tried to do it before but the search bar wasn't shown up on the browser, so waited for that.

**Comment by Sachin-chaurasiya** [comment]
> > @Sachin-chaurasiya does it really need to be modified, I guess we shouldn't now as the page looks clear to me.
> 
> @vasantisuthar , we can do something like this if there is a search term.
> 
> ![image](https://user-images.githubusercontent.com/59080942/182311960-a7c6ee37-c40f-4eb7-9b68-1e8c3f6ea7ea.png)

**Comment by vasantisuthar** [comment]
> Cool I will do it, I tried to do it before but the search bar wasn't shown up on the browser, so waited for that.

Will submit this on Sunday

**Comment by priyankarpal** [comment]
already added
