### ISSUE TITLE
[Play]: Fix React landing page style

### ISSUE THREAD

**Issue by sidiDev** [reactplay/react-play#281]
@atapas Hi! I fixed the problem, you can review the PR again, and please let me know if everything is ok.

### The broblem

Early feedback, the changes are impacting the basic styles like H1...H6, some links, etc of the platform and so why impacting the look of other plays. It could be, that you are using Tailwind underneath and that is probably bringing some resets for those element styles. Could you please check once?

_Originally posted by @atapas in https://github.com/reactplay/react-play/issues/241#issuecomment-1140648070_

**Comment by atapas** [comment]
@sidiDev 

FYI: https://github.com/reactplay/react-play/pull/241#issuecomment-1148397310

Closing the issue.
