### ISSUE TITLE
✨ [Feature request]: Live Playground

### ISSUE THREAD

**Issue by murtuzaalisurti** [reactplay/react-play#282]
**Is your feature request related to a problem? Please describe.**
I got feedback from many people to add a playground where people can actually experiment some stuff with react on an existing play or a new instance.

**Describe the solution you'd like**
A playground which will allow learners to experiment with a play's code in a live editor window. (open for discussion)

**Additional context**
For example, a codesandbox kind of thing or some kind of a live editor just to tweak some stuff and play around with it temporarily. 

Write your thoughts, suggestions and opinions below...

**Comment by atapas** [comment]
@murtuzaalisurti Lets discuss this as an "idea" first.

**Comment by murtuzaalisurti** [comment]
> @murtuzaalisurti Lets discuss this as an "idea" first.

yeah that sounds good
