### ISSUE TITLE
✨ [Feature request]: Add New Idea, Landing Page

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#283]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to add new idea 💡 for the plays.
This idea is Landing Page.

**Describe alternatives you've considered**

**Additional context**
I am happy to work on

**Comment by Programming-School-Pro-Coding** [comment]
#267

**Comment by Sachin-chaurasiya** [comment]
@Programming-School-Pro-Coding, Assigned to you.

**Comment by koustov** [comment]
@Programming-School-Pro-Coding I didn't get the idea of this play. Could you please elaborate a little more in the issue description?

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding I didn't get the idea of this play. Could you please elaborate a little more in the issue description?

Done.

**Comment by atapas** [comment]
We already have a dedicated page to add ideas. closing it.

**Comment by atapas** [comment]
Ok reopening as there is a pending PR

**Comment by atapas** [comment]
This is not needed as the PR is closed,
