### ISSUE TITLE
🐛 [Bug report]: Wrong route being highlighted

### ISSUE THREAD

**Issue by TejasShekar** [reactplay/react-play#284]
**Describe the bug**
In [this](https://reactplay.io/plays/dynamic-routes/:menu) play, the wrong route is being highlighted even though the route being shown in the URL is not the same as the highlighted tab in the play.

**To Reproduce**
1. Select Breakfast tab
2. Then toggle between the three tabs in any random manner. 
For ex, say you toggled the tabs in this way : breakfast -> dinner->lunch->breakfast->lunch->dinner->lunch
3. Now, when you hit the back button in the browser, the previous route was `/dinner` and this should highlight only the `dinner` tab in the app. But it highlights both `lunch` tab (wiz. the current route you were on before going back) and `dinner` tab ( wiz. the previous route) as well. This persists until the first route `/:menu`.
4. So, from whatever current tab you start going back from, it will stay highlighted till the end of routes for the app in the browser history.

**Expected behavior**
Only the correct tab as per the route being shown in the URL should be highlighted. 
For ex: if the URL has `/dinner` as the route, only the dinner tab should be highlighted and all other tabs should stay in their unselected/non-highlighted state.

**Screenshots**
![Screenshot 2022-06-05 232641](https://user-images.githubusercontent.com/68545229/172063878-467fcb84-74b3-40ae-8a2e-bf7eef58fd15.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Browser Version 102.0.1245.30

**Additional context**
Check the elements tab in the dev tools. 
You can see that the `active` class is being applied to the `lunch` tab even if the route is `/dinner`. Infact, when you go to the same route i.e. `/lunch` , the `active` class is being applied twice on the `NavLink`.

**Comment by Deepak8717** [comment]
@TejasShekar thank you brother for bringing it into light. I will work on it.

**Comment by TejasShekar** [comment]
@Deepak8717 You're welcome. Also add a correct Github link that redirects directly to your play folder in react-play repo.

**Comment by Deepak8717** [comment]
@TejasShekar , i did not understand. Care to explain ?

**Comment by TejasShekar** [comment]
> @TejasShekar , i did not understand. Care to explain ?
![Screenshot (158)](https://user-images.githubusercontent.com/68545229/172134849-73e7f1f8-7e31-4a06-a43b-73644acb595b.png)

**Comment by Deepak8717** [comment]
@TejasShekar thanks again.

**Comment by koustov** [comment]
Since this issue has been fixed with https://github.com/reactplay/react-play/pull/286, I am closing it.
