### ISSUE TITLE
✨ [Feature request]: Update the search bar in such a way that it listens to the keys of your keyboard

### ISSUE THREAD

**Issue by hasnainmakada-99** [reactplay/react-play#285]
**Is your feature request related to a problem? Please describe.**
Currently we have to use enter button in the search bar, The user enters the name of the play clicks on enter and then it finds out the particular play, How about we add a keyup listener (speaking as I've used in vanilla js) in the search bar so that whenever user release key on his keyboard the required search results appear automatically or else it will show play not found error if the play is not there

**Describe the solution you'd like**
I've not worked with react till now so I don't know how to implement a listener in react, but speaking from my vanilla JS point of view we can add an event listener to the input area of the search bar

**Describe alternatives you've considered**
No alternatives from my side

**Additional context**
If this feature is implemented successfully it reduces the complexity to click one more button on our keyboard which is enter :sweat_smile:

**Comment by Programming-School-Pro-Coding** [comment]
Hi Sir

Please tell me more information or an example

**Comment by hasnainmakada-99** [comment]
> Hi Sir
> 
> Please tell me more information or an example

If you've worked with Vanilla js there are several event listeners which listens to our computers keyboard so I am telling to implement the keyboard event listeners to our input of the search bar

**Comment by hasnainmakada-99** [comment]
> > > Hi Sir
> > > Please tell me more information or an example
> > 
> > 
> > If you've worked with Vanilla js there are several event listeners which listens to our computers keyboard so I am telling to implement the keyboard event listeners to our input of the search bar
> 
> Give me a reason

Means ?

**Comment by Programming-School-Pro-Coding** [comment]
> > > > Hi Sir
> > > > Please tell me more information or an example
> > > 
> > > 
> > > If you've worked with Vanilla js there are several event listeners which listens to our computers keyboard so I am telling to implement the keyboard event listeners to our input of the search bar
> > 
> > 
> > Give me a reason
> 
> Means ?

Why to listens to the keys of your keyboard

**Comment by hasnainmakada-99** [comment]
> > > > > Hi Sir
> > > > > Please tell me more information or an example
> > > > 
> > > > 
> > > > If you've worked with Vanilla js there are several event listeners which listens to our computers keyboard so I am telling to implement the keyboard event listeners to our input of the search bar
> > > 
> > > 
> > > Give me a reason
> > 
> > 
> > Means ?
> 
> Why to listens to the keys of your keyboard

if it will listens to the keys then it can be more search efficient for the users as well as the developers

**Comment by Programming-School-Pro-Coding** [comment]
> > > > > > Hi Sir
> > > > > > Please tell me more information or an example
> > > > > 
> > > > > 
> > > > > If you've worked with Vanilla js there are several event listeners which listens to our computers keyboard so I am telling to implement the keyboard event listeners to our input of the search bar
> > > > 
> > > > 
> > > > Give me a reason
> > > 
> > > 
> > > Means ?
> > 
> > 
> > Why to listens to the keys of your keyboard
> 
> if it will listens to the keys then it can be more search efficient for the users as well as the developers

Do you means it is searching while user is typing ?

**Comment by hasnainmakada-99** [comment]
> > > > > > > Hi Sir
> > > > > > > Please tell me more information or an example
> > > > > > 
> > > > > > 
> > > > > > If you've worked with Vanilla js there are several event listeners which listens to our computers keyboard so I am telling to implement the keyboard event listeners to our input of the search bar
> > > > > 
> > > > > 
> > > > > Give me a reason
> > > > 
> > > > 
> > > > Means ?
> > > 
> > > 
> > > Why to listens to the keys of your keyboard
> > 
> > 
> > if it will listens to the keys then it can be more search efficient for the users as well as the developers
> 
> Do you means it is searching while user is typing ?

exactly

**Comment by hasnainmakada-99** [comment]
So will you be able to solve this issue @Programming-School-Pro-Coding

**Comment by hasnainmakada-99** [comment]
> > So will you be able to solve this issue @Programming-School-Pro-Coding
> 
> I will try

I am assigning it to you

**Comment by Programming-School-Pro-Coding** [comment]
> > > So will you be able to solve this issue @Programming-School-Pro-Coding
> > 
> > 
> > I will try
> 
> I am assigning it to you

Ok

**Comment by Programming-School-Pro-Coding** [comment]
Hey @hasnainmakada-99 

I done it
