### ISSUE TITLE
✨ [Feature request]: Add new idea - Image Gallery

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/react-play#296]
I would like to add one play idea which is `Image Gallery`, this will be an intermediate play where the creator has to use a free API service like [Unsplash](https://unsplash.com/) to get the images and show them in a gallery view. 
They have to provide a search option for users to search images.

**Comment by Programming-School-Pro-Coding** [comment]
> I would like to add one play idea which is Image Gallery.

Create A New PR First

**Comment by Sachin-chaurasiya** [comment]
> > I would like to add one play idea which is Image Gallery.
> 
> Create A New PR First

@Programming-School-Pro-Coding, I think first we should create the issue and add a proper description then start working on it.
cc : @atapas

**Comment by Programming-School-Pro-Coding** [comment]
> > > I would like to add one play idea which is Image Gallery.
> > 
> > 
> > Create A New PR First
> 
> @Programming-School-Pro-Coding, I think first we should create the issue and add a proper description then start working on it. cc : @atapas

Ok
