### ISSUE TITLE
🐛 [Bug report]: Filter box appear on landing page of the application

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#302]
**Describe the bug**
The filter box appears on the application's landing page for a fraction and then vanishes. Refer screenshot

**To Reproduce**
1. Go to '[reactplay](https://reactplay.io/)'
2. Refresh the page

**Expected behavior**
The filter box should only appear when one navigates to [play](https://reactplay.io/plays) page

**Screenshots**
![image](https://user-images.githubusercontent.com/7145967/172668311-7959f707-b4df-438e-9229-12602f4bb36a.png)

**Comment by Programming-School-Pro-Coding** [comment]
Ok, Assign me
I will do it

**Comment by ShivamBhasin2002** [comment]
Hi is this issue resolved or can I work on it?

**Comment by ShivamBhasin2002** [comment]
hey @atapas @koustov can u guide me on out of the following route on which of the routes should the search and filter box be visible?
![image](https://user-images.githubusercontent.com/57500840/175491290-1b4c2da2-6af1-41e6-ad08-d65a19e9c3ab.png)

**Comment by atapas** [comment]
> hey @atapas @koustov can u guide me on out of the following route on which of the routes should the search and filter box be visible? ![image](https://user-images.githubusercontent.com/57500840/175491290-1b4c2da2-6af1-41e6-ad08-d65a19e9c3ab.png)

Hey @ShivamBhasin2002 I would suggest you join the discord and post it in the need-help channel for the community member to get you info faster.

Discord Server: https://discord.gg/YbmXwU5f

For the routes.. it should be available for the `/plays` and `/plays/:play-name` . IMO this issue should be fixed in the component than route?
