### ISSUE TITLE
[Add a Play]: Cryptocurrency Tracker

### ISSUE THREAD

**Issue by Adit0507** [reactplay/react-play#312]
Thank You! 

## What's the Play about?

- This project gives real time updates about all cryptocurrencies i.e Coin price, Market Cap, 24h Price Change, Total Volume.

- Also there is a search bar where the user can search their desired coin.

## What ReactJS concept will be used to create this play?
- useState, useEffect hooks were used.
- Coin Gecko API was used
- Axios was used to fetch the data.

## Are you willing to take it up for implementation?
- I don't get this question.

- I have a live version of the project ready <a href="https://cryptocurrency-tracker-adit0507.netlify.app/">here</a>

**Comment by atapas** [comment]
> ## Are you willing to take it up for implementation?
> * I don't get this question.
> * I have a live version of the project ready [here](https://cryptocurrency-tracker-adit0507.netlify.app/)

Hey @Adit0507 

As we expect the projects to build within ReactPlay(not linking the external projects at this point), the question is if the person providing an idea to implement in ReactPlay is also taking up for the implementation. Alternatively, people may post an idea and want someone else to pick it up. I hope it clarifies.

**Comment by Adit0507** [comment]
Ok so I want to implement i.e build the project in React Play as well. 

I have to follow the steps given here right ?
https://github.com/reactplay/react-play/blob/main/CREATE-PLAY.md

Really looking forward to contribute here 😃

**Comment by atapas** [comment]
> Ok so I want to implement i.e build the project in React Play as well.
> 
> I have to follow the steps given here right ? https://github.com/reactplay/react-play/blob/main/CREATE-PLAY.md
> 
> Really looking forward to contribute here 😃

Very excited to have you here @Adit0507 

Assigned it to you. Yes that what you need to follow and build. Happy coding.

We have a Discord you may want to join un case you have any questions to ask to anyone! Here is the link: https://discord.gg/3XVrkdCz

**Comment by Adit0507** [comment]
@atapas I'm getting a minor problem, the play is working really well but I cant see the cover image in my localhost even though I uploaded it and imported it correctly.

I also tried using Unsplash and google drive but it didnt work.

**Comment by atapas** [comment]
> @atapas I'm getting a minor problem, the play is working really well but I cant see the cover image in my localhost even though I uploaded it and imported it correctly.
> 
> I also tried using Unsplash and google drive but it didnt work.

Can you please paste the play meta object of your play from the play-meta.js file? Also gimme the image link.

**Comment by Adit0507** [comment]
Ofc

{
    id: 'pl-cryptocurrency-tracker', 
    name: 'Cryptocurrency Tracker', 
    description: '',
    component: () => {return <CryptocurrencyTracker />},
    path: '/plays/cryptocurrency-tracker',
    level: 'Intermediate',
    tags: 'JSX, Hooks, API',
    github: 'Adit0507',
    cover: 'plays/cryptocurrency-tracker/Cover.jpg',
    blog: '',
    video: '',
    language: 'js'
  },


Image Link: https://unsplash.com/photos/ZwAsnutAtUM

**Comment by atapas** [comment]
> Ofc
> 
> { id: 'pl-cryptocurrency-tracker', name: 'Cryptocurrency Tracker', description: '', component: () => {return }, path: '/plays/cryptocurrency-tracker', level: 'Intermediate', tags: 'JSX, Hooks, API', github: 'Adit0507', cover: 'plays/cryptocurrency-tracker/Cover.jpg', blog: '', video: '', language: 'js' },
> 
> Image Link: https://unsplash.com/photos/ZwAsnutAtUM

Keep the value of the cover property blank 

cover: ‘’

And keep a cover.png file in your play folder.


Alternatively the cover property should have the URL to a publicly hosted image with resolvable path.


You can See other plays as references.

**Comment by Adit0507** [comment]
Its working now !!!!

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?
