### ISSUE TITLE
🐛 [Bug report]: Input checkboxes are uncontrolled

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#313]
#319 All though it works really good but suddenly i encontered some error about the input checkboxs are becoming uncontrolled. we have value here but there is no onChange
![Screenshot from 2022-06-15 20-15-29](https://user-images.githubusercontent.com/63530626/173857635-484fd04d-6a0a-4977-a895-3d3051b1ab03.png)

**Comment by atapas** [comment]
@Angryman18 is that something you can fix quickly?

**Comment by Angryman18** [comment]
ok i will see it

**Comment by Angryman18** [comment]
#319
