### ISSUE TITLE
✨ [Feature request]: Connection between IDEA and PLAY

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#317]
**Is your feature request related to a problem? Please describe.**
Ideas are a great place to share prospects for play however today we cannot identify if play has been created/improvised from an existing idea.
The concept of this issue is to create a connection between an `idea` and `play` visually. It must be `1 to *` relationship

**Describe the solution you'd like**
Need UI proposal

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Programming-School-Pro-Coding** [comment]
Hey @koustov 

How can i do it ?
