### ISSUE TITLE
🐛 [Bug report]: Style update required for mobile view

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#318]
**Describe the bug**
The mobile view should be altered to utilize the more of real-estate. Need to reduce the padding and for cards and card container in mobile view.
Refer screenshot

**To Reproduce**
1. Open `ReactPlay` on handheld device
2. Navigate to `browse` plays

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7145967/173771401-e710298c-6e5a-4c7d-b690-60fe414158a8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: SS
 - OS: Android

**Additional context**
Issue owner, please create a UI proposal in discussion thread first

**Comment by nitishsaini706** [comment]
@koustov are you working on this?

**Comment by koustov** [comment]
> @koustov are you working on this?

No, i just posted what i noticed. You are free to pick it up.

**Comment by ammaaraslam** [comment]
Anyone working on this?

**Comment by Sachin-chaurasiya** [comment]
> Anyone working on this?

Hey @ammaaraslam, No one is working on this issue. should I assign this to you?

**Comment by ammaaraslam** [comment]
Ya sure
