### ISSUE TITLE
✨ [Feature request]: PWA integration of our ReactPlay app

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#333]
hi if anyone is willing to build pwa of our reactplay app is strongly welcome. i could also able to help working with workbox and building serviceworker. thanks.

**Comment by frankiefab100** [comment]
I will like to work on this.

**Comment by Angryman18** [comment]
thanks for taking this on.

**Comment by atapas** [comment]
Hi @frankiefab100 Any update? The required images are posted on discord.
