### ISSUE TITLE
🐛 [Bug report]: Expanding-card play's active card is too wide on small screen. 

### ISSUE THREAD

**Issue by Deepak8717** [reactplay/react-play#335]
**Describe the bug**
On small screen, the active card of Expanding-card play is too wide. it's a small tweak if someone looking to get started can fix it. 

Solution:
the width of .active class needs to be fixed on small screen

**To Reproduce**
1. Go to https://reactplay.io/plays/expanding-cards/
2. resize the screen to smaller screen
3. look at the active card
4. active card looks too wide

**Expected behavior**
active card should be well aligned with other cards. 

**Screenshots**

![expanding-card](https://user-images.githubusercontent.com/5671550/174956890-050da7e0-c278-4867-969d-2d11c0431af6.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser brave

**Comment by atapas** [comment]
@Deepak8717 will you fix this one?

**Comment by Deepak8717** [comment]
@atapas I will fix it. but I let it taken by someone until I am busy with a new play. if no one does I will as it's just one line of code.

**Comment by atapas** [comment]
@lpizzinidev Can I assign this to you?

**Comment by NdukaClara** [comment]
@atapas Can you assign this to me?

**Comment by atapas** [comment]
> @atapas Can you assign this to me?

Hi @NdukaClara I see there is a PR already that @Deepak8717 is doing review.

Could you please pick up anything else from the list?

https://github.com/reactplay/react-play/labels/good%20first%20issue
