### ISSUE TITLE
✨ [Feature request]: Add Emojis to Simple Live Chat Play

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#336]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an Emoji icon when you click on it it show up many emojis to add

**Describe alternatives you've considered**

**Additional context**
I am happy to work on

**Comment by Angryman18** [comment]
Awesome. do it.

**Comment by Programming-School-Pro-Coding** [comment]
Assign me @atapas

**Comment by Programming-School-Pro-Coding** [comment]
@atapas Where can i add the code ?

simple-live-chat directory is not in plays folder

**Comment by Programming-School-Pro-Coding** [comment]
I guess the code is in [react-play-store](https://github.com/reactplay/react-play-store) repository

**Comment by koustov** [comment]
> I guess the code is in [react-play-store](https://github.com/reactplay/react-play-store) repository

[react-play-store](https://github.com/reactplay/react-play-store) repository not wired yet. The code still lies here. Under [simple-live-chat](https://github.com/reactplay/react-play/tree/main/src/plays/simple-live-chat)

**Comment by Programming-School-Pro-Coding** [comment]
Hi @Angryman18 

In your play, It give me an empty page

Please tell me why ?

**Comment by Angryman18** [comment]
yes. we dont have firebase api and other secret details commit. you can join us on discord i will help you giving our config file. https://discord.gg/p5XmjnpM

**Comment by atapas** [comment]
> yes. we dont have firebase api and other secret details commited. you can join us on discord i will help you giving our config file. https://discord.gg/p5XmjnpM

@Angryman18 we shouldn’t provide the prod keys to devs. Developer must create firebase account and get required configurations.

I would suggest to update your play’s readme and add the step on how to get the configurations and what keys are required.

If you are giving the details of how to do it to @Programming-School-Pro-Coding , make sure he documents it part of his PR.

**Comment by Programming-School-Pro-Coding** [comment]
> yes. we dont have firebase api and other secret details commited. you can join us on discord i will help you giving our config file. https://discord.gg/p5XmjnpM

I can't

**Comment by Programming-School-Pro-Coding** [comment]
> > yes. we dont have firebase api and other secret details commited. you can join us on discord i will help you giving our config file. https://discord.gg/p5XmjnpM
> 
> @Angryman18 we shouldn’t provide the prod keys to devs. Developer must create firebase account and get required configurations.
> 
> I would suggest to update your play’s readme and add the step on how to get the configurations and what keys are required.
> 
> If you are giving the details of how to do it to @Programming-School-Pro-Coding , make sure he documents it part of his PR.

👍

**Comment by Programming-School-Pro-Coding** [comment]
How I can get the config file ?

**Comment by Angryman18** [comment]
Go to firebase.google.com then sign in.
Add a project
Create an webapp inside that project(not Android, not ios, only webapp)
Copy config and assign to rhe environment vars
Enable authentication
Enable database writing rules
For env var key you will find inside firebase.js inside simple live chat play
Add env car & run the play. Thats it.

**Comment by Programming-School-Pro-Coding** [comment]
> Go to firebase.google.com then sign in. Add a project Create an webapp inside that project(not Android, not ios, only webapp) Copy config and assign to rhe environment vars Enable authentication Enable database writing rules For env var key you will find inside firebase.js inside simple live chat play Add env car & run the play. Thats it.

Ok

**Comment by Programming-School-Pro-Coding** [comment]
Hey @atapas I want to the client id and client secret to run the github method

**Comment by Programming-School-Pro-Coding** [comment]
> Go to firebase.google.com then sign in. Add a project Create an webapp inside that project(not Android, not ios, only webapp) Copy config and assign to rhe environment vars Enable authentication Enable database writing rules For env var key you will find inside firebase.js inside simple live chat play Add env car & run the play. Thats it.

It is not working

**Comment by Programming-School-Pro-Coding** [comment]
.
