### ISSUE TITLE
🐛 [Bug report]: Modal in Memory Game lost responsiveness

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#339]
The modal which open by clicking "how to play" button in memory game play has lost it's responsiveness after adding tailwind i guess.
indeed we need to fix it by reducing the aspect ratio of the image.
anyone who is good at css may fix it i guess.

![Screenshot from 2022-06-23 09-54-50](https://user-images.githubusercontent.com/63530626/175209053-2a6d43b4-6422-4fb0-b369-5669d08f4ad4.png)

**Comment by atapas** [comment]
@Angryman18 I see it working correctly on prod. Have you checked on reactplay.io or localhost?

![image](https://user-images.githubusercontent.com/3633137/175213301-7b8ca875-13e8-44d4-8e67-45b241ce0627.png)

**Comment by Angryman18** [comment]
Yes it works on small screen but on 720p display its broken like the screenshot. Also works well on 1080p.

**Comment by Kaybangz** [comment]
It looks to be working fine now, otherwise, i'd like to be assigned this issue

**Comment by yung-coder** [comment]
hey, @Angryman18  in which device there is a CSS break ..?

**Comment by Angryman18** [comment]
> hey, @Angryman18 in which device there is a CSS break ..?

768p or 720p. Please check it.

**Comment by yung-coder** [comment]
hey @Angryman18 , I checked it is working fine in maximum number of devices but it's breaking for a specific res like this...

![Screenshot 2022-06-29 231803](https://user-images.githubusercontent.com/94097778/176503492-718a8fa3-cc67-4ca8-9ad7-029be8f6e05b.png)

**Comment by Angryman18** [comment]
Can you fix it. We want it to appear properly on all sort of resolution.

**Comment by yung-coder** [comment]
@Angryman18 yeah,
 
I will try my best to fix it asap..!

**Comment by yung-coder** [comment]
Hey can u assign me for this i would like to try solving it ..!
