### ISSUE TITLE
✨ [Feature Request]: Footer enhancements

### ISSUE THREAD

**Issue by nirmalkc** [reactplay/react-play#340]
**Describe the bug**
Current footer is quite simple. Need more additional information about the vision of the project, stack used, purpose, contact options etc.,

**Expected behavior**
- Footer logo
- A short description about the owner
- Social media connecting options
- Description about the framework
- What can you do using the framework
- How can you start with this framework
- How can you show your support to this framework by a tweet or being a sponsor.

**Screenshots**
![image](https://user-images.githubusercontent.com/6359059/175311440-374143e5-9832-45df-bd71-a396b4e77f93.png)

**Additional tasks**
- @atapas to come up with a better description text for the show love section and its button labels.
- @atapas to provide more info about the hyperlink in the footer and where it would take the user to? Should that new page should be taken care as a part of this issue?

**Comment by nawed2611** [comment]
Hey, Can I work on this issue?

**Comment by atapas** [comment]
> Hey, Can I work on this issue?

Hey @nawed2611 I see it is already picked by @nirmalkc. You can look into other issues and help. Thanks!
