### ISSUE TITLE
🐛 [Bug report]: Normalize the backend API calls

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#353]
**Describe the bug**

The Home page makes the call to list all the plays but we do not use it in the Home page. Ideally,

- Home page should make the "Featured" play call
- The play list page should make the all plays call with minimalistic data required for the thumbnails.
- Each of the play details should retrieve all required data for a play.

**Comment by 6km** [comment]
can I help with this issue?

**Comment by Angryman18** [comment]
i guess it being managed by #371

**Comment by Angryman18** [comment]
[Screencast from 25-07-22 07:31:38 PM IST.webm](https://user-images.githubusercontent.com/63530626/180795885-9de4a7ff-dfa0-4c49-981d-7808e9d11121.webm)

this issue isnt solved i guess.

**Comment by koustov** [comment]
> Screencast.from.25-07-22.07.31.38.PM.IST.webm 
> this issue isnt solved i guess.

@Angryman18 , I didn't get the issue . Are you saying that, there shouldn't be any more API calls to list PLAYS once its done in `/plays` route? Please explain

**Comment by Angryman18** [comment]
yes that was what i tried to show there. I think we dont make the call when user goes into a play but if user landing directly on a play only then we should me making the api call ?
