### ISSUE TITLE
🐛 [Bug report]: Search filter issue under production

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#357]
before we used to search using ```or``` operator in our query (where clause) but for now we have ```dev_mode``` which we have to consider while searching goes on either prodcution or development. and the intension is not to make search through ```dev_mode: true``` on our production. in order to make that working we need the 2 operator for our pattern which we are following to generate the graphql query. help is needed in this scenerio when searchTerm goes for ```play name``` or ```play description``` and ```dev_mode: false```

**Comment by koustov** [comment]
We wouldn't need `dev_mode` variable in consideration one the PR for #328 gets merged

**Comment by Angryman18** [comment]
ok thats fine.

**Comment by atapas** [comment]
> We wouldn't need `dev_mode` variable in consideration one the PR for #328 gets merged

@koustov what do you think the done done ETA of #328 ? 

Interim let us fix the query?

**Comment by Angryman18** [comment]
let us close this issue i think

**Comment by atapas** [comment]
Fixed
