### ISSUE TITLE
[Add a Play]:  Budget App

### ISSUE THREAD

**Issue by Adit0507** [reactplay/react-play#367]
## What's the Play about?
I would like to add a Budget app with which the user can plan their expense and categorize them really well. 

Live site: https://budget-app-adit0507.netlify.app/

## What ReactJS concept will be used to create this play?
Custom Hooks, Prop Drilling, Local Storage

## Are you willing to take it up for implementation?
Yes, I'm willing to build it.

I took reference from https://www.youtube.com/watch?v=yz8x71BiGXg to make this project.

**Comment by atapas** [comment]
All yours, please join our discord to discuss anything or if you need help.

https://discord.gg/S4jNTRsm
