### ISSUE TITLE
[Add a Play]: TextUtils App

### ISSUE THREAD

**Issue by Susmita-Dey** [reactplay/react-play#373]
Thank You! 

## What's the Play about?
TextUtils App is a text-based utility app that can count words and manipulate them for case conversion and also includes many oher features.

Deployed version:- https://text-utils-six.vercel.app/ 

## What ReactJS concept will be used to create this play?
Function-based components and react-routing has been used to create this play.

## Are you willing to take it up for implementation?
Yes.

**Comment by atapas** [comment]
@Susmita-Dey 

We are changing the way play is created in react play. It's in beta. Do you want to test that feature while you create this play? Let me know, I'll enable you for that.

**Comment by atapas** [comment]
Sure thing!

Just ping @koustov or @murtuzaalisurti on our Discord. They will assist you wherever needed 👍

**Comment by Surya8991** [comment]
@Susmita-Dey I can help with adding few functions to this play.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey I can help with adding few functions to this play.

Yes, add some more functionalities in the github repo if you want. I'm having exams now. So, I couldn't submit the play right now.

**Comment by Surya8991** [comment]
@Susmita-Dey I have added extract text and numbers do check it out . Created a pull request too!.

**Comment by atapas** [comment]
> @Susmita-Dey I have added extract text and numbers do check it out . Created a pull request too!.

What’s the PR link?

**Comment by Surya8991** [comment]
1sec let me add reverse add function and i will add the project directly to play section and give you  pr link

**Comment by Susmita-Dey** [comment]
@atapas Kindly add hacktoberfest label to it. making the PR soon.

**Comment by Sachin-chaurasiya** [comment]
@Susmita-Dey , Done.
