### ISSUE TITLE
✨ [Feature request]: Tech stack page needs better categorization

### ISSUE THREAD

**Issue by nirmalkc** [reactplay/react-play#375]
**Is your feature request related to a problem? Please describe.**
Tech stack page has a big list of brand logos, which makes it difficult to understand and crowded.

**Describe the solution you'd like**
Organized it with a contextual groups.

**Current design**
![image](https://user-images.githubusercontent.com/6359059/178903880-4b3b0d41-b4d6-4cda-ae62-4c506a81bdf7.png)

**Comment by frankiefab100** [comment]
Seems this issue has been resolved @Angryman18

**Comment by jeromtom** [comment]
What would be the ideal categories?

**Comment by jeromtom** [comment]
Would categorisation like this be good enough?

Front-end:

- React.js
- Redux.js
- Material UI
- Tailwind
- Javascript
- Typescript

Back-end:

- NHost
- Hasura
- PostgreSQL
- Firebase
- GraphQL
- Docker
- Umami

Versioning:

- Git
- Github

**Comment by jeromtom** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by atapas** [comment]
> I would like to work on this issue. Please assign it to me.

Hi @jeromtom are you taking part in Fosshack? We originally labelled this issue for the Fosshack event so wanted to confrm.

**Comment by jeromtom** [comment]
Yes

**Comment by atapas** [comment]
> Yes

Assigned.

Please post your first draft of design when ready!

**Comment by ujwal-yadav** [comment]
@atapas Please assign this to me.

**Comment by priyankarpal** [comment]
> @atapas Please assign this to me.

alright!

**Comment by ujwal-yadav** [comment]
> > @atapas Please assign this to me.
> 
> alright!
I have raised the PR, pls review this- https://github.com/reactplay/react-play/pull/1265
