### ISSUE TITLE
Clicking on Featured Play makes the header hidden halfway

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#383]
![featuredPlayError](https://user-images.githubusercontent.com/63530626/179547067-062e10a4-2c65-4e72-aec4-252ff0cf89f8.png)

**Comment by yung-coder** [comment]
@Angryman18 in what resolution u are seeing it ..?

**Comment by koustov** [comment]
Mostly because of `position: fixed` within a flexbox.

**Comment by Angryman18** [comment]
> @Angryman18 in what resolution u are seeing it ..?

768px

**Comment by yung-coder** [comment]
I will check it ..

**Comment by 6km** [comment]
> @Angryman18 I have checked it but i am not facing this problem ...

I think you will only face this problem if you open a play from the featured plays section.

**Comment by yung-coder** [comment]
Yes
