### ISSUE TITLE
[Add a Play]: Dev jokes

### ISSUE THREAD

**Issue by yung-coder** [reactplay/react-play#389]
Thank You! 

## What's the Play about?

Developer jokes is a app where a random developer joke pops up every time you open it or click next joke !

Deployed version ⤵️

https://jokes-dev.netlify.app/

## What ReactJS concept will be used to create this play?

Function-based components and axios for fetching data from api ! 

## Are you willing to take it up for implementation?

Yes

**Comment by atapas** [comment]
This is done.
