### ISSUE TITLE
[Add a Play]: countries-statics 

### ISSUE THREAD

**Issue by Deepak8717** [reactplay/react-play#392]
Thank You! 

## What's the Play about?
This play shows the country's information around the world. Information such as name, area, demographics, capital currencies, etc. You can search for a specific country or short by region. 

## What ReactJS concept will be used to create this play?
You learn to work with useState, use effect hook and rest API data fetching techniques. 

## Are you willing to take it up for implementation?
Yes

**Comment by atapas** [comment]
Very exciting project @Deepak8717 

Can you give the link of the API, I am interested to see what kind of data we get from it. I may suggest some additional use cases

**Comment by Deepak8717** [comment]
@atapas 
https://restcountries.com/
