### ISSUE TITLE
[Add a Play]: DevDASH

### ISSUE THREAD

**Issue by shreyazz** [reactplay/react-play#394]
Thank You! 

## What's the Play about?
It is a [dev.to](https://dev.to/) dashboard which visually represents the stats of your blogs. It also lists out the blogs of an author.

## What ReactJS concept will be used to create this play?
Hooks
State
API Fetching

## Are you willing to take it up for implementation?
Yes

**Comment by atapas** [comment]
@shreyazz great,

looking forward to see it.
