### ISSUE TITLE
🐛 [Bug report]: fetch() is not supported in IE11

### ISSUE THREAD

**Issue by 6km** [reactplay/react-play#400]
**Describe the bug**
Fetch API (used in multiple hooks) is not supported in IE11 and Opera Mini.

**Desktop:**
 - OS: Windows
 - Browser IE11

**Additional context**
- https://caniuse.com/fetch

**Comment by 6km** [comment]
Btw, are you planning to support IE11?

**Comment by atapas** [comment]
Internet Explorer is officially retired in June 2022. No intention of supporting it. We support MS Edge, though.

We will not fix this issue.
