### ISSUE TITLE
🐛 [Bug report]: Memory Game is broken

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#406]
![Screenshot from 2022-07-22 23-10-04](https://user-images.githubusercontent.com/63530626/180494505-b2af026d-8eae-4ba4-9d4f-9b0202ff6106.png)

**Comment by 6km** [comment]
Looks like it's an error with Hasura

![image](https://user-images.githubusercontent.com/62352949/180495405-03197079-bcdd-421c-ba0f-885b07a8f09d.png)

**Comment by Angryman18** [comment]
It works on small screen device
