### ISSUE TITLE
🐛 [Bug report]: Cannot prompt details and generate id 

### ISSUE THREAD

**Issue by EOEboh** [reactplay/react-play#416]
**Describe the bug**

I cannot create a play. The "Create Play" button keeps returning a blank screen.

**To Reproduce**
 
This particular step in the "Create Play Guide" below does not pop up for me.

`Fill the information and submit. Paramter details

Field`

**Expected behavior**
An information containing different parameters where I am supposed to fill and then, an ID generated. 

**Desktop (please complete the following information):**
 - Browser : chrome

**Comment by atapas** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> I cannot create a play. The "Create Play" button keeps returning a blank screen.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> This particular step in the "Create Play Guide" below does not pop up for me.
> 
> `Fill the information and submit. Paramter details
> 
> Field`
> 
> **Expected behavior** An information containing different parameters where I am supposed to fill and then, an ID generated.
> 
> **Desktop (please complete the following information):**
> 
> * Browser : chrome

What's your OS?

Could you please post some screens of the error?

**Comment by EOEboh** [comment]
I think I kind of mistakenly skipped the questions after the authentication.

How do I prompt the detail-questions again? The questions that describe your project

**Comment by atapas** [comment]
> I think I kind of mistakenly skipped the questions after the authentication.
> 
> How do I prompt the detail-questions again? The questions that describe your project

@koustov can you plz help here?

**Comment by murtuzaalisurti** [comment]
@atapas can you check if the play created in the db?

**Comment by atapas** [comment]
> @atapas can you check if the play created in the db?

@EOEboh What was the name given for the play? So that I can see if it has been created in the DB?

**Comment by EOEboh** [comment]
I already resolved it. This issue can be closed now. Thanks
