### ISSUE TITLE
[Add a Play]: Travel App

### ISSUE THREAD

**Issue by EOEboh** [reactplay/react-play#419]
Thank You! 

## What's the Play about?
This is a web app that returns the nearest restaurants, hotels and other attractions based on the user's geographical location.

## What ReactJS concept will be used to create this play?
Hooks in React such as useState, UseRefs
Axios in React to fetch data.

## Are you willing to take it up for implementation?
Yes I am. Already working on it

**Comment by EOEboh** [comment]
@atapas could you assign this to me please?. Can I proceed?

**Comment by atapas** [comment]
Done

**Comment by EOEboh** [comment]
Thank you
