### ISSUE TITLE
🐛 [Bug report]: Can create a play in production

### ISSUE THREAD

**Issue by 6km** [reactplay/react-play#420]
**Describe the bug**
I'm allowed to create a play in production

**To Reproduce**
1. Go to [reactplay.io/plays/create](https://reactplay.io/plays/create)

**Expected behavior**
I mustn't be able create a play in production

**Screenshots**
![image](https://user-images.githubusercontent.com/62352949/180768713-7fbee03e-8042-47d8-bac1-fac1169f7761.png)

**Comment by atapas** [comment]
> **Describe the bug** I'm allowed to create a play in production
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [reactplay.io/plays/create](https://reactplay.io/plays/create)
> 
> **Expected behavior** I mustn't be able create a play in production
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/62352949/180768713-7fbee03e-8042-47d8-bac1-fac1169f7761.png)

Ah, are you accessing the URL directly?

**Comment by 6km** [comment]
> are you accessing the URL directly?

Yes, I created a play through [reactplay.io/plays/create](https://reactplay.io/plays/create)

**Comment by atapas** [comment]
> > are you accessing the URL directly?
> 
> Yes, I created a play through [reactplay.io/plays/create](https://reactplay.io/plays/create)

Quite a tester you are @6km :)

**Comment by atapas** [comment]
> > > are you accessing the URL directly?
> > 
> > 
> > Yes, I created a play through [reactplay.io/plays/create](https://reactplay.io/plays/create)
> 
> Quite a tester you are @6km :)

Btw, do you want to attempt fixing it too? @6km

**Comment by atapas** [comment]
@koustov please review this one.
