### ISSUE TITLE
✨ [Feature request]:  Dark mode/Light on react play

### ISSUE THREAD

**Issue by Surya8991** [reactplay/react-play#424]
Hi ReactPlay Team ,As a developers I would love to see ReactPlay in dark mode too hoping it will be released soon.

**Comment by EOEboh** [comment]
Hello @atapas can you assign this issue to me?

**Comment by Sam10-debug** [comment]
Hoping I can do some work on this part 🙏

**Comment by Sam10-debug** [comment]
Hi ReactPlay, I would love to work on the dark/light mode on react play with react 
Can this issue be assigned to me?
