### ISSUE TITLE
✨ [Feature request]: Add a button to choose a random play

### ISSUE THREAD

**Issue by 6km** [reactplay/react-play#434]
**Is your feature request related to a problem? Please describe.**
No, but it can be a good addition, especially if the user is puzzled and doesn't know which play to choose.

**Describe the solution you'd like**
Add a button in the plays list page that opens a random play

**Comment by harshsinghatz** [comment]
But right now we have different difficulty levels for the plays which can give some useless play recommendations to the user

Maybe we can target the beginners and only give random plays of beginner tag!!!

Let me know what you think if this seems like a nice feature. I can pick this up

**Comment by atapas** [comment]
Yeah, I think this feature request is like how we can ask Netflix to select a movie for us!

I agree with @harshsinghatz about the use case. I think this should be built with some intelligence. Like based on the kind of plays visited by the users in the past, I recommend one. We can leverage both levels and tags for this purpose. However, if the user is new or we do not have the historical data built yet for the user, we can then show it randomly.

What say?

**Comment by harshsinghatz** [comment]
@atapas Yeah, that makes sense!!

**Comment by 6km** [comment]
I agree with you @atapas, @harshsinghatz. I think this feature will be a great way to make users actively use ReactPlay if it's based on their previous visits.

**Comment by Sam10-debug** [comment]
I’d like to work on this part please

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
