### ISSUE TITLE
✨ [Feature request]: Automatic tweet about newly created play

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#438]
**Is your feature request related to a problem? Please describe.**
The idea is to submit an automatic tweet as soon as a new play gets merged to `main`. It will remove, all manual intervention and will reduce human error.

**Describe the solution you'd like**
- Gather the creator's tweeter handle (optional) during play creation
- Create a standard template for `new play tweet`
- Create a git hook (nhost) to submit a tweet once it gets merged,

**Describe alternatives you've considered**
NA

**Additional context**
Review the template before proceeding

**Comment by Srisuma13** [comment]
Hi @koustov, I would like to contribute to this issue if it is up for grabs so that you could assign it to me.
