### ISSUE TITLE
✨ [Feature request]: Bring top creator of the month and leader board

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#439]
**Is your feature request related to a problem? Please describe.**
A suggestion is to create a space on the home page where `top play creator of the month` and `leaderboard` can be placed.

Note: this request doesn't talk about `most liked` plays for now.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
Need to review the screen before initiating the implementation

**Comment by Architsharma7** [comment]
Hey, I would like to work on this issue, can you assign it to me?

**Comment by NagarjunShroff** [comment]
Hey @atapas, I would also be interested to work on this - I'm also open to working along with @Architsharma7.

**Comment by atapas** [comment]
I shall assign based on @Architsharma7 response tomorrow.

**Comment by Architsharma7** [comment]
Hey @atapas Yes i would like to work on it.

**Comment by atapas** [comment]
@Architsharma7 I saw @NagarjunShroff got started with it. Would you please contact him(on discord) and see you both can work on it?

**Comment by Architsharma7** [comment]
Okay I'll contact him if he shares his discord

**Comment by NagarjunShroff** [comment]
> Okay I'll contact him if he shares his discord

here is my disord Nagarjun Shroff#0175

**Comment by mayukh551** [comment]
@atapas @koustov 
I have created a space on the home page to display the top play creator card,
here's a screenshot
<img width="960" alt="play-creator-ss" src="https://user-images.githubusercontent.com/82811112/209909897-25cfb527-c9d0-4dea-8229-e3e8335399c2.png">
