### ISSUE TITLE
✨ [Feature request]: Create individual Contributor Page

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#440]
**Is your feature request related to a problem? Please describe.**
The application already has the capability to filter plays by the creator and that's not all about the user. A user has many more touch points across the application. Refer to the below list to understand the scope of this feature as a whole.

In scope (for this issue0:
- Listing user-related plays
- User profile information (name, photo, handles eyc.)
- When he joined reactplay

Out of scope (reserved for future implementation):
This would make more sense when we start adding more information about the user 
-  no of play liked
- current badge
- engagement with the application
- total blogs
- Many more

Ideally, this is an epic-level item. For now, let us treat it as a feature.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
- Once #417 gets merged, we will be having a more controlled way of handling user space
- Need to review the mockup before initiating the implementation

**Comment by bhtibrewal** [comment]
@atapas I would like to work on this

**Comment by atapas** [comment]
Let's do the design first
