### ISSUE TITLE
🐛 [Bug report]: Play snap is broken: Cover image is not appearing

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#443]
**Describe the bug**
When you share a play on any social media, the cover image is not appearing. Need to update the meta tag with appropriate cover image.

**To Reproduce**
1. Go to `reactplay.io`
2. List plays
3. Open any play which has a local cover image
4. Copy the URL
5. Paste the URL on social platforms/IMs

**Expected behavior**
The play should appear with name, description, creator and image

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by atapas** [comment]
@Sachin-chaurasiya, this will be a high-priority item to fix. Please let us know if you need any help/prior details. Let's go.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya, this will be a high-priority item to fix. Please let us know if you need any help/prior details. Let's go.

Sure @atapas.

**Comment by Sachin-chaurasiya** [comment]
Hey @koustov , Some Play has a cover image and some do not. which has a cover I can see a preview like this.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/59080942/183263334-be68dd93-ba3b-41f6-b6bc-5a2f704f9caf.png">

It will be greater if you could share some examples like what are we expecting precisely here.
