### ISSUE TITLE
✨ [Feature request]: Lazy load for home page

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#463]
**Is your feature request related to a problem? Please describe.**
Currently, the entire home page gets loaded at once, which might not be very useful as the user might not travel to the bottom of the page every single time.
So the idea of this issue is to load individual sections when the user is scrolling for it.

**Describe the solution you'd like**
Lazy loaded sections.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by crater90** [comment]
Hey @koustov, I would like to work on this issue.... can you assign me ?

**Comment by Sachin-chaurasiya** [comment]
@crater90 , Welcome to the community.
Assigned to you, happy coding 🚀 .

**Comment by crater90** [comment]
#692

**Comment by crater90** [comment]
#692
