### ISSUE TITLE
[Add a Play]: Star rating

### ISSUE THREAD

**Issue by frankiefab100** [reactplay/react-play#464]
Thank You! 

## What's the Play about?
A react component that allows a user to easily select their preferred star rate.

## What ReactJS concept will be used to create this play?
Functional components and useState hooks

## Are you willing to take it up for implementation?
Yes

**Comment by EOEboh** [comment]
Hey @frankiefab100 have you started development on this?

**Comment by frankiefab100** [comment]
> Hey @frankiefab100 have you started development on this?

Yes, I have
