### ISSUE TITLE
🐛 [Bug report]: Home page being rendered while refreshing

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#486]
**Describe the bug**
When you are refreshing any page other that `home` page, initially home page is being rendered for a while. 

**To Reproduce**
1. Open any play or go to `/plays` path
2. Refresh the page
3. Notice home page contents are being rendered for some time

**Expected behavior**
While loading is going on, it should show the animation, not home page

**Screenshots**
![image](https://user-images.githubusercontent.com/7145967/184499058-c5be4f7d-7118-4a5b-b8bf-b5780357dec5.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by Angryman18** [comment]
yes its weird. this issue relates with the filickering issue.

**Comment by Angryman18** [comment]
i got the issue. its happening for authentication thing. when we refresh the page auth status is false for 1-2 render then it becomes true instantly. i think this should not happen. authentication status should persist between first render to last render (either true or false) when refreshing the page?? facing same issue on hackathon project.

**Comment by priyankarpal** [comment]
i guess this issue got solved
