### ISSUE TITLE
✨ [Feature request]: Change how contributors are displayed in the homepage

### ISSUE THREAD

**Issue by ammaaraslam** [reactplay/react-play#492]
**Describe the solution you'd like**

Currently the **Contributors** section in the homepage consists of only 29 contributors out of 39 *(this is caused by the GitHub API's pagination system - each page returns only 30 items)* and each contributor is represented inside a circle. Here are few features to be implemented on to the contributors section *(suggested by @atapas)*.

- Based on the number of contributions we make the circle bigger... more contributions more bigger circle. We get the contribution count already.
- We show first 25 contributors on the page starting with the bigger _(most contributions)_ to smaller circles _(least contributions)_.
- Then we show a link like  "See more contributors" and that takes to the project's readme's contributor section where we show all the contributors.

This may encourage people to even contribute more make their circle bigger and even to appear on our home page.

**Comment by nobel10122025** [comment]
i would like to work on this :)

**Comment by yung-coder** [comment]
I would like to work on it 🛠️

**Comment by yung-coder** [comment]
Hey @atapas i will continue the work for the issue form tomorrow sorry for the delay i was just busy with my college exams..!

**Comment by AbhiPatel10** [comment]
Looks good or Should we make a consistency on bigger to smaller Circle?

![image](https://user-images.githubusercontent.com/76242769/218032729-45e45bc0-fb43-4260-94f2-b2ce1be42173.png)

**Comment by atapas** [comment]
> Looks good or Should we make a consistency on bigger to smaller Circle?
> 
> ![image](https://user-images.githubusercontent.com/76242769/218032729-45e45bc0-fb43-4260-94f2-b2ce1be42173.png)

Yes I like it. What's your logic?

**Comment by AbhiPatel10** [comment]
I Use Switch case in One function and use that function in Style. 

switch (true) {
      case item >= 80:
        contributionCircle = { height: '150px', width: '150px' };

        break;
      case item < 80 && item >= 50:
        contributionCircle = { height: '130px', width: '130px' };

        break;
      case item < 50 && item >= 30:
        contributionCircle = { height: '100px', width: '100px' };

        break;
      default:
        contributionCircle = { height: '50px', width: '50px' };
    }



So Now we need to show only 25 contributors in Home page and made one Button for "See more contributors" and redirect to GitHub contributors ?

also please assign this task to me.

**Comment by 6km** [comment]
> Yes I like it. What's your logic?

More Contributions = Bigger Circle 😃

**Comment by atapas** [comment]
> I Use Switch case in One function and use that function in Style.
> 
> switch (true) { case item >= 80: contributionCircle = { height: '150px', width: '150px' };
> 
> ```
>     break;
>   case item < 80 && item >= 50:
>     contributionCircle = { height: '130px', width: '130px' };
> 
>     break;
>   case item < 50 && item >= 30:
>     contributionCircle = { height: '100px', width: '100px' };
> 
>     break;
>   default:
>     contributionCircle = { height: '50px', width: '50px' };
> }
> ```
> 
> So Now we need to show only 25 contributors in Home page and made one Button for "See more contributors" and redirect to GitHub contributors ?
> 
> also please assign this task to me.

Great..

A few things:

- These sizes must be responsive. so that on mobile, tab , and desktops they scale well.
- We need to have a contributions page on the /contributors route to list them all in a card with
photo, name, number of contributions

**Comment by AbhiPatel10** [comment]
Okay, I'm working on it to improve that code and make it responsive across all devices.

Is there a specific design I should use for the contributor page, or can I make it however I see fit?

**Comment by atapas** [comment]
> Okay, I'm working on it to improve that code and make it responsive across all devices.
> 
> Is there a specific design I should use for the contributor page, or can I make it however I see fit?

Make it on Figrma or https://excalidraw.com/ and share the design first

**Comment by atapas** [comment]
Hey @yung-coder 

I have added @AbhiPatel10 as assignee to this issue as he made some progress on it. If you had started on it or panning to contribute, you both can collaborate. In case you are not working/not panning to work on it, let me know.

**Comment by yung-coder** [comment]
@atapas

Hey sure would love to collaborate and finish this task asap pitch me on discord @AbhiPatel10 let's get this done.

**Comment by AbhiPatel10** [comment]
@yung-coder Thank you for collaborating; I have sent you the message on Discord.

**Comment by atapas** [comment]
@AbhiPatel10 @yung-coder 

Please give me an idea of how the all contributors page may look like. Some basic design.

**Comment by AbhiPatel10** [comment]
Sure sir working on it... Building basic design in Figma

**Comment by AbhiPatel10** [comment]
Looks Good ?  @atapas Sir 


 ![image](https://user-images.githubusercontent.com/76242769/218300083-3bb32a39-8d78-4e7c-a15f-fc5638346143.png)
