### ISSUE TITLE
✨ [Feature request]: Add Section for React Play Posts on blog.reactplay.io

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [reactplay/react-play#517]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add Section or Page or Both of them for React Play Posts on blog.reactplay.io

**Describe alternatives you've considered**

**Additional context**

**Comment by brittanyjoiner15** [comment]
@Programming-School-Pro-Coding want to make sure i understand this issue, and if so i might be able to help! is the goal to add a section that shows tagged posts that are react plays? Or whats the way to differentiate which posts are React Plays?

**Comment by Programming-School-Pro-Coding** [comment]
> @Programming-School-Pro-Coding want to make sure i understand this issue, and if so i might be able to help! is the goal to add a section that shows tagged posts that are react plays? Or whats the way to differentiate which posts are React Plays?

I don't understand you
