### ISSUE TITLE
ReactPlay misspelled in the CLI

### ISSUE THREAD

**Issue by frankiefab100** [reactplay/react-play#518]
ReactPlay is misspelled as `rectplay` during installation in CLI

![reactplay misspelling](https://user-images.githubusercontent.com/46662771/186211968-e07be347-6424-42b5-a714-e55c8fb6b020.JPG)

**Comment by ammaaraslam** [comment]
Hi @frankiefab100, thanks for noticing it. Will fix it ASAP.

**Comment by frankiefab100** [comment]
> Hi @frankiefab100, thanks for noticing it. Will fix it ASAP.

Alright👍🏼

**Comment by ammaaraslam** [comment]
This issue has been fixed with this [PR](https://github.com/reactplay/create-react-play/pull/25) on the [`create-react-play`](https://github.com/reactplay/create-react-play) repo
