### ISSUE TITLE
🐛 [Bug report]: 

### ISSUE THREAD

**Issue by Deevyn9** [reactplay/react-play#524]
**Describe the bug**
Inconsistent horizontal margin on the navbar

**To Reproduce**
1. Go to 'The reactplay site'
3. Scroll to the ''hero page"

**Expected behavior**
Same space between the edge of screen and the elements on both sides of the navbar

**Screenshots**

**Desktop (please complete the following information):**
 - Browser  [chrome]

**Additional context**
Nothing else

**Comment by atapas** [comment]
Hey @Deevyn9 

Thanks for reporting it. Could you please post a screenshot of the issue?

**Comment by Deevyn9** [comment]
The places the arrows are pointing to are the ones in question 

![image](https://user-images.githubusercontent.com/79726362/187045497-7025a937-7907-48b8-9412-e49d77bc501e.jpeg)

**Comment by atapas** [comment]
Thanks @Deevyn9 for the clarity. Do you want to fix it?

**Comment by mohanadkandil** [comment]
Hello,
can I fix it ?

**Comment by atapas** [comment]
> Hello,
> can I fix it ?
> @atapas @Deevyn9

Go ahead
