### ISSUE TITLE
[Add a Play]: Pokemon app

### ISSUE THREAD

**Issue by yung-coder** [reactplay/react-play#527]
Thank You! 

## What's the Play about?

So , it's kinda fun type app it will give details of a specific pokemon on search like it's hp, moves and etc....

## What ReactJS concept will be used to create this play?

Axios for fetching data from api and react hooks..!

## Are you willing to take it up for implementation?

Yes

**Comment by vasantisuthar** [comment]
@yung-coder go ahead

**Comment by yung-coder** [comment]
Okay 🥷✔️
