### ISSUE TITLE
🐛 [Cancel btn on Filter Modal does not work]: 

### ISSUE THREAD

**Issue by mayukh551** [reactplay/react-play#548]
**Describe the bug**
When you want to cancel the filtered queries by clicking on the cancel button on the filter modal
the filters do not get removed.

**To Reproduce**
1. Click on Filter Icon beside the search input
3. Apply one or more filters.
4. After the filters are applied and filtered plays are displayed, if you want to remove the applied filters, clicking on cancel button won't remove the applied filters.

**Expected behavior**
On clicking the cancel button on filter modal, all applied filters should get removed.

**Desktop (please complete the following information):**
 - OS: [e.g. win 10]
 - Browser [chrome]

**Comment by atapas** [comment]
Hi @mayukh551 

The objective of the cancel button was not to clear the applied filter. Rather to close the modal. I think it is better to rename it as Close.

However, we need a way to remove the applied filter. Can we add a link called `Clear All` at the top right of the modal? Click on it will clear the filter. Whats Say?

**Comment by mayukh551** [comment]
Understood!

Yes, a 'clear All' button is necessary.
I will try and add 'Clear All' button that removes all applied filters.
