### ISSUE TITLE
[Add a Play]: Typing Speed Test 

### ISSUE THREAD

**Issue by makdoom** [reactplay/react-play#557]
Thank You! 

## What's the Play about?

It's a typing test application in ReactJS where users can test their typing speed or accuracy.

## What ReactJS concept will be used to create this play?

React hooks (useState, useEffect etc) and some javascript concept

## Are you willing to take it up for implementation?

Yeah...!!

**Comment by anirudhp26** [comment]
Hey, I would like to work on this feature !

**Comment by makdoom** [comment]
Hey @anirudhp26 I am already working on it ..!
