### ISSUE TITLE
🐛 [Bug report]: Content goes blank searching play name which are under development mode

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#564]
there a lot plays which comes from the graphql call clicking on browse button. we can search for any play which are available but searching a play name which is created but they are not yet published, our play section goes blank as shown on the screenshot.

![Screenshot from 2022-09-23 16-38-36](https://user-images.githubusercontent.com/63530626/191948050-41f683e6-6a10-4f3f-a81f-a4b498e873c9.png)

**Comment by atapas** [comment]
> there a lot plays which comes from the graphql call clicking on browse button. we can search for any play which are available but searching a play name which is created but they are not yet published, our play section goes blank as shown on the screenshot.
> 
> ![Screenshot from 2022-09-23 16-38-36](https://user-images.githubusercontent.com/63530626/191948050-41f683e6-6a10-4f3f-a81f-a4b498e873c9.png)

Can you give the steps?

**Comment by Angryman18** [comment]
search `threads` keyword on the search bar. we have a `threads` named play created but not yet published.

**Comment by atapas** [comment]
> search `threads` keyword on the search bar. we have a `threads` named play created but not yet published.

Got it, when we query the plays, we need to add devMode false.. to fix it so that ongoing plays won;t me fetched..

Seems you already started Hacking :) feel free to fix it.

**Comment by Hat52** [comment]
I would like to work on this issue

**Comment by sarkartanmay393** [comment]
@atapas I would to like to work on it, if its available.

**Comment by Abhighyaa** [comment]
Hey @atapas, I can contribute fixing this. Please let me know, if this still prevails. Thanks.

**Comment by Hat52** [comment]
@atapas as you have reopened this issue, I would like to work on it.

**Comment by atapas** [comment]
> @atapas as you have reopened this issue, I would like to work on it.

Assigned

**Comment by Hat52** [comment]
@atapas do you have any Idea how I can recreate this bug, I have tried the above explanation by @Angryman18 but that doesn't result in the page going blank.
Thanks

**Comment by atapas** [comment]
Ok so it is this way

- Create a play locally.. this entry still gets created in DB and now search by that play name

I believe this has been fixed to show an error that play not found.. Can you give it a try?

**Comment by Hat52** [comment]
Sure

**Comment by Hat52** [comment]
@atapas I have created a play on my local and then searched the play on the live app, This issue is not appearing instead I am seeing the proper message that states "Play not found".

**Comment by priyankarpal** [comment]
this issue was solved
