### ISSUE TITLE
✨ [Feature request]: Integrate Google Analytics with ReactPlay

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#57]
**Is your feature request related to a problem? Please describe.**
It is an enhancement.

**Describe the solution you'd like**
We need to integrate GA to see the metrics.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by abhikhatri67** [comment]
Hey @atapas,

Is anyone working on this?

**Comment by atapas** [comment]
> Hey @atapas,
> 
> Is anyone working on this?

I am planning to pick it up as I have the tracking id and all. Having said that, if you want to pick it up, go ahead, I will get you the tracking id to integrate. Please let me know.

**Comment by abhikhatri67** [comment]
CooI, If you haven't started working on it, please assign it to me.

**Comment by atapas** [comment]
> CooI, If you haven't started working on it, please assign it to me.

Done

**Comment by atapas** [comment]
We do not need this issue anymore as the Umami is integrated.
