### ISSUE TITLE
Setup Commitlint to enhance the developer experience

### ISSUE THREAD

**Issue by KashishLakhara04** [reactplay/react-play#570]
### Goal

- Setup Commitlint and Configure commitlint to use conventional config ``@commitlint/config-conventional``
### How commitlint helps?

- Commitlint helps your team adhere to a commit convention. By supporting npm-installed configurations it makes sharing of commit conventions easy.
### Resources

- [Commitlint setup](https://commitlint.js.org/#/guides-local-setup)
- [Conventional Commit Message](https://www.conventionalcommits.org/en/v1.0.0/)

I would like to work on this issue.

**Comment by Abdul-Hafeez-Galib** [comment]
Hi, can you assign this to me.

**Comment by Abdul-Hafeez-Galib** [comment]
No
