### ISSUE TITLE
🐛 [Bug report]: Heading levels are not heirarchical

### ISSUE THREAD

**Issue by EmmaDawsonDev** [reactplay/react-play#580]
**Describe the bug**
Heading levels are not being used heirarchically which is an accessibility problem.

**To Reproduce**

**Expected behavior**
H1 should be followed by h2, then h3 and so on.

**Screenshots**

**Desktop (please complete the following information):**
 All browsers

**Smartphone (please complete the following information):**
All devices

**Additional context**
I would like to work on this issue.

**Comment by Bennykillua** [comment]
Hi @EmmaDawsonDev  I will like to work on this. What particular file has this issue?

**Comment by atapas** [comment]
Thank you @EmmaDawsonDev 

I'm on vacation, will look into it from Wednesday, 5th Oct. Keep going, keep contributing 👍
