### ISSUE TITLE
🐛 [Bug report]: npm install error

### ISSUE THREAD

**Issue by Susmita-Dey** [reactplay/react-play#591]
**Describe the bug**
Legacy error and a lot of dependancy errors are being generated on running `npm install`

**To Reproduce**
1. Clone the repo locally
2. Go inside the folder
3. Open terminal in that folder and run `npm install`

**Expected behavior**
No errors should have been reproduced and everything should have been installed succesfully within a few minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/79099734/193462647-443dffc4-51cf-400d-9124-229cfd3e2aba.png)

**Laptop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
Kindly assign me this issue as part of hacktoberfest contribution. I want to add the command to remove this type of error in te `CREATE-PLAY.md` file to help other contributors who might face the same problem in the near future. 

Command to be added:- **`npm install --legacy-peer-deps`**

**Comment by MajorReact** [comment]
I'd like to handle this. Could you assign this task to me?

**Comment by Susmita-Dey** [comment]
@atapas Will make a PR by tomorrow

**Comment by MajorReact** [comment]
> @atapas Will make a PR by tomorrow

Is the session closed to me?

**Comment by atapas** [comment]
> > @atapas Will make a PR by tomorrow
> 
> Is the session closed to me?

I didn't get that question, @MajorReact. Do you mean if this issue still can be owned by you? That is not likely, as @Susmita-Dey is already on it. You can always find another one!
