### ISSUE TITLE
🐛 [Bug report]: Empty Note error

### ISSUE THREAD

**Issue by muzaffar640** [reactplay/react-play#600]
**Describe the bug**
The user has the ability to make blank notes. If the `Note Title` and `Note Content` are both blank, no user should be able to create an empty note.

**To Reproduce**
1. Go to the [Keeper App](https://reactplay.io/plays/shivam-katare/keeper)
2. Click on the `+` button keeping both `Note Title`  and `Note Content` empty.

**Expected behavior**
Users shouldn't be able to create any empty notes and should instead receive some sort of popup notification asking them to "Please provide some valid data."

**Screenshots**
![Screenshot 2022-10-04 at 12 31 50 AM](https://user-images.githubusercontent.com/55223302/193659579-1dec7b93-9c10-4679-9973-699b5c3d212e.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Redmi K20 pro
 - OS: Android
 - Browser: Chrome

I will be more than happy to fix it. Let me know if this makes sense.

**Comment by thisisbillall** [comment]
Can I take this?

**Comment by atapas** [comment]
> Can I take this?

Assigned to you

**Comment by siddxharth** [comment]
Hey, can I work on this too?

**Comment by siddxharth** [comment]
Hey @Angryman18, I've made a pull request fixing the bug. Could you please review that?
