### ISSUE TITLE
✨ [Feature request]: Build dashboard for react-play 

### ISSUE THREAD

**Issue by shrilakshmishastry** [reactplay/react-play#603]
**Is your feature request related to a problem? Please describe.**
Currently, there is no dashboard that shows the statistics of activity across react-play website vise as well individual play vise.

**Describe the solution you'd like**
As part of this new feature, we will be introducing a dashboard that gives statistics on activities

**Comment by ajaxbo360** [comment]
can you please assign me to this issue

**Comment by supminn** [comment]
- I believe #218 is related to the same.

**Comment by atapas** [comment]
> * I believe [✨ [Feature request]: Play statistics: View Count #218](https://github.com/reactplay/react-play/issues/218) is related to the same.

Nah.. they are different..

I think, this issue is going to be like a creator's profile where the other one will show a view count per play in the play list page. @shrilakshmishastry What you think?

**Comment by shrilakshmishastry** [comment]
Seems like it's a part of what we are building now. We have currently planned to build a dashboard at individual play level, react-play level view statistics and GitHub activities 

Wireframe of same is below 
![playfigures](https://user-images.githubusercontent.com/29778698/194001017-775274f4-3f13-4980-b323-63a0bb99134e.png)

**Comment by atapas** [comment]
Ok @shrilakshmishastry I misunderstood then!

One question... How would user get into this dashboard? What will be the user journey?

**Comment by joshi-kaushal** [comment]
@shrilakshmishastry & @vasantisuthar, if you need a hand with this issue, let me know!
