### ISSUE TITLE
[Add a Play]: Image App

### ISSUE THREAD

**Issue by obinneji** [reactplay/react-play#615]
Thank You! 

## What's the Play about?
An app that allows users to save images in a personal gallery.

## What ReactJS concept will be used to create this play?
react-router, redux, react-dom, react.

## Are you willing to take it up for implementation?
yes

**Comment by obinneji** [comment]
Good day sir. The major issue I'm having is styling but I will do it this
Week
L

**Comment by obinneji** [comment]
Sorry I could not contribute my laptop is faulty

**Comment by joshi-kaushal** [comment]
@obinneji hey man! Open source is not just limited to Hacktoberfest. You can still contribute with your code and ideas.

**Comment by hasnainmakada-99** [comment]
You can contribute to this issue @obinneji and I am removing the hacktoberfest label as it is over now @atapas sir

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue? @obinneji
