### ISSUE TITLE
Better to add contribute file in readme 

### ISSUE THREAD

**Issue by pavankumarraju13** [reactplay/react-play#617]

**Comment by atapas** [comment]
@pavankumarraju13 I didn't understand this issue description. Could you please be more elaborative?

**Comment by pavankumarraju13** [comment]
Adding a contributing.md file to the readme file would be more clear and better

**Comment by Sachin-chaurasiya** [comment]
@pavankumarraju13 , We already have `contributing.md` linked in the readme.

![image](https://user-images.githubusercontent.com/59080942/194231365-cf6a0234-59c5-4a2d-a7db-2022ba49c337.png)
