### ISSUE TITLE
[Add a Play]: Typing Master

### ISSUE THREAD

**Issue by aayush-1412** [reactplay/react-play#618]
Thank You! 

## What's the Play about?
This play creates a web app for checking the typing speed of user by providing their WPM data.

## What ReactJS concept will be used to create this play?
React Hooks, React-DOM

## Are you willing to take it up for implementation?
Yes

**Comment by Sachin-chaurasiya** [comment]
Hello @aayush-1412 , Welcome to the community.
We already have play for typing test https://github.com/reactplay/react-play/pull/565.

Live Link : https://reactplay.io/plays/makdoom/typing-speed-test

**Comment by aayush-1412** [comment]
> Hello @aayush-1412 , Welcome to the community. We already have play for typing test #565.
> 
> Live Link : https://reactplay.io/plays/makdoom/typing-speed-test

Oh my bad, didn't saw it. I will be trying my hands on some other ideas then, thanks.
