### ISSUE TITLE
[Add a Play]: Weather App

### ISSUE THREAD

**Issue by aayush-1412** [reactplay/react-play#619]
Thank You! 

## What's the Play about?
This web app displays the current weather information such as temperature, humidity along with weather forecast feature upon entering the city.

## What ReactJS concept will be used to create this play?
React Hooks , React DOM

## Are you willing to take it up for implementation?
Yes

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by mashriram** [comment]
@atapas - I am interested in developing this app. Can you please assign it to me?

**Comment by mashriram** [comment]
@priyankarpal , @atapas - I am interested in working in this issue. Can you please assign it to me?

**Comment by priyankarpal** [comment]
> @priyankarpal , @atapas - I am interested in working in this issue. Can you please assign it to me?

sure

**Comment by mashriram** [comment]
@priyankarpal  - I have submitted a PR for the Weather App - https://github.com/reactplay/react-play/pull/1270
Looking forward to your review comments
