### ISSUE TITLE
[Add a Play]: Text Utils

### ISSUE THREAD

**Issue by AnkitaMalik22** [reactplay/react-play#625]
Thank You! 

## What's the Play about?

Text Utils helps us to manipulate our texts the way we want.

## What ReactJS concept will be used to create this play?

- useState 
- useEffect

## Are you willing to take it up for implementation?
yes

**Comment by Sachin-chaurasiya** [comment]
Hello @AnkitaMalik22 , Welcome to the community.
It would be great if you provide more info about the play.

**Comment by AnkitaMalik22** [comment]
> Hello @AnkitaMalik22 , Welcome to the community.
> It would be great if you provide more info about the play.


**About Text Utils**

Users can - 

- count words in their text
- remove white spaces from text
- remove duplicate lines
- make texts capitalise ,uppercase etc according to them

**Comment by AnkitaMalik22** [comment]
> @AnkitaMalik22 , Assigned to you, happy coding 🚀 .

I was working on this and someone else's PR got merged ?!

**Comment by Sachin-chaurasiya** [comment]
@AnkitaMalik22 , No, You can continue.

**Comment by Susmita-Dey** [comment]
@AnkitaMalik22 It's a duplicate issue. Check #373

**Comment by Sachin-chaurasiya** [comment]
> @AnkitaMalik22 It's a duplicate issue. Check #373

Thanks, @Susmita-Dey  for the confirmation.

**Comment by atapas** [comment]
> > @AnkitaMalik22 It's a duplicate issue. Check #373
> 
> Thanks, @Susmita-Dey for the confirmation.

Are these 2 issues identical in just names or in implementation too? If the intent is different then we can still have both.

**Comment by AnkitaMalik22** [comment]
> @AnkitaMalik22 It's a duplicate issue. Check #373 

Okay! I was unaware .

**Comment by AnkitaMalik22** [comment]
> > > @AnkitaMalik22 It's a duplicate issue. Check #373
> > 
> > Thanks, @Susmita-Dey for the confirmation.
> 
> Are these 2 issues identical in just names or in implementation too? If the intent is different then we can still have both.

The implementation is also alike ! It's okay I will try  creating another play
