### ISSUE TITLE
✨ [Feature request]: Add first interaction to greet a new contributor whenever they open a new issue or pull request

### ISSUE THREAD

**Issue by hasnainmakada-99** [reactplay/react-play#631]
**Is your feature request related to a problem? Please describe.**
We should integrate [first interaction](https://github.com/marketplace/actions/first-interaction) with reactplay so that when new contributors will open a new issue or they are raising pr for the first time, They should be greeted

**Describe the solution you'd like**
Integrate first interaction with reactplay

**Describe alternatives you've considered**
There are various actions available in the marketplace but I will suggest `first interaction` because it is simple to integrate

**Additional context**
None

**Comment by atapas** [comment]
Are you doing it?

**Comment by hasnainmakada-99** [comment]
> Are you doing it?

I can do that, but I think we should give other contributors a chance too

**Comment by atapas** [comment]
> > Are you doing it?
> 
> I can do that, but I think we should give other contributors a chance too

That makes sense.. You may want to update the description with the lin to the `first interaction`.

**Comment by hasnainmakada-99** [comment]
> 

Means ?

**Comment by atapas** [comment]
> > 
> 
> Means ?

A link of how to do it.

**Comment by hasnainmakada-99** [comment]
Ok @atapas sir I'll attach a link on how to it

**Comment by Engineervinay** [comment]
Hey, @atapas , @hasnainmakada-99 👋  .  this is my first time participanting in hactoberfest. 
Can I work on this?  
I will try my best to complete it as soon as possible.

**Comment by hasnainmakada-99** [comment]
Yes @Engineervinay go for it

**Comment by Engineervinay** [comment]
Thanks @hasnainmakada-99  please assign me this issue, and is there any specific message that should be displayed or should I go with this normal greetings?

For issue: 
> Thank you for filing an issue in React-Play.
            If this is a bug report, please include relevant logs to help us debug the problem.

For PR:
> Hello! Thank you for your contribution.
  If you are fixing a bug, please reference the issue number in the description.
            If you are implementing a feature request, please check with the maintainers that the feature will be accepted first.

**Comment by hasnainmakada-99** [comment]
I think it's good to go, What do you say @atapas sir

**Comment by Engineervinay** [comment]
Hey @hasnainmakada-99 , @atapas . I have created pull request for this issue. here are some screenshots of tests.
![Screenshot (21)](https://user-images.githubusercontent.com/29520476/194575259-d33cb188-cb68-4f55-ad0e-41f225fa4a1b.png)
![Screenshot (22)](https://user-images.githubusercontent.com/29520476/194575264-d1c3ed0f-a26a-4290-8bdd-c4b24fb0b2b2.png)
