### ISSUE TITLE
🐛 [Bug report]: Updated techstack.jsx file

### ISSUE THREAD

**Issue by KORLA2** [reactplay/react-play#632]
**Describe the bug**
Imported Techstack info array if it is empty applying map on it gives error
**To Reproduce**

**Expected behavior**
I have changed a bit now it works fine
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by atapas** [comment]
@KORLA2 Was it giving any issue when you were running the app. I am asking as the tech-stack info is hard-coded and hardly can be empty. But there can be corner cases so I am trying to understand.

**Comment by KORLA2** [comment]
Sorry sir it is not the  issue but I some how want to contribute to this
repo really I haven't understood any thing sir please spare some time and
explain me sir I know react pretty well if you don't mind please assign
some issues sir
