### ISSUE TITLE
🐛 [Bug report]: div tag cannot appear as a descendant of p tag

### ISSUE THREAD

**Issue by SSK-14** [reactplay/react-play#643]
**Describe the bug**
div tag cannot appear as a descendant of p tag
p tag can only contain inline elements and div tag is a block element.
Putting a div tag inside it is improper.

**To Reproduce**
Steps to reproduce the behaviour:
1. in local development env
2. can see warnings in console.

**Expected behaviour**
Parent elements should be div and inside we can have p tag for texts in ExtendedFooter.

**Screenshots**
<img width="398" alt="Screenshot 2022-10-08 at 10 12 08 AM" src="https://user-images.githubusercontent.com/45158568/194688896-54bf30d0-d4b1-4dcd-b5ad-626e5f859b70.png">
<img width="391" alt="Screenshot 2022-10-08 at 10 12 22 AM" src="https://user-images.githubusercontent.com/45158568/194688910-68b9e15a-d60b-4e98-8a86-1bfeb3be262a.png">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [22]

**Additional context**
Like to work on this. Could you assign me to this?

**Comment by Sachin-chaurasiya** [comment]
@SSK-14 , Assigned to you.
