### ISSUE TITLE
🐛 [Bug report]: Play header is missing from Text Avatar play

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/react-play#650]
**Describe the bug**
The play header is missing from the Text Avatar play

**Steps to reproduce the behavior:
https://user-images.githubusercontent.com/59080942/194710767-0614cf46-1dbd-4e81-a471-291f8a61768c.mov

**Expected behavior**

**Screenshots**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/59080942/194710717-b01d212a-84d9-4d7a-845e-409613cb33a0.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hello @hiimnhan , As you have worked on the play, so can you take care of this issue?

**Comment by hiimnhan** [comment]
Yeah sure I will fix it

**Comment by Sachin-chaurasiya** [comment]
Thanks @hiimnhan , Assigned it to you.

**Comment by hiimnhan** [comment]
@Sachin-chaurasiya I don't really know how to fix it, is there any guide for it or I need to add the header to my component?

**Comment by atapas** [comment]
> @Sachin-chaurasiya I don't really know how to fix it, is there any guide for it or I need to add the header to my component?

Please check any of the existing play code. You need to add a header and wrap the body in the div.

**Comment by Sachin-chaurasiya** [comment]
> > @Sachin-chaurasiya I don't really know how to fix it, is there any guide for it or I need to add the header to my component?
> 
> Please check any of the existing play code. You need to add a header and wrap the body in the div.

@hiimnhan , For reference : https://github.com/reactplay/react-play/blob/main/src/plays/analog-clock/AnalogClock.jsx#L25

**Comment by hiimnhan** [comment]
got it
