### ISSUE TITLE
🐛 [Bug report]: Page does not load a login option.

### ISSUE THREAD

**Issue by madox357** [reactplay/react-play#653]
**Describe the bug**
I used `npm install --legacy-peer-deps` and reached the landing page. Found a project I liked and clicked create. It just refreshed the page and does not prompt anything else.
**To Reproduce**
1. Go to 'localhost'
2. Click on 'Create'
3. Scroll down to 'page'
4. See blank page

**Expected behavior**
I was expecting to see either the login with your github account information or reach authentication page.

**Screenshots**
![Screen](https://user-images.githubusercontent.com/49364274/194727360-70e8e35d-3cd2-4092-8539-53309d347afc.png)
![ReactPlay](https://user-images.githubusercontent.com/49364274/194727371-05426e8c-078a-445a-aae4-5bc6ec7ff8b7.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by koustov** [comment]
Hello @madox357 , it looks like `.env` file issue. Do you have it updated as per [README](https://github.com/reactplay/react-play/blob/main/README.md#%EF%B8%8F-create-a-env-file-at-the-root-of-your-project-folder-with-the-following-content)?
