### ISSUE TITLE
🐛 [Bug report]:  No unique key value for each play in FeaturedPlays

### ISSUE THREAD

**Issue by SSK-14** [reactplay/react-play#655]
**Describe the bug**
No unique key value for each play in FeaturedPlays.
Keys help React identify which items have changed, are added, or are removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. in local development env
2. can see warnings in console.

**Expected behaviour**
should have unique key value for each play in FeaturedPlays.

**Screenshots**
<img width="398" alt="Screenshot 2022-10-09 at 10 18 49 AM" src="https://user-images.githubusercontent.com/45158568/194738684-2d6c65ce-1cd4-403b-9c47-8aee47985f63.png">

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]
 - Version [ 22]

**Additional context**
Like to work on this. Could you assign me to this?

**Comment by Sachin-chaurasiya** [comment]
@SSK-14 , Should I assign this to you?

**Comment by SSK-14** [comment]
Yes, like to work on this.

**Comment by Sachin-chaurasiya** [comment]
@SSK-14 , Assigned to you.
