### ISSUE TITLE
✨ [Feature request]: Workflow to update all-contributors list

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#658]
**Is your feature request related to a problem? Please describe.**
Currently for each new entry, one has to manually invoke the `all-contributor` bot and update the contributor list. It's not feasible with expanding community.

**Describe the solution you'd like**
The ideal solution would be, to invoke a workflow on every PR merge. This workflow will check if the contributor is already present in the contributors list, if not then it will notify the bot which in return will create a PR.

**Describe alternatives you've considered**
GitAPI could be one alternative however that is a far-fetched idea. As of now, the workflow would hold good.

**Additional context**
NA

**Comment by Harshil-Jani** [comment]
Hi ! I would like to create the workflow.

**Comment by koustov** [comment]
> Hi ! I would like to create the workflow.

Sure @Harshil-Jani .I have assigned it to you

**Comment by Harshil-Jani** [comment]
Hi ! I have already Added the PR for the workflow, Can you try it out once ?
