### ISSUE TITLE
✨ [Feature request]: Add a share button on Typing Speed Play

### ISSUE THREAD

**Issue by bhtibrewal** [reactplay/react-play#668]
**Is your feature request related to a problem? Please describe.**
When i generate my typing speed report i would like to be able to share it with others.

**Describe the solution you'd like**
Add a share/ copy link button on the modal showing my typing speed.

**Describe alternatives you've considered**

**Additional context**
thinking of using the twitter API for this feature.

**Comment by Sachin-chaurasiya** [comment]
Hello @bhtibrewal, would you like to work on this issue?

**Comment by Sachin-chaurasiya** [comment]
> yes @Sachin-chaurasiya I want to work on this but I have just been assigned a task so would also need time to start with this one, also can u add label #hacktoberfest

Sure @bhtibrewal , assigning to you, you can work on this later.
