### ISSUE TITLE
✨ [Feature request]: Show Progress Status on Play Ideas Page

### ISSUE THREAD

**Issue by bhtibrewal** [reactplay/react-play#669]
**Is your feature request related to a problem? Please describe.**
I was going through the list of ideas and had decided to work on an idea and when i came to the repository I saw a issue already created with the idea and in progress.

**Describe the solution you'd like**
Show a Complted/ In -progress/ Available tag on all the play ideas card.

**Describe alternatives you've considered**
NA

**Additional context**
Filter for the same can also be provided on the page.

i would be pleased to get the chance to work on this Feature.

**Comment by atapas** [comment]
An idea can be implemented by multiple people.

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
