### ISSUE TITLE
[Add a Play]:  News feed application

### ISSUE THREAD

**Issue by NagarjunShroff** [reactplay/react-play#670]
Thank You! 

## What's the Play about?

News feed application based on countries.
- Supports different languages.
- Headlines/ detailed news.
- Search news
- Categories

## What ReactJS concept will be used to create this

React hooks: useState, useEffect

## Are you willing to take it up for implementation?

Yes

**Comment by koustov** [comment]
Assigned to you @NagarjunShroff
