### ISSUE TITLE
✨ [Feature request]:  Adding .env file for dev mode during create-react-play process

### ISSUE THREAD

**Issue by NagarjunShroff** [reactplay/react-play#675]
We can create a .env file with the required dev setup details.
Also, we can update .gitignore not to check in this file.

This would be really helpful for any beginner.

**Comment by Angryman18** [comment]
didnt quite understand the issue although we need .env file in order to run the app locally. we have it here https://github.com/reactplay/react-play#%EF%B8%8F-create-a-env-file-at-the-root-of-your-project-folder-with-the-following-content

**Comment by Yordaniss** [comment]
I saw that .env files are already in .gitignore. Perhaps it would be heplful if there will be .env.example file in project with data, that beginners could just rename and that's should be enough to get started.

If so i could take this issue.

**Comment by ammaaraslam** [comment]
Great suggestion @NagarjunShroff!
Gonna implement it 🚀
