### ISSUE TITLE
🐛 [Bug report]: nHost and umami svg not grey colour in tech stacks page

### ISSUE THREAD

**Issue by SSK-14** [reactplay/react-play#680]
**Describe the bug**
In tech stacks page nHost and umami svg does not have uniform colour like others.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://reactplay.io/tech-stacks'
2. Can see the colour difference 

**Expected behaviour**
**Screenshots**
<img width="253" alt="Screenshot 2022-10-11 at 7 07 12 PM" src="https://user-images.githubusercontent.com/45158568/195107285-f4bb5d41-01a2-4209-bee2-321bd1b532c7.png">
<img width="259" alt="Screenshot 2022-10-11 at 7 05 29 PM" src="https://user-images.githubusercontent.com/45158568/195107345-03e1ec13-18bc-43f8-ba21-12f4c18175e6.png">

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [ chrome, safari]
 - Version [22]

**Additional context**
Like to work on this. Could you assign me to this?

**Comment by Sachin-chaurasiya** [comment]
@SSK-14 , Assigned to you!
