### ISSUE TITLE
🐛 [Bug report]: An alert appears when the website loads

### ISSUE THREAD

**Issue by joshi-kaushal** [reactplay/react-play#683]
**Describe the bug**
An alert saying _New Update Available, Click OK to update_ prompts on the screen whenever I open a website with a new session.

**To Reproduce**
try opening the website from a different browser or incognito mode

**Expected behavior**
An alert appearing on the screen like below

**Screenshots**
![image](https://user-images.githubusercontent.com/53049546/195256870-93d46aa9-8a46-414a-bd71-f1fd63efdbcb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Browser: Microsoft Edge 
 - Version: Edge 106.0.1370.42

**Additional context**
- I tried this on Chrome and sometimes it works fine. but many times(mainly on edge) it shows the alert.

**Comment by Angryman18** [comment]
this is not a bug. it is the service worker which asks to update the cache whenever it detects content pushed.
