### ISSUE TITLE
🐛 [Bug report]: Infinite Loading UI for Twitters section

### ISSUE THREAD

**Issue by billy-le** [reactplay/react-play#685]
**Describe the bug**
When twitter widget fails to load their script, the cards won't show and the section is stuck in the loading state.

**To Reproduce**
1. Go to /
2. Once in a blue moon twitter widgets will fail to load
3. Scroll down to Community/Twitter Section 
4. See infinite loading state

**Expected behavior**
Show error or hide section

**Screenshots**
![image](https://user-images.githubusercontent.com/9342687/195281234-4df9fa2f-27b5-4e0b-bfc7-d3d77b264e1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox, Chrome

**Additional context**
May not always fire due to external script being fetched

**Comment by billy-le** [comment]
I have a fix for this as well as for #684 in one PR.

**Comment by priyankarpal** [comment]
ig this issue got solved @billy-le You can check the website
