### ISSUE TITLE
[Add a Play]: 

### ISSUE THREAD

**Issue by Shreyash1601** [reactplay/react-play#693]
### What's the Play about?

**A React component to display the current scorecard of T20 matches and results of previous matches**

A ReactJS component to display live scores and results of T20 matches happening globally

### What ReactJS concept will be used to create this play?

Material UI icons and card rendering

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shreyash1601** [comment]
Please assign this to me

**Comment by Angryman18** [comment]
please edit the title with a little more information

**Comment by Shreyash1601** [comment]
> 

I have edited the title with more details. Please assign me this issue

**Comment by atapas** [comment]
Assigned

You still need to put the issue title
