### ISSUE TITLE
✨ [Feature request]: ADD: Alt text for Play cover Image 

### ISSUE THREAD

**Issue by bhtibrewal** [reactplay/react-play#697]
### Is your feature request related to a problem? Please describe.

for better SEO and we should add appropriate alt tag based on each play cover image instead of just having having empty string.
https://github.com/reactplay/react-play/blob/1afce9f3bcffd1ae4c7f2a3860e74e86f2cb77ea/src/common/playlists/PlayThumbnail.jsx#L79

### Describe the solution you'd like.

add a field of alt text in the play object

### Describe alternatives you've considered.

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SahilSingh177** [comment]
I can work on this issue. Assign this to me.
