### ISSUE TITLE
🐛 [Bug report]: Search Bug in the Emojipedia Play

### ISSUE THREAD

**Issue by bhtibrewal** [reactplay/react-play#698]
### Descrcibe the bug?

in the emojipedia search
- if I write a word that results in no emoji found even if I backspace and reach to a query word where i should be shown some emojis but it doesn't until I completely clear the search

### Steps to reproduce the bug?

1. Go to Emojipedia play
2. type some random text in saerch
3. then Backspace 
4. You won't see the emojis until you completely clear the search

### Expected behavior

update on backspace as well.

### Desktop (Please provide your system information)

Browser: Chrome

### Screenshot / Screenshare

![image](https://user-images.githubusercontent.com/42600164/195821675-477198af-b93a-4eba-9cf8-86a1caa9d963.png)
![image](https://user-images.githubusercontent.com/42600164/195821705-9de2928b-b04b-454b-a247-7d5173ef68c8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by nishasen** [comment]
Hello Tapas can you please assign the task to me?

**Comment by atapas** [comment]
@yung-coder and @Aniketmishra0 

Please don't mind assigned to @nishasen, as she asked for it long back on discord. Please look for other issues, I shall assign them.

**Comment by yung-coder** [comment]
Np, @atapas

**Comment by nishasen** [comment]
I have fixed the issue and raised a PR for the same #704
