### ISSUE TITLE
[Add a Play]: Note taker

### ISSUE THREAD

**Issue by atharvapatil46** [reactplay/react-play#702]
### What's the Play about?

- One would be able to add, delete and edit the notes.
- They can also search and pin the important notes.

### What ReactJS concept will be used to create this play?

- State management 
- User events

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayusshh19** [comment]
please assign this issue to me

**Comment by atapas** [comment]
> please assign this issue to me

It's assigned to @atharvapatil46
