### ISSUE TITLE
🐛 [Bug report]: Search plays on typing text instead of hitting enter all the time

### ISSUE THREAD

**Issue by nishasen** [reactplay/react-play#705]
### Descrcibe the bug?

When we search any play from the search bar we have to hit enter all the time, whereas it should search whenever the search text changes.

### Steps to reproduce the bug?

1. Go to search for a play on the top navigation bar.
2. On typing something you always have to press enter to make a search

### Expected behavior

The expected behavior of the search bar should be to provide search results whenever a person types something to it, instead of hitting enter all the time to search. 
Doing this way would give more results.

### Desktop (Please provide your system information)

OS : Windows
Browser: Chrome, firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nishasen** [comment]
@atapas I would like to take this up and fix the issue

**Comment by atapas** [comment]
We have this to minimize the backend calls. What's your suggestions to fix it?

**Comment by nishasen** [comment]
> We have this to minimize the backend calls. What's your suggestions to fix it?


We can use debounce for minimizing the backend call
According to recent situation there is only one backend call that is whenever we hit enter
If we use debounce we can set a delay so the backend calls will happen only after a certain delay
What do you suggest in this?

**Comment by nishasen** [comment]
Doing it the way @siddxharth is doing will cause a lot of backend calls

**Comment by siddxharth** [comment]
> Doing it the way @siddxharth is doing will cause a lot of backend calls

Can we put a timeout on it then? After x micro-seconds of receiving the last input, the search will play?

**Comment by nishasen** [comment]
> > Doing it the way @siddxharth is doing will cause a lot of backend calls
> 
> Can we put a timeout on it then? After x micro-seconds of receiving the last input, the search will play?

Actually this is were debounce comes into play, it puts a timer on calling the api only on certain intervals when we start typing

**Comment by siddxharth** [comment]
Okay, will give it a try. Can you assign me this?

**Comment by nishasen** [comment]
> Okay, will give it a try. Can you assign me this?

Hey I cant assign as I am not the owner of the repo, I think I have the solution though let @atapas confirm, if this could be a way.
