### ISSUE TITLE
[Add a Play]: Get Motivated

### ISSUE THREAD

**Issue by Hat52** [reactplay/react-play#740]
### What's the Play about?

This play will contain the motivation quotes from different peoples from different walk of life.

### What ReactJS concept will be used to create this play?

- State management
- Event handling
- Searching 

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SardarShubham** [comment]
Please assign this issue to me.

**Comment by Hat52** [comment]
I have already create this play and I will create a pr in a bit. You can find other issue to contribute to :)
