### ISSUE TITLE
🐛 [Bug report]: Glitch in homepage navigation bar

### ISSUE THREAD

**Issue by kd100100** [reactplay/react-play#741]
### Descrcibe the bug?

In the homepage, while clicking on the heart icon in the navigation bar, the navigation bar moves right.

### Steps to reproduce the bug?

1. Go to `http://localhost:3000` or `https://reactplay.io/` on laptop/desktop browser.
2. Click on `heart icon` on the top right.
3. You will find that navigation bar is moving to the right.

### Expected behavior

Navigation bar shouldn't change position because of clicking actions.

### Desktop (Please provide your system information)

OS: MacOS
Browser: Chrome
Version: 106.0.5249.119

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kd100100** [comment]
I would like to contribute to this issue.

**Comment by Sachin-chaurasiya** [comment]
@kd100100 , Can you attach the screenshot or recordings?

**Comment by kd100100** [comment]
[nav-error-recording.webm](https://user-images.githubusercontent.com/64349912/197127199-dfbb2269-e737-4659-ada2-e682181065c1.webm)

**Comment by Abhishek-90** [comment]
I would like to take it up.

**Comment by priyankarpal** [comment]
hello @kd100100 would you like to work on this issue?

**Comment by yash358** [comment]
hello @priyankarpal I like to work on this issue

**Comment by priyankarpal** [comment]
> hello @priyankarpal I like to work on this issue

sure

**Comment by dev0869** [comment]
I want to help with this issue.

**Comment by priyankarpal** [comment]
> I want to help with this issue.

sure

**Comment by priyankarpal** [comment]
> hello @priyankarpal I like to work on this issue

I am assigning this issue to someone because it has been pending for two weeks
