### ISSUE TITLE
🐛 [Bug report]: Making the language logo colorfull on hover

### ISSUE THREAD

**Issue by Hat52** [reactplay/react-play#747]
### Descrcibe the bug?

Currently when we hover on the trending play the language logo is not colored to be more visible.
![Uploading image.png…]()

### Steps to reproduce the bug?

Go to the home page of reactplay.io scroll down to the treading plays section and then hover on any one of the play you will notice that the play card's size increased but the language icon remains the same.

### Expected behavior

When we hover on the play card the language icon should become colorful.

### Desktop (Please provide your system information)

- Windows
- Chrome

### Screenshot / Screenshare

![image](https://user-images.githubusercontent.com/44437268/197182300-79b585f6-13b2-4b03-834c-35bc2c7f9a9f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SardarShubham** [comment]
I want to contribute to this issue.

**Comment by Hat52** [comment]
@SardarShubham I am working on this one you can find another one :)

**Comment by Hat52** [comment]
@Sachin-chaurasiya  @atapas can I get a colorful logo of ts and js that I can use.

**Comment by Sachin-chaurasiya** [comment]
@Hat52 , Can you create the colourful logo from existing js and ts logos?

**Comment by Hat52** [comment]
@Sachin-chaurasiya okay I will try.

**Comment by SardarShubham** [comment]
@Hat52 I know how to edit svgs, if you're couldn't find a way....i can still go ahead with this task.

**Comment by Hat52** [comment]
@Sachin-chaurasiya I can manage :)
