### ISSUE TITLE
✨ [Feature request]:  Configure repository with Gitpod

### ISSUE THREAD

**Issue by ammaaraslam** [reactplay/react-play#763]
### Is your feature request related to a problem? Please describe.

Contributors can easily setup the project in Gitpod with little to no config.

### Describe the solution you'd like.

This feature would include the addition of a **Open in Gitpod** button to the `README.md` that opens up the repository in Gitpod.io and a gitpod config script that automates the setup of the project in Gitpod. _(this includes the correct installation command - since there are certain errors in using `npm install` we have to use `npm install --legacy-peer-deps`. We can add this to the config to automatically be used to install the dependencies)_

### Describe alternatives you've considered.

*

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
This would be great @ammaaraslam 🚀
