### ISSUE TITLE
[Add a Play]: A Drawing Board made with React + TypeScritpt + Redux

### ISSUE THREAD

**Issue by bhaveek424** [reactplay/react-play#765]
### What's the Play about?

It's a drawing board having a Windows XP style nostalgic UI with:
- Color Pallete: choose different colors from
- Undo/Redo buttons
- Export buttons to save the drawing

### What ReactJS concept will be used to create this play?

React + TypeScript with Redux and later upgrade to Redux Toolkit

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhtibrewal** [comment]
hey @bhaveek424 I would like to collaborate on this play if you are interested

**Comment by bhaveek424** [comment]
Sure @bhtibrewal
