### ISSUE TITLE
✨ [Feature request]: Add support for cover.jpeg and cover.jpg

### ISSUE THREAD

**Issue by Hat52** [reactplay/react-play#774]
### Is your feature request related to a problem? Please describe.

yes, Right now when we try to set the preview image of a play. The cover image must have the .png extension otherwise the preview will not show.

### Describe the solution you'd like.

I would like to implement a feature that is smart enough to detect which cover file is present in the play and set it as preview of the play. 

### Describe alternatives you've considered.

...

### Screenshot / Screenshare

![image](https://user-images.githubusercontent.com/44437268/198988360-c83e8efc-fa3a-498c-b8a3-7fed95dae4e8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
How to want to plan the implementation? Interesting idea!

**Comment by Hat52** [comment]
@atapas I am open to suggestion. Right now I don't have much of idea.

**Comment by A-HK** [comment]
Hey @atapas, came across this org on the Foss Hack page and would love to contribute.
Can I get started on this issue?

**Comment by atapas** [comment]
> Hey @atapas, came across this org on the Foss Hack page and would love to contribute.
> 
> Can I get started on this issue?

Done!

**Comment by atapas** [comment]
> Hey @atapas, came across this org on the Foss Hack page and would love to contribute. Can I get started on this issue?

If you need any help please join the Discord: https://discord.gg/cDrXVm7bT4

**Comment by A-HK** [comment]
> If you need any help please join the Discord: https://discord.gg/cDrXVm7bT4

Yes, have joined the server, thanks :)

**Comment by Hat52** [comment]
@atapas is this issue fixed or can I work on it?
