### ISSUE TITLE
🐛 [Bug report]: *js/*ts files are not being generated upon creation of a play

### ISSUE THREAD

**Issue by bhaveek424** [reactplay/react-play#775]
### Descrcibe the bug?

After running the command `npx create-react-play -c <my unique play code>`, only a directory is created and it doesn't contain any files. I've tried it by selecting both javascript and typescript at the time of add a play, but none seems to generate their respective files.

### Steps to reproduce the bug?

1. After selecting the play and getting the `npx ....` command, run the `npx ...` command
2. It will create a directory/folder with the same name of the project
3. The folder won't have any files.
4. It will be an empty folder.

### Expected behavior

It is expected to create a file named `DrawingBoard.js` if selected Javascript.

### Desktop (Please provide your system information)

OS: Ubuntu(Linux)
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
Browser: Firefox, Brave

### Screenshot / Screenshare

![react-play-bug2](https://user-images.githubusercontent.com/61945842/199006205-fb51fd82-0bcc-4b93-baf3-74e9a7143366.jpeg)
![react-play-bug1](https://user-images.githubusercontent.com/61945842/199006219-7e39d4ca-1684-4afa-830e-826965ebf212.jpeg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
The same is reproducible on Mac too.

**Comment by koustov** [comment]
This issue has been fixed as part [this pr](https://github.com/reactplay/create-react-play/pull/29). I need a confirmation if its working in order to close this issue.
