### ISSUE TITLE
🐛 [Bug report]: The Contributor Readme is not updated

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#784]
### Descrcibe the bug?

We used to update the contributor readme manually by all-contributor bot after a successful contribution. In October that process wen through some block and the contributor list is not updatted.

### Steps to reproduce the bug?

Go to react-play read me and scroll down to the contributor list
The contributors doesn't match with actual contributors.

### Expected behavior

All contributors must be shown in the readme.

### Desktop (Please provide your system information)

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@all-contributors please add @Harshil-Jani @tech-doctor @ankitk26 @NagarjunShroff @zulalnb @Abrar0204 @samvardhan777 @GodStarLord @trishnakalita660 @KMohZaid for Code

**Comment by atapas** [comment]
@all-contributors
please add @tech-doctor for Code. 
please add @ankitk26 for Code.
please add @NagarjunShroff for Code.
please add @zulalnb for Code.
please add @Abrar0204 for Code.
please add @samvardhan777 for Code.
please add @GodStarLord for Code.
please add @trishnakalita660 for Code.
please add @KMohZaid for Code.

**Comment by atapas** [comment]
@all-contributors please add @ankitk26 for Code

**Comment by atapas** [comment]
Reopening this one @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
@all-contributors please add all missing contributors

**Comment by Sachin-chaurasiya** [comment]
@all-contributors please add missing contributors for Code

**Comment by Sachin-chaurasiya** [comment]
@all-contributors
please add @kd100100 for code
please add @bhtibrewal for code
please add @aks318 for code
please add @AbhiPatel10 for code
please add @Abrar0204 for code
please add @aimunhidden485 for code
please add @ankitk26 for code
please add @GodStarLord for code
please add @joeshajan for code
please add @KMohZaid for code
please add @samvardhan777 for code
please add @undefined for code
please add @trishnakalita660 for code
please add @wyarejali for code
please add @zulalnb for code
please add @nrshnaik for code

**Comment by Sachin-chaurasiya** [comment]
@all-contributors
please add @undefined for code
please add @trishnakalita660 for code
please add @wyarejali for code
please add @zulalnb for code
please add @nrshnaik for code

**Comment by Sachin-chaurasiya** [comment]
@all-contributors
please add @undefined for code
please add @trishnakalita660 for code
please add @wyarejali for code
please add @zulalnb for code
please add @nrshnaik for code

**Comment by Sachin-chaurasiya** [comment]
@all-contributors

please add @undefined for code
please add @trishnakalita660 for code
please add @wyarejali for code
please add @zulalnb for code
please add @nrshnaik for code
