### ISSUE TITLE
[Add a Play]: React Multistep Form 

### ISSUE THREAD

**Issue by abhi886** [reactplay/react-play#788]
### What's the Play about?

A simple multistep form that can be used in any of your projects.

### What ReactJS concept will be used to create this play?

Hook, Custom Hook, TypeScript, Form Handling, Conditional Rendering, State and Lifecycle, JSX, React Ref's.

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by abhi886** [comment]
Hey @joshi-kaushal ,
I had been working on the issue and also requested a pull request #804 . I think i am lost in the process and could not move forward. 
@atapas @koustov  Could you guide me towards the right direction please.
Thank You.

**Comment by atapas** [comment]
> Hey @joshi-kaushal ,
> 
> I had been working on the issue and also requested a pull request #804 . I think i am lost in the process and could not move forward. 
> 
> @atapas @koustov  Could you guide me towards the right direction please.
> 
> Thank You.

What issues are you facing?

**Comment by abhi886** [comment]
Hi @atapas,
I had opened a pull request #804 and was waiting for a review. Could you have a look at it please. 
Thank You.
