### ISSUE TITLE
🐛 [Bug report]: On each mount there is 3 api calls. better we cache these data instead of making calls

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#790]
### Descrcibe the bug?

actually not a bug but more like a feature. we are curerntly making call when our filter modal mounts each times and the apis are retuning same data everytime. better we only call these apis only on first mount and cache them internally so that next time when it mounts it wont make any call again and again.

### Steps to reproduce the bug?

we need to create a caching technique.

### Expected behavior

expected bhaviour is not making call on each mount

### Desktop (Please provide your system information)

OS - Ubuntu 22.10
brower - Google Chrome
version - lastest

### Screenshot / Screenshare

![Screenshot from 2022-11-11 19-02-17](https://user-images.githubusercontent.com/63530626/201361848-b76707b8-d2cb-4ab6-b4b2-57f047cc0097.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Angryman18** [comment]
if anyone wants can pick it up

**Comment by atapas** [comment]
@supminn want to take a look?

**Comment by supminn** [comment]
> @supminn want to take a look?

Sure, I'd like to take it up!
