### ISSUE TITLE
✨ [Feature request]: Code cleanup `Common` folder

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/react-play#813]
### Is your feature request related to a problem? Please describe.

Fix the eslint and formatting issue for common folder file formatting.

### Describe the solution you'd like.

Fix the eslint and formatting issue for common folder file formatting.

### Describe alternatives you've considered.

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by supminn** [comment]
Hi @Sachin-chaurasiya 
I would like to take it up. Could you assign this issue to me?

**Comment by Sachin-chaurasiya** [comment]
Assigned to you @supminn.

**Comment by yung-coder** [comment]
hey @Sachin-chaurasiya i would also like to work on this issue....?

**Comment by Sachin-chaurasiya** [comment]
> hey @Sachin-chaurasiya i would also like to work on this issue....?

@yung-coder , You can collaborate with @supminn for the same.

**Comment by supminn** [comment]
Hi @yung-coder I have fixed the issues and raised the PR.
I suggest you to check out `plays` folder. They still have a lot of errors pending.

**Comment by yung-coder** [comment]
> Hi @yung-coder I have fixed the issues and raised the PR. I suggest you to check out `plays` folder. They still have a lot of errors pending.

@Sachin-chaurasiya  can i work on plays folder .....?

**Comment by Sachin-chaurasiya** [comment]
> > Hi @yung-coder I have fixed the issues and raised the PR. I suggest you to check out `plays` folder. They still have a lot of errors pending.
> 
> @Sachin-chaurasiya  can i work on plays folder .....?

Yes , you can, but please mention the play in the ticket that you will be working on.

**Comment by supminn** [comment]
This issue can be marked closed as the PR has been merged with `release/code-cleanup` branch.
