### ISSUE TITLE
✨ [Feature request]: Code cleanup `Plays` folder

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/react-play#814]
### Is your feature request related to a problem? Please describe.

Fix the eslint and formatting issue for the `plays` folder file formatting.

### Describe the solution you'd like.

Fix the eslint and formatting issue for the `plays` folder file formatting.

### Describe alternatives you've considered.

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
@atapas @koustov @Angryman18 @Shivam-Katare, Please comment on this issue with play names that you guys will be working on.

**Comment by yung-coder** [comment]
hey @Sachin-chaurasiya  i  would  also like to work on Plays folder i will start with  MultiselectComponent play.

**Comment by supminn** [comment]
- I have raised PR #830 
- It contains the fixes for all the JavaScript files within the `plays` folder.

**Note**: The fixes are pending only on TypeScript files (.ts and .tsx)
Since most of these changes were w.r.t defining the types, I wasn't sure of their specific use case.
