### ISSUE TITLE
🐛 [Bug report]: Select Creator option from filter form is not displaying All after selecting All option from dropdown

### ISSUE THREAD

**Issue by surajgjadhav** [reactplay/react-play#818]
### Descrcibe the bug?

Select Creator option from filter form is not displaying **All** after selecting **All** option from drop down list. But, ideally it should show the **ALL** option after selecting it.

### Steps to reproduce the bug?

1. Go to reactplay.io
2. Select Browse Option on home page
3. Click on Filter Icon
4. under Creator option Select ALL 

### Expected behavior

It should show All in input box like other fields, after Selecting **All** option for Creator 

### Desktop (Please provide your system information)

OS: Windows 11
Browser: Brave
Version: 1.45.127

### Screenshot / Screenshare

Step 1: Selecting All option from dropdown list for Creator Option
![image](https://user-images.githubusercontent.com/31582237/204200991-24ed7efc-ce10-4ec6-876d-8f5aff78b77f.png)

Step 2: After Selecting All option from Creator Options
![image](https://user-images.githubusercontent.com/31582237/204201141-bda368e6-5c73-4396-83e9-6f03cef6bf07.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@supminn Want to check it out?

**Comment by surajgjadhav** [comment]
Yes, Sure 👍

**Comment by supminn** [comment]
> @supminn Want to check it out?

Sure @atapas, please assign it to me.

**Comment by surajgjadhav** [comment]
Thanks @atapas and @supminn :)
