### ISSUE TITLE
[Add a Play]: Audio Visualizer

### ISSUE THREAD

**Issue by shhmag** [reactplay/react-play#822]
### What's the Play about?

A straightforward audio visualizer that depicts sounds using wave spectrum .

### What ReactJS concept will be used to create this play?

p5.js, React hooks (useState, useEffect etc)

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CulturalProfessor** [comment]
Hey @DyingintheDarkness can you assign this issue to me.

**Comment by DyingintheDarkness** [comment]
@atapas Hello, I haven't been assigned this issue yet, but I would like to implement it.

**Comment by atapas** [comment]
> @atapas Hello, I haven't been assigned this issue yet, but I would like to implement it.

I see, no worries, please start implementing it. It's even better to have 2 implementation of same idea at times. I'll add you as assignee too.
