### ISSUE TITLE
✨ [Feature request]: Need to update twitter thumbnails 

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#824]
### Is your feature request related to a problem? Please describe.

The twittter thumbnails are a little back dated now. Need to replace those with more recent mentions.

### Describe the solution you'd like.

Upddate the mention ids.

### Describe alternatives you've considered.

Dynamic thumb creation. (Not as per this issue)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yung-coder** [comment]
Hey @koustov i would like to work on this issue....

**Comment by atapas** [comment]
> Hey @koustov i would like to work on this issue....

Hey this is scheduled for the codepeak event. Are you taking part in it?

**Comment by sidling1** [comment]
I would like to work on it

**Comment by atapas** [comment]
> I would like to work on it

Hi @sidling1 Are you taking part in CodePeak 2022? https://www.codepeak.tech/register

**Comment by yung-coder** [comment]
> > Hey @koustov i would like to work on this issue....
> 
> Hey this is scheduled for the codepeak event. Are you taking part in it?

Yeah i have participated @atapas
