### ISSUE TITLE
✨ [Feature request]: Dynamic Twitter thumbnail

### ISSUE THREAD

**Issue by yung-coder** [reactplay/react-play#832]
### Is your feature request related to a problem? Please describe.

No this feature is not related to any problem it is  for  getting  twitter thumbs dynamically 

Suggested by @koustov 

### Describe the solution you'd like.

We can get recently  mentioned tweets through twitter API and can update it dynamically.

### Describe alternatives you've considered.

Alternatives can be to get  recent  mentions  from the twitter handle as we do  now. 

### Additional context

I would like to work on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@yung-coder How are we planning to solve this?

**Comment by yung-coder** [comment]
> @yung-coder How are we planning to solve this?


@atapas 

We can get recently mentioned tweets from reactplay Twitter's handel by using Twitter api and extract twitter id form that and then we can show them on frontend.


Refer this:-

https://oauth-playground.glitch.me/?id=usersIdMentions&params=%28%27query%21%28%29%7Ebody%21%27%27%7Epath%21%28%27*%7E**id%21%272244994945%27%29%01*_

**Comment by ayushi0809** [comment]
Hi, Can I work on this feature?

**Comment by yung-coder** [comment]
hey @atapas  should i  start on this one ...?
