### ISSUE TITLE
🐛 [Bug report]: Motivate Play filter dropdown is not showing the applied filter label

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/react-play#836]
### Descrcibe the bug?

Motivate Play filter dropdown is not showing the applied filter label.

https://reactplay.io/plays/hat52/motivate-me

### Steps to reproduce the bug?

- Visit https://reactplay.io/plays/hat52/motivate-me
- Apply the author filter and it shows the `All` instead of the applied filter label.
![image](https://user-images.githubusercontent.com/59080942/208230292-b3cd58c9-d2bc-41a5-9240-ed1466aa983f.png)

### Expected behavior

Motivate Play filter dropdown should show the applied filter label.

### Desktop (Please provide your system information)

Browser [e.g. chrome]

### Screenshot / Screenshare

![image](https://user-images.githubusercontent.com/59080942/208230292-b3cd58c9-d2bc-41a5-9240-ed1466aa983f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joeshajan** [comment]
Hey, @Sachin-chaurasiya I would like to work on this issue. Can you assign this to me?

**Comment by Sachin-chaurasiya** [comment]
> Hey, @Sachin-chaurasiya I would like to work on this issue. Can you assign this to me?
> 

Hello @joeshajan , Assigned to you.
