### ISSUE TITLE
[Add a Play]: Tenzies Game 

### ISSUE THREAD

**Issue by AbhiPatel10** [reactplay/react-play#840]
### What's the Play about?

Tenzies Game using React.Js

### What ReactJS concept will be used to create this play?

react
react-confetti

Image:

![image](https://user-images.githubusercontent.com/76242769/209009038-7a6ea72c-a68f-48ba-81f6-276ce520f8cf.png)

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@AbhiPatel10 Super!!

Get started. If you need any help, ping us on Discord #needs-help channel

**Comment by AbhiPatel10** [comment]
Thanks a lot sir, this is my first contribution to reactplay I will give my 100%.
