### ISSUE TITLE
🐛 [Bug report]: Not Redirect to 404 Page

### ISSUE THREAD

**Issue by AbhiPatel10** [reactplay/react-play#847]
### Descrcibe the bug?

If We enter wrong route then it's not redirect to 404 page.

### Steps to reproduce the bug?

Enter anything in route path which is not mentioned in routing and give enter.

It Look like this.

![image](https://user-images.githubusercontent.com/76242769/209477928-bee36bc1-bc0b-4ae4-af17-2e8da4dcc58a.png)

### Expected behavior

It's Should Look Like this.

![image](https://user-images.githubusercontent.com/76242769/209477940-8c005c6a-bb13-47b3-ab33-2a5947634a01.png)

### Desktop (Please provide your system information)

Windows
Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Angryman18** [comment]
i will review this.
