### ISSUE TITLE
🐛 [Bug report]: Minified MUI error on click Filter 

### ISSUE THREAD

**Issue by AbhiPatel10** [reactplay/react-play#849]
### Descrcibe the bug?

When we click on filter icon second time It generate error like this. 

![image](https://user-images.githubusercontent.com/76242769/209478875-1f2f48ef-0fd2-450a-a193-e3ff3808fa19.png)

### Steps to reproduce the bug?

go to browse (plays) Click on Filter Icon then Close The Popup.

Then click a second time, and the error appears as shown in the image above. 

### Expected behavior

Should not give error when we open Filter popup.

### Desktop (Please provide your system information)

windows
chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@AbhiPatel10 do you want to fix it?

**Comment by AbhiPatel10** [comment]
My college exam is nearby, so I will not be able to work on this.

Anyone can go ahead. 😇

**Comment by Sachin-chaurasiya** [comment]
@atapas , I will work on this.
