### ISSUE TITLE
🐛 [Bug report]:  404 Page should redirect to home page

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#855]
### Descrcibe the bug?

There are two issues
1. Currently 404 page says `Why don't you go back to home.. Redirecting in X sec.`. This is misleading as automatic redirection takes to `/plays` instead of home page
2. The text `home` should be hyperlinked with home page

### Steps to reproduce the bug?

1. Go to `reactplay.io`
2. Manullu update the url to something that doesn't exist in route table

### Expected behavior

As described in description

### Desktop (Please provide your system information)

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhishek-90** [comment]
I would like to take it up.

**Comment by AbhiPatel10** [comment]
@atapas sir, I would like to work on this issue.

**Comment by atapas** [comment]
> @atapas sir, I would like to work on this issue.

@Abhishek-90 Please confirm if this is being worked and there is a PR?

**Comment by AbhiPatel10** [comment]
This is just a small change so should I proceed?

**Comment by Abhishek-90** [comment]
I have raised a PR for my changes, it ie currently in review @atapas @AbhiPatel10

**Comment by AbhiPatel10** [comment]
Okay no problem, @koustov sir has commented on your PR Please solve that so Your PR Will Merge.

**Comment by atapas** [comment]
> I have raised a PR for my changes, it ie currently in review @atapas @AbhiPatel10

Hi @Abhishek-90 there is a review comment. please take care.
