### ISSUE TITLE
✨ [Feature request]: Show the Play creation date in the play page

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#862]
### Is your feature request related to a problem? Please describe.

Right now the play page doesn't show when the play was created. Could you show the play creation date?

### Describe the solution you'd like.

The play creation date should be in the header where we show other meta data like who created the paly, photo etc.

The date must be,
- Formatted properly
- Must be locale-aware to the browser.

### Describe alternatives you've considered.

None

### Screenshot / Screenshare

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/3633137/211459681-432c3d7a-c582-44fa-b361-b34b6107dcde.png">

### Additional context

We already use the date-fns library. Please utilize that for the formatting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankitk26** [comment]
Hi @atapas , I would like to work on this feature

**Comment by Sachin-chaurasiya** [comment]
@ankitk26, Assigned to you.

**Comment by ankitk26** [comment]
Is the position and format of the date fine?


![image](https://user-images.githubusercontent.com/53444460/211642293-402d8158-a99c-4f03-845f-269011197b2e.png)

**Comment by Sachin-chaurasiya** [comment]
> Is the position and format of the date fine?
> 
> ![image](https://user-images.githubusercontent.com/53444460/211642293-402d8158-a99c-4f03-845f-269011197b2e.png)

Thanks, @ankitk26, I think we should keep the date on the right side below the play description.

**Comment by ankitk26** [comment]
I have placed the date below the description of the play.

![image](https://user-images.githubusercontent.com/53444460/211742736-1138ae90-bd10-467e-b7dc-cf4fbd9adbc9.png)

**Comment by atapas** [comment]
> > Is the position and format of the date fine?
> > ![image](https://user-images.githubusercontent.com/53444460/211642293-402d8158-a99c-4f03-845f-269011197b2e.png)
> 
> Thanks, @ankitk26, I think we should keep the date on the right side below the play description. cc : @atapas

Tagging @nirmalkc to take the call... The current place is not intuitive for sure.

**Comment by atapas** [comment]
@nirmalkc Could you please suggest the design?

**Comment by nirmalkc** [comment]
### Option #1
![image](https://user-images.githubusercontent.com/6359059/213969003-cde43d87-d785-4678-8d88-c9971b4ee917.png)

**Comment by nirmalkc** [comment]
### Option #2
![image](https://user-images.githubusercontent.com/6359059/213969604-ba84878f-34d7-4678-84a3-bed5cd18f85f.png)

**Comment by nirmalkc** [comment]
@atapas please share your thoughts

**Comment by atapas** [comment]
> @atapas please share your thoughts

I liked Option 2. We do not need the info now. just a dot separator with name is good.

@ankitk26 FYI.. Hope you can get it done now?

**Comment by ankitk26** [comment]
> > @atapas please share your thoughts
> 
> I liked Option 2. We do not need the info now. just a dot separator with name is good.
> 
> @ankitk26 FYI.. Hope you can get it done now?

Sure

**Comment by ankitk26** [comment]
![image](https://user-images.githubusercontent.com/53444460/214382865-e61904b5-0b91-4499-b16e-eea4c6a18760.png)

I added the date with the dot separator. Should I keep the description as it is on the right side?

**Comment by atapas** [comment]
> ![image](https://user-images.githubusercontent.com/53444460/214382865-e61904b5-0b91-4499-b16e-eea4c6a18760.png)
> 
> I added the date with the dot separator. Should I keep the description as it is on the right side?

Hi @ankitk26 Can I please get the PR for this one?
