### ISSUE TITLE
✨ [Feature request]: Use OpenAI API to generate React.js based Project Ideas

### ISSUE THREAD

**Issue by mayukh551** [reactplay/react-play#863]
### Is your feature request related to a problem? Please describe.

We need more ideas to create React.js projects, and more the no. of ideas, the better for aspiring React Developers.
For generating random ideas, OpenAI API can be used to generate 10 unique random React.js project ideas.

### Describe the solution you'd like.

Using OpenAI API of text completion, token key and model 'text-davinci-003' with randomness set to 0.9 (low: 0, high: 1)

### Describe alternatives you've considered.

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamkelv** [comment]
@mayukh551 is this issue still open
