### ISSUE TITLE
🐛 [Bug report]: Fix the Cypress test fail issue

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#866]
### Descrcibe the bug?

Now the Cypress test fails due to the Tweet card validation. Please fix it.

### Steps to reproduce the bug?

Run the Cypress build locally or see any preview build for the error log.

### Expected behavior

All tests should pass

### Desktop (Please provide your system information)

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShaileshParmar11** [comment]
Hi, i would like to pick this one!

**Comment by Tonie-NG** [comment]
Hi @atapas . I would love to take this up. Can you explain more about the issue?
