### ISSUE TITLE
[Typo]: Redundant classnames in components

### ISSUE THREAD

**Issue by aimunhidden485** [reactplay/react-play#868]
### What's the Play about?

I have identified that there are multiple classnames that are being used in multiple components that are repetitive. This is causing a  redundancy in our codebase,

solution:
-Removing the redundant classnames , this will make sure that we have dry codebase

### What ReactJS concept will be used to create this play?

nothing

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Can you please add more details in the title and description?

**Comment by aimunhidden485** [comment]
I've updated the title and description.
