### ISSUE TITLE
✨ [Feature request]: Add banner feature to playlist page

### ISSUE THREAD

**Issue by aimunhidden485** [reactplay/react-play#873]
### Is your feature request related to a problem? Please describe.

As a user, I want to be able to see a dynamic banner on the playlist page that will display a random playthumbnail from all the plays

### Describe the solution you'd like.

+ The banner should be prominently displayed at the top of the playlist page
+ The banner should be able to contain text, images, and links
+ Whenever the page reloads, it would have a different banner.

### Describe alternatives you've considered.

no response

### Screenshot / Screenshare

![image](https://user-images.githubusercontent.com/96931784/212354510-e9417e4e-cd92-4acd-9ce4-4af2996eb465.png)

### Additional context

no response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Hey @aimunhidden485 Seems interesting, but I am not able to get the feature completely. Is it possible for you to do a sketch for ReactPlay(a very basic one) and post it? We can chat too.

**Comment by aimunhidden485** [comment]
@atapas Sure. I made a figma design https://www.figma.com/file/eTaATA9LQLoPdzkPsa98SX/Untitled?node-id=0%3A1


> The backgound image will be the playthumbnail

> The name of the game will appear at the top.

> And a description will show up below the game title

**Comment by atapas** [comment]
> @atapas Sure. I made a figma design https://www.figma.com/file/eTaATA9LQLoPdzkPsa98SX/Untitled?node-id=0%3A1
> 
> 
> 
> 
> 
> > The backgound image will be the playthumbnail
> 
> 
> 
> > The name of the game will appear at the top.
> 
> 
> 
> > And a description will show up below the game title

Can we auto generate it?

**Comment by aimunhidden485** [comment]
@atapas Each time the page loads, it will display a randomized banner from all the plays

**Comment by atapas** [comment]
> @atapas Each time the page loads, it will display a randomized banner from all the plays

Got it but how will you generate that?

**Comment by aimunhidden485** [comment]
> > @atapas Each time the page loads, it will display a randomized banner from all the plays
> 
> Got it but how will you generate that?

I'll do it by using Math. Random function. It will generate a random index from plays array.

**Comment by atapas** [comment]
> > > @atapas Each time the page loads, it will display a randomized banner from all the plays
> > 
> > 
> > Got it but how will you generate that?
> 
> I'll do it by using Math. Random function. It will generate a random index from plays array.

Sure go ahead. I am curious.
