### ISSUE TITLE
🐛 [Bug report]: Deletion of unused files

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#874]
### Descrcibe the bug?

this is not actually any bug but what i see is some of the files which are imported in different other files has no use. for example we have import `index.css` in the index.js file but the index.css file is actually empty. also `setupTests.js` file which is never used anywhere and `reportWebVitals.js` also might be. so my question is can we actually remove these files or they are covering some specefic need? if not then i think we should remove them.

### Steps to reproduce the bug?

--

### Expected behavior

--

### Desktop (Please provide your system information)

--

### Mobile (Please provide your device information)

--

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@Angryman18 Are you picking it up?

Also suggest the path of the files to remove.
