### ISSUE TITLE
✨ [Feature request]: Twitter Community Section is taking up a lot of space

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#891]
### Is your feature request related to a problem? Please describe.

The Twitter Community section is taking up a lot of space in mobile view. As you can see here in the video. To get to the footer, users must scroll a long way and if we want to add more tweets in the future, it will need more space.

https://user-images.githubusercontent.com/91705825/213924080-168de3b7-9ef5-4bdc-83c6-b0422bd8a29d.mp4

### Describe the solution you'd like.

Instead of that, we can use a carousel slider for the mobile view which automatically slides or the user can also slide it to view. 

### Describe alternatives you've considered.

We can do something like this👇

https://user-images.githubusercontent.com/91705825/213924711-c8855687-ecfb-4edb-834a-d1f396e2669f.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
I loved the idea. Do you want to implement it @Shivam-Katare ?

**Comment by Shivam-Katare** [comment]
Yes @atapas I am ready to implement it.

**Comment by atapas** [comment]
Assigned @Shivam-Katare

**Comment by atapas** [comment]
@Shivam-Katare We will be getting away with the Twitter section. Instead we are coming up with this one.

https://github.com/reactplay/react-play/issues/955

Your carousel work will still be relevant with the new ideas too. Please keep an eye.
