### ISSUE TITLE
🐛 [Bug report]: Child pages show the home page for a fraction and then renders actual content. 

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#894]
### Descrcibe the bug?

Child pages show the home page for a fraction and then renders actual content. 

I have validated against `plays`  and `leaderboard` page. Need to check all other pages as well

### Steps to reproduce the bug?

1. Goto `reactplay.io`
2. Click on `Browse`
3. or click on `Leaderboard` icon

### Expected behavior

The intended page should be rendered immediately. If required common loading spinner needs to be introduced

### Desktop (Please provide your system information)

Desktop browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anmol567** [comment]
The issue is not getting reproduced kindly share some more context.

**Comment by atapas** [comment]
I can't reproduce this one. Do I need to disable cache and enable network throttling to test? Can you record the screen and attach?

**Comment by atapas** [comment]
@koustov Do you still see this issue?
