### ISSUE TITLE
🐛 [Bug report]: Banner visibility not correctly controlled by search filter

### ISSUE THREAD

**Issue by aimunhidden485** [reactplay/react-play#896]
### Descrcibe the bug?

When the search filter is applied, the banner should be hidden, but it is still visible. This bug occurs when the search filter is applied and should be fixed so that the banner is correctly hidden when the search filter is active

### Steps to reproduce the bug?

1. Go to  [https://reactplay.io/plays]()
2. Apply the search filter 
3. Observe that the banner is still visible on the page, even though the search filter has been applied.

### Expected behavior

The banner should not be visible if the search filter applied

### Desktop (Please provide your system information)

no response

### Mobile (Please provide your device information)

no response

### Screenshot / Screenshare

![image](https://user-images.githubusercontent.com/96931784/214762736-7912519a-57fb-4d86-9c04-62236a7a8e8a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@koustov I think you are working on it already?

**Comment by koustov** [comment]
> @koustov I think you are working on it already?

Yes, this has already been considered in one of my local branch. Will create a PR soon

**Comment by priyankarpal** [comment]
Since there haven't been any updates, we can move forward with closing this issue.
