### ISSUE TITLE
[#2PlaysAMonth]: Roll the dice

### ISSUE THREAD

**Issue by wyarejali** [reactplay/react-play#899]
### What's the Play about?

Roll the dice is a game that will play you VS computer. Where you can roll the dice as many times as you want then add the points to the main cart if you got 🎲 "1" during roll the dice you will lose points and then computer will roll dice.
If you collect 100 points first before computer, you win 🏆 otherwise you loose 😪

### What ReactJS concept will be used to create this play?

useState, useEffect, Hooks, 

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Do you target this play for the #2PlaysAMonth event? @wyarejali
