### ISSUE TITLE
🐛 [Bug report]: Server run break locally on Windows due to linting error.

### ISSUE THREAD

**Issue by ANKIT9761** [reactplay/react-play#903]
### Descrcibe the bug?

So when we fork this repo and run the server on windows machine it throws error due to eslint demanding to delete cr files.
And this results in server breaking and the server fails to start.

### Steps to reproduce the bug?

1- Fork the repo and clone it on windows machine.
2- Install the packages using npm.
3- Start the server and it will through the error.

### Expected behavior

It Should start the server and then we can start with the creation of our play.

### Desktop (Please provide your system information)

- OS: Windows
- Browser: Edge
Version 109.0.1518.70

### Screenshot / Screenshare

![Screenshot (108)](https://user-images.githubusercontent.com/35369589/215642042-c91c8791-28b6-4d39-8873-88efe7233077.png)
![Screenshot (109)](https://user-images.githubusercontent.com/35369589/215642049-b282b635-bafe-42a3-9723-fe77d055813a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@ANKIT9761 Don;t forget a title while creating issues :)
