### ISSUE TITLE
[Add a Play]: Two Plays A Month Demo

### ISSUE THREAD

**Issue by koustov** [reactplay/react-play#907]
### What's the Play about?

ReactPlay brings you an opportunity to participate in the month-long drive to learn and contribute to Open Source

### What ReactJS concept will be used to create this play?

Standard

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
any update?  @koustov
