### ISSUE TITLE
[#2PlaysAMonth]: Image Gallery - Create a responsive image gallery by using the free Unsplash API

### ISSUE THREAD

**Issue by siddhantsiddh15** [reactplay/react-play#910]
### What's the Play about?

Image Gallery - Create a responsive image gallery by using the free Unsplash API

### What ReactJS concept will be used to create this play?

Hooks, State management, Conditional rendering, Promises, useEffect

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Nice!
