### ISSUE TITLE
Lets include yarn installation process in readme file

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#912]
### Is your feature request related to a problem? Please describe.

Since we strongly recommend people use yarn and most of the folks are having same issue regarding installation of node modules.. some folks are not aware of yarn installation process also so let us include yarn installation process on mac, windows & linux on our readme file and that would help new people installing the modules and we can have less issue coming in discord related to node_module installation error and npm error

### Describe the solution you'd like.

As above 

### Describe alternatives you've considered.

As above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@Angryman18 Also, I think we should emphasise yarn as our default choice for dependency installation. npm can be a fallback.

**Comment by hasnainmakada-99** [comment]
Sounds good to me @atapas sir and @Angryman18
