### ISSUE TITLE
[#2PlaysAMonth]: Customizable College Curriculum Manager

### ISSUE THREAD

**Issue by nileshkr17** [reactplay/react-play#913]
### What's the Play about?

Title: "Customizable College Curriculum Manager"

Objective: The goal of this project is to create an interactive, user-friendly application that allows college students to manage their earned credits and create a customized course flow based on those credits.

The application will allow students to view their current credit balance and track their progress toward their degree. Students can search for courses offered by the college and view details about each course, including the number of credits it awards and the prerequisites required.

They can then add courses to their custom curriculum and arrange them in a personalized order that best fits their schedule and learning goals. The application will provide a visual representation of the student's progress and highlight any prerequisites that need to be fulfilled before they can take certain courses. Students will be able to collaborate with peers, share their custom curriculum with classmates, and receive feedback from instructors.
The application will be designed to be accessible and responsive on a variety of devices, including desktops, laptops, and mobile devices.

### What ReactJS concept will be used to create this play?

This React project will be developed using the following technologies:
React.js
ReactFlow
JavaScript
HTML/CSS
A backend database for storing and retrieving data about students, courses, and curricula.
APIs for fetching course information and other relevant data from the college's systems.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Very interesting idea.
