### ISSUE TITLE
[#2PlaysAMonth]:  Code Snippets

### ISSUE THREAD

**Issue by AbdulMuheeth** [reactplay/react-play#916]
### Code Snippets

Description: A collection of code snippets which allows you to copy and paste your code snippet and lets you download it as an image to share!

### What ReactJS concept will be used to create this play?

Context API, Hooks, React Router.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Very cool idea.
