### ISSUE TITLE
install dependencies issues [bug]: 

### ISSUE THREAD

**Issue by Sandivsv** [reactplay/react-play#921]
### What's the Play about?

sir, I have faces defficulty on installing dependencies, It gives error. what can I do now ?? 

![image](https://user-images.githubusercontent.com/72245997/216156975-76238bd2-48d8-41ce-9192-6123a7edc31c.png)

### What ReactJS concept will be used to create this play?

Now,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sandivsv** [comment]
I also used this command "npm install --legacy-peer-deps" to install but we got this ........

![image](https://user-images.githubusercontent.com/72245997/216162131-929d5cdc-c125-4200-99cb-9d155a905e0f.png)

**Comment by atapas** [comment]
Hey @Sandivsv please take a look into the readme. 

- Make sure you have correct Node version(16.x)
- If npm install doesn’t work, try 
npm install --legacy-peer-deps
- We highly recommend using yarn. You can install it easily.

If any of these doesn’t work, give us the screenshot of the yarn install log so that we can guide you on missing steps. But yeah, follow the readme carefully.

**Comment by atapas** [comment]
For a more faster resolution of this kind of issue, join discord where folks are resolving it collaboratively.

**Comment by atapas** [comment]
@Sandivsv Have you tried the steps?

**Comment by Sandivsv** [comment]
Yes sir I install yarn and using this all dependencies have been installed. But we are getting one more issue of incorrect path when we start run, like this 

![image](https://user-images.githubusercontent.com/72245997/216570201-4d967852-5e3a-463d-9a15-f4c86e77846a.png)

**Comment by atapas** [comment]
> Yes sir I install yarn and using this all dependencies have been installed. But we are getting one more issue of incorrect path when we start run, like this 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/72245997/216570201-4d967852-5e3a-463d-9a15-f4c86e77846a.png)
> 
> 

We fixed that and also posted about it on Discord #2playsamonth channel.

You just need to pull the latest from upstream and do a yarn install to fix it.

**Comment by Sandivsv** [comment]
It's all good now, sir. Thanks.
