### ISSUE TITLE
[#2PlaysAMonth]: Content Moderation Analyzer

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [reactplay/react-play#922]
### What's the Play about?

Build an app to visualise moderated image stored in S3 bucket using Amazon Rekognition.

### What ReactJS concept will be used to create this play?

useEffect, useState, Hooks ( will add more along the way as I build the project)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Great idea @ShreyaPrasad1209. Looking forward to get it built.
