### ISSUE TITLE
[#2PlaysAMonth]: A React Tetris Game

### ISSUE THREAD

**Issue by PapayaHUANG** [reactplay/react-play#923]
### What's the Play about?

The classic one-player Tetris game.
It is more common to build game with vanillaJS, but i want to create it in react to see what I can do.

### What ReactJS concept will be used to create this play?

React hooks, Redux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Super cool ✌️

**Comment by PapayaHUANG** [comment]
Actually I have made one react tetris game:
https://github.com/PapayaHUANG/react-redux-tetris
(but after the deadline)
Should I make a PR and include it to this repo? @atapas

**Comment by atapas** [comment]
> Actually I have made one react tetris game: https://github.com/PapayaHUANG/react-redux-tetris (but after the deadline) Should I make a PR and include it to this repo? @atapas

Yes! Please follow the steps here to create a project on ReactPlay.. If you face issues, we are having our community call tomorrow on Discord, please attend,

https://docs.reactplay.io/How-To-Guides/how-to-create-play
