### ISSUE TITLE
[#2PlaysAMonth]: Text Analyzer

### ISSUE THREAD

**Issue by yung-coder** [reactplay/react-play#924]
### What's the Play about?

A Adv text analyzer that will help you  analyze your text and tell to do certain modifications and error correction and  text extraction from images and  a lot more.

### What ReactJS concept will be used to create this play?

Hooks  (will add more in the process of building it)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Nice idea!
