### ISSUE TITLE
[#2PlaysAMonth]: TeeRex Store

### ISSUE THREAD

**Issue by Adityakadali** [reactplay/react-play#925]
### What's the Play about?

A simple webapp where customers can browse through the catalog of t-shirts, add t-shirts to the shopping cart and checkout the items in the cart.  

### What ReactJS concept will be used to create this play?

Components, React Router, UseState, UseEffect

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Nice! Are you also planning any payment gateway integration?
