### ISSUE TITLE
[#2PlaysAMonth]: A Sports Platform with Cricket and Football Updates

### ISSUE THREAD

**Issue by kumarvinayak490** [reactplay/react-play#926]
### What's the Play about?

This platform will use free APIs available on internet to build a platform which will have fixtures details 

### What ReactJS concept will be used to create this play?

Hooks, React Router, Fetching Data, 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Good idea 👍
