### ISSUE TITLE
[#2PlaysAMonth]:  Dad Jokes

### ISSUE THREAD

**Issue by Bobby-coder** [reactplay/react-play#930]
### What's the Play about?

Dads Jokes app is a web app which shows the funny dad jokes. User can upvote and downvote any joke.

### What ReactJS concept will be used to create this play?

Functional component, useState, useEffect, Dad Jokes API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Dad Jokes! That's something new. Excited to see this one.
