### ISSUE TITLE
[#2PlaysAMonth]: focastra

### ISSUE THREAD

**Issue by Prashantrajput11** [reactplay/react-play#933]
### What's the Play about?

**focastra is a web app, basically a super tool to focus better.**

 It is a combination of two words focus and astra ( tool). Hence the name focAstra.

-  This tool will be having basic features that can make you more productive at your next task. 
- Such as todo app(**p1 feature**) , pomodro (**p1 feature**)to let you get into flow and then get a break.
-  Accountabilty (**p1 feature**) feature to keep you accountable. A score card (p2 feat) to get points.
-  A meditation feature (**p3 feature**) that would show list of meditations and steps to  help you focus between long working hours.
- asmr sounds feature (**p3 feature**) ( if time permits) to relax your mind

### What ReactJS concept will be used to create this play?

Components, react hooks, react router, context Api

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
focastra sounds promising.
