### ISSUE TITLE
[#2PlaysAMonth]: React Cart Management

### ISSUE THREAD

**Issue by SoumyadeepOSD** [reactplay/react-play#934]
## React Cart Management

# Hey Everyone👋

## In this React Play I'm going to make a Shopping Cart Application that contains Beautiful UI designs along with proper state management while moving the items from Home Page to Cart and Vice versa. Attractive icons and animations will also be there.

<h3>Hope it will create a little amount of value in the community</h3>

<h3>Thankyou✔️</h3> 

### What ReactJS concept will be used to create this play?

# In this React Play I'll use
-  <h3>ReactRouterDom</h3> 👉 <h2>For routing different pages</h2>
- <h3>ReduxToolkit</h3>  👉 <h2>to enable the state management of the Project</h2>
- <h3>ReactComponents</h3>  👉 <h2>for User Interface</h2>
  

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Great. @SoumyadeepOSD can you please update the title?

**Comment by SoumyadeepOSD** [comment]
> Great. @SoumyadeepOSD can you please update the title?

@atapas  I recently updated the title✌️ Thanks for informing about it

**Comment by SoumyadeepOSD** [comment]
@atapas  I got so many errors while making the project in the reactplay. Can I change the subject of this issue and make a new Play ?
