### ISSUE TITLE
🐛 [Bug report]: Create a play page not expanding to full height

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [reactplay/react-play#935]
### Descrcibe the bug?

The form is not expanding to full height; instead, it covers a very small height, as shown below. 

![image](https://user-images.githubusercontent.com/43600306/216626232-78003148-2db9-4eab-865f-b09a74cdf63c.png)

### Steps to reproduce the bug?

1. `yarn start` to fire up the application locally
2. Click 'Create'
3. The form opens up

### Expected behavior

It should open up as show in this screenshot posted [here](https://github.com/reactplay/react-play/blob/main/CREATE-PLAY.md)

### Desktop (Please provide your system information)

**OS:** Apple M2 Ventura 13.1
**Browser:** Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@ShreyaPrasad1209 is there a scroll bar appear that allow you to navigate some way?

Do you have a bigger monitor to test it if it opens better there?

**Comment by ShreyaPrasad1209** [comment]
I have to explicitly click on the scroll bar to navigate. This happened on my 24-inch monitor.

**Comment by atapas** [comment]
Got it. Thanks for reporting it. We will fix it soon but I hope you are able to make progress with play creation for now!

**Comment by ShreyaPrasad1209** [comment]
I can take up this issue if you want. Yes I'm filling up the form but the experience could be a lot better 🙈
