### ISSUE TITLE
[#2PlaysAMonth]: ChatAppUsingFirebase

### ISSUE THREAD

**Issue by Aarize29** [reactplay/react-play#937]
### What's the Play about?

In this project, I will be developing a live chat app using firebase as backend with full authentication system 
User can signIn using there google accounts and can have real time chats with other users(Just like youtube live chats).

### What ReactJS concept will be used to create this play?

Hooks:-I will be using Hooks like useState, useNavigate, useEffect.
Components:- To make code easy to study, I will be dividing my application in few components 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Looking forward to it.
