### ISSUE TITLE
[#2PlaysAMonth]: QA forum

### ISSUE THREAD

**Issue by vrx29** [reactplay/react-play#940]
### What's the Play about?

QA Site is a web app where you can post your questions and users can add answers to them. There will be an option to upvote and downvote also there will be an option to accept the answer for the user who has posted the question.

### What ReactJS concept will be used to create this play?

Functional Components, Hooks eg: useState, useEffect, React Router

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Nice!
