### ISSUE TITLE
🐛 [Bug report]: Add concurrency groups to all of the workflows, So that failure rate is low

### ISSUE THREAD

**Issue by hasnainmakada-99** [reactplay/react-play#953]
### Descrcibe the bug?

I would like to analyze all the GH-actions workflow and then add concurrency groups to all of the workflows. This will help in reducing the failure of workflows and will queue them all in a group

### Steps to reproduce the bug?

None

### Expected behavior

Expected behaviour will increase the time in running of the workflows as it will queue them all and will run one by one

### Desktop (Please provide your system information)

OS: Windows
Browser: Brave
Version: 1.48

### Mobile (Please provide your device information)

None

### Screenshot / Screenshare

Here is an example of the workflow which is not grouped under a single concurrency
![image](https://user-images.githubusercontent.com/82728823/217997728-53697b10-980a-48d0-9b49-23b3251a1cff.png)

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@hasnainmakada-99 Do you want to take it up?

**Comment by hasnainmakada-99** [comment]
Yes i'll take it up @atapas sir
