### ISSUE TITLE
[#2PlaysAMonth]: Emoji guess game

### ISSUE THREAD

**Issue by rashy10** [reactplay/react-play#954]
### What's the Play about?

The user will be given a list of emoji to select from.The emojis would be split in 3 row the user has to pick from the 3 times , now the game will display the card 

### What ReactJS concept will be used to create this play?

useState, 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by rashy10** [comment]
I installed everything now when I am npm start it ,this is the issues popping up:

  6:1   error  Delete `␍⏎`
                                                                                              prettier/prettier
  14:9   error  Insert `··`
                                                                                              prettier/prettier
  16:32  error  Delete `··`
                                                                                              prettier/prettier
  18:71  error  Replace `␍⏎··············Pellentesque·euismod,·urna·eu·tincidunt·consectetur,␍⏎··············nisi·nunc·ultricies·nisi,·eget·consectetur·nunc·nisi` with `·Pellentesque·euismod,·urna·eu␍⏎··············tincidunt·consectetur,·nisi·nunc·ultricies·nisi,·eget·consectetur·nunc·nisi·euismod`  prettier/prettier
  21:14  error  Delete `·euismod`
                                                                                              prettier/prettier
  24:1   error  Insert `··`
                                                                                              prettier/prettier
  31:31  error  Insert `␍⏎`
                                                                                              prettier/prettier

✖ 7 problems (7 errors, 0 warnings)
  7 errors and 0 warnings potentially fixable with the `--fix` option.

**Comment by atapas** [comment]
Because of the lint error. Please follow the steps mentioned here to correct it

https://twitter.com/swapnakpanda/status/1623303136772513793?s=20&t=vUraBAU8cMyU-GxoS8XYGw

Please join our discord and post your queries on #needs-help channel for more real time updates.
