### ISSUE TITLE
✨ [Feature request]: Add Home Grown Testimonial for ReactPlay

### ISSUE THREAD

**Issue by atapas** [reactplay/react-play#955]
### Is your feature request related to a problem? Please describe.

It is not a problem. It's a feature request.

We have a section to post community speaks where we show static Tweets.

![image](https://user-images.githubusercontent.com/3633137/218072382-db91297b-b208-49ee-bc99-7dfa3339b237.png)

It doesn't scale due to the following reasons:

- The Tweets are driven by the static ids
- It renders slow
- Twitter is making their APIs priced to query these

Hence the proposal is to create the functionality of homegrown testimonials. 

### Describe the solution you'd like.

Here are the expectations:

- Provide an ability for users to authenticate and write testimonials about the platform.
- User should be able to select a category like `General`, and event name(`#2PlaysAMonth`, `Hack-R-Play`, etc) to provide the testimonial. If nothing selected, Geberal selects by default.
- Recent 10 testimonials should be shown on the home page where the tweets are shown now.
- Each testimonial should have the message, category, date, and the event name shown.
- There should be a link to take users to all testimonial page(/testimonials) route where all the testimonials must be listed in the date order(recent to old)
- Provide a filter on the testimonials page to filter by the events.

### Describe alternatives you've considered.

None.

### Screenshot / Screenshare

Shall Share some design thoughts in the next comment.

### Additional context

Talk to @atapas and @koustov for further discussions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Here is an idea for the testimonial page:

![image](https://user-images.githubusercontent.com/3633137/218082850-b61ffc49-a2c8-4d1e-a5a4-0e229c1897ea.png)

**Comment by 6km** [comment]
Interesting! ✨
I will be working on this ASAP

**Comment by atapas** [comment]
> Interesting! ✨
> 
> I will be working on this ASAP

Count me in if you need any help or got any questions. @koustov is doing the DB part but you can get started with UI with fake JSON data in the mean time.

**Comment by atapas** [comment]
@6km The tables are ready. Here is example fetch query

```gql
query MyQuery {
  testimonials {
    id
    quote
    user
    event
    user_id_map {
      avatarUrl
      displayName
    }
    event_map {
      name
    }
  }
}
```

The response to the above query:

```json
{
  "data": {
    "testimonials": [
      {
        "id": "1e19f639-be73-42bb-8387-ba89277b7d4c",
        "quote": "ReactPlay community is awesome. So glad to be part of it.",
        "user": "0680f581-6584-4bc4-bbe9-aa7c97567e72",
        "event": "95063183-6a29-4c34-b08e-10cb306ea29c",
        "user_id_map": {
          "avatarUrl": "https://avatars.githubusercontent.com/u/3633137?v=4",
          "displayName": "Tapas Adhikary"
        },
        "event_map": {
          "name": "General"
        }
      }
    ]
  }
}
```

**Comment by koustov** [comment]
> @6km The tables are ready. Here is example fetch query
> 
> ```graphql
> query MyQuery {
>   testimonials {
>     id
>     quote
>     user
>     event
>     user_id_map {
>       avatarUrl
>       displayName
>     }
>     event_map {
>       name
>     }
>   }
> }
> ```
> 
> The response to the above query:
> 
> ```json
> {
>   "data": {
>     "testimonials": [
>       {
>         "id": "1e19f639-be73-42bb-8387-ba89277b7d4c",
>         "quote": "ReactPlay community is awesome. So glad to be part of it.",
>         "user": "0680f581-6584-4bc4-bbe9-aa7c97567e72",
>         "event": "95063183-6a29-4c34-b08e-10cb306ea29c",
>         "user_id_map": {
>           "avatarUrl": "https://avatars.githubusercontent.com/u/3633137?v=4",
>           "displayName": "Tapas Adhikary"
>         },
>         "event_map": {
>           "name": "General"
>         }
>       }
>     ]
>   }
> }
> ```

I will be adding a title field as well and this will be mandatory

**Comment by 6km** [comment]
What do you think of this UI design?

![react-play-testimonials](https://user-images.githubusercontent.com/62352949/218320090-e89bedb8-74c2-419b-8ec3-232b593f2d1c.png)

**Comment by atapas** [comment]
> @koustov What do you think of this UI design?
> 
> ![react-play-testimonials](https://user-images.githubusercontent.com/62352949/218320090-e89bedb8-74c2-419b-8ec3-232b593f2d1c.png)

@koustov Do you have any further suggestion to this?

Also can we please add two more event details in the table?

- Twitter Spaces(No start and end date)
- ReactPlay Live(No start and end date)
