### ISSUE TITLE
🐛 [Bug report]: Error in play if play name contains hyphen 

### ISSUE THREAD

**Issue by yung-coder** [reactplay/react-play#966]
**Describe the bug**

Play will be created in plays folder  but it will not be shown in playlist section in local environment.  

**To Reproduce**
1. Go to create play 
2. Click on create
3. Enter play name with hyphen  in it 

**Expected behavior**

Play should be available in playlist section in local environment.

**Screenshots**

none

**Desktop (please complete the following information):**
 - OS:  Ubuntu 
 - Browser: Firefox
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**

I would  like to explore why this is happening and try to fix it.

**Comment by koustov** [comment]
This is webapp issue, so moved here
