### ISSUE TITLE
[#2PlaysAMonth]: A Mini version of A Picture Editing App

### ISSUE THREAD

**Issue by aghildev** [reactplay/react-play#975]
### What's the Play about?

The Play Is Actually A  Mini version of A Picture Editing App..Where We can try to improve our Editing Skills.This Web App Allows you to Play With The Almost All Filters Available in a Real Editing App..

### What ReactJS concept will be used to create this play?

Functional components: The PhotoshopApp component is a functional component that uses React hooks to manage state.

State and setState: The useState hook is used to create state variables selectedOptionIndex and options. setSelectedOptionIndex and setOptions are used to update their values.

Props: The props object is passed as a parameter to the PhotoshopApp function and used to render the PlayHeader component.

Conditional rendering: The Slider component is conditionally rendered using a ternary operator and selectedOption state variable.

Event handling: The handleSliderChange function is used to update the options state variable based on slider value changes.

Memoization: The useMemo hook is used to memoize the selectedOption and imageStyle variables, which can improve performance by preventing unnecessary re-renders.

Component composition: The SidebarItem and Slider components are used as child components of PhotoshopApp.

CSS styling: CSS modules are used to import styles from a separate styles.css file and apply them to the components.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
@aghildev , please give some title to issue.
