### ISSUE TITLE
✨ [Feature request]: Search plays parallelly with typing

### ISSUE THREAD

**Issue by ankitk26** [reactplay/react-play#978]
### Is your feature request related to a problem? Please describe.

It would be better to get the search results as we type in the search box. It is just related to the UX part of the website.
To get back all the plays, one has to refresh the page or clear the search box and hit enter. Instead, the user can clear the text in the search box and all the plays are displayed back.

### Describe the solution you'd like.

One solution could be to filter the search results on change of the text in search box.
We can add a debounce function over the onChange function to display the search results after a small delay to avoid frequent function calls on every character change.the 

### Describe alternatives you've considered.

One alternative would be to simply call the handleSearch function on every character change. 
Or there could be a clear icon button at the end of the search box to get back all the plays without refreshing the page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShaileshParmar11** [comment]
Hello, has anyone thought about this issue? do we have a plan to add this functionality?

**Comment by haddercone** [comment]
Hi @ankitk26 @ShaileshParmar11 , I believe this feature would be good from the UX perspective. 
If we proceed with this, I would like to work on it.
Thanks :)

**Comment by janvi01** [comment]
Hey @atapas I would like to work on this, Please assign me.
