### ISSUE TITLE
🐛 [Bug report]: Layout shifiting

### ISSUE THREAD

**Issue by shrilakshmishastry** [reactplay/react-play#981]
### Descrcibe the bug?

![image](https://user-images.githubusercontent.com/29778698/219828268-23431ea6-3148-46de-893b-18aac2dad2b4.png)
here if you click on username layout shifts due to addition of border.

### Steps to reproduce the bug?

It's in play page

### Expected behavior

Layout shouldn't shift

### Desktop (Please provide your system information)

mac , firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
@shrilakshmishastry is it happening for only this play or a generic issue?

**Comment by shrilakshmishastry** [comment]
in general to all page, this can be fixed giving border white and on hover changing it

**Comment by atapas** [comment]
> in general to all page, this can be fixed giving border white and on hover changing it

Will you fix it?

**Comment by rahulpandey70** [comment]
Hey @atapas, If no one is working on this issue, Please assign me.
