### ISSUE TITLE
[2PlaysAMonth]: Notes App

### ISSUE THREAD

**Issue by afreen0102** [reactplay/react-play#989]
### What's the Play about?

This Play is made using React JS and Django. This Play can Create, Update and Delete Notes from the App. The App also stores Created and Updated dates automatically. 

### What ReactJS concept will be used to create this play?

Components: (Custom)
Hooks : useState, useEffect, 
React Router Dom: BrowserRouter, Routes, Route, Link, useNavigate, useParams

### Are you willing to take it up for implementation?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elite16op** [comment]
Can I make this with the help of react and supabase if you agree ?

**Comment by afreen0102** [comment]
Hi Team,

Everytime i want to create a play.there is an 404 error.can you please look
into it

Thank you

**Comment by atapas** [comment]
@elite16op Let's catch up on Discord.

**Comment by elite16op** [comment]
@atapas  yeah for sure, here is my username Elite#3737
